apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-vm-operator
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 15m
  prune: true
  wait: true
  targetNamespace: victoria-metrics
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  path: ./flux/infrastructure/controllers/vm-operator/app
  dependsOn:
    - name: infra-cert-manager
    - name: infra-prometheus-operator-crds
