apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
spec:
  interval: 1h
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.17.2
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sigs-nfd
        namespace: flux-system
      interval: 30m
  install:
    crds: CreateReplace
    timeout: 15m
  upgrade:
    crds: CreateReplace
  values:
    image:
      repository: registry.k8s.io/nfd/node-feature-discovery
      tag: v0.18.3@sha256:f9ef2ebee55141a1758d3c0a87bb701f5db2adf6856f7218b11bc2bac7b63862
    master:
      startupProbe:
        failureThreshold: 60
        timeoutSeconds: 5
      resources:
        requests:
          cpu: 21m
          memory: 51Mi
        limits:
          memory: 51Mi
    worker:
      config:
        core:
          sources:
            - pci
            - system
            - usb
      resources:
        requests:
          cpu: 5m
          memory: 48Mi
        limits:
          memory: 48Mi
