apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
spec:
  interval: 1h
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.18.3
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sigs-nfd
        namespace: flux-system
      interval: 30m
  install:
    crds: CreateReplace
    timeout: 15m
  upgrade:
    crds: CreateReplace
  values:
    featureGates: null
    image:
      repository: registry.k8s.io/nfd/node-feature-discovery
      tag: v0.19.0@sha256:2fa1c99ad09bdf2c8ad97706a4ad2fd548c84d5ecd70ba32a6152c667b96c4d2
    master:
      startupProbe:
        failureThreshold: 60
        timeoutSeconds: 5
      livenessProbe:
        timeoutSeconds: 5
      resources:
        requests:
          cpu: 21m
          memory: 128Mi
        limits:
          memory: 128Mi
    worker:
      config:
        core:
          sources:
            - pci
            - system
            - usb
      resources:
        requests:
          cpu: 5m
          memory: 48Mi
        limits:
          memory: 48Mi
