apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-authentik
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18.6@sha256:a66f9e4c34950b78668fa4741bf55e6a58227cc31a6e60c128f2ce1d4c072928
  primaryUpdateStrategy: unsupervised
  storage:
    size: 2Gi
    storageClass: ceph-rbd-retain
