apiVersion: v1
kind: Secret
metadata:
    name: authentik-smtp
stringData:
    AUTHENTIK_EMAIL__HOST: ENC[AES256_GCM,data:TvhgoBOW+d/Xd0leDXk=,iv:EGj1nPRib8VfixZ1F5BX6Nr8+b0yOwXyDjO0DVX35+0=,tag:D1xKWaux2ix4ebXikjfoLw==,type:str]
    AUTHENTIK_EMAIL__PORT: ENC[AES256_GCM,data:mzE0,iv:bj2k07tgDIJNi0WJbeVmpfw3Gn9bipqhWcYNMffJ9FU=,tag:023qg2IiFDi2UM5B/hp0Bw==,type:str]
    AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:6dgal2lUd1p8Txjd5WFa/Hc=,iv:BywsDNklQ6pYHJe/lvueqo5PYpmD+Se9a1UbSZeA8gk=,tag:iRTdcubWUCHr0n5w57CX7g==,type:str]
    AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:a739l+3idQBdHCcW3lv/4N+Mmm6IMHQC,iv:ink/rC2vCJ5cSGzgtU+sCVGU5qZikQrxrX46cOHsDm4=,tag:fxReurvDUePSkPpO8WPLpA==,type:str]
    AUTHENTIK_EMAIL__FROM: ENC[AES256_GCM,data:/Q6wDK5VKX7eRKvrYquypdarNtmaT54wXuBUv5E=,iv:0g9yTwSEVEbq/Gtx2yCzKMCG3Tu4Oo2b8bMypfyPII0=,tag:q4awlWyROCNvZ9hPpxhxJw==,type:str]
    AUTHENTIK_EMAIL__USE_SSL: ENC[AES256_GCM,data:NX8yvQ==,iv:+mA3FtqrOtR7577hIOubb9fn29qrPLJIju5p1jRwrT8=,tag:CbcDvtgxbjng5sS2iiZ6SA==,type:str]
sops:
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvc2gyb3lnZlc0YlRCS0c4
            dG5rWS9JckdSY0hmcERiRkl1Ykt5dUsxWW0wCmIwVzU1YzVieGhrcWN4VXdvVmN6
            aW55YVFVZE12dTN6QVdHMHgzQXc4M3MKLS0tIFhGdFF5cWhYNHJ6Y2RlMzg0TXN6
            S09INDNHNFdRZk5xVTNjT1dDNUNQSmsK+r6oNRyxSqmH7N23JMCcNTtJJ2Ab+kHj
            8Gi6HnwZEoKU4bXBUlFcrP6nAVBZh3Sy20IS+vEXFzMSlfzM2KtXSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-28T18:07:37Z"
    mac: ENC[AES256_GCM,data:/uqk4qa9d9iygVifJUdm9NpgGy3zLCiCr1gyHjEh68NJnvwM4U4J7QDcQKbK97Z6woSIL6XH6sJIxMZbMEsUoRymsjhSe+EC1ijQLDz6U5PEs6Gt/USjOA+tBVYeE4b37kzK5XU0kZR7zD244IiiZ3J9vTjC0gxB6DhTNjJZ+Gk=,iv:WqEuIVRuZ3tNh7dQeFzoZvtMj7yio5Xn99jJ8hruuA8=,tag:NkUG9jlcLDuU5tfP/35dJw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
