apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:dg5OA/M0QhwI98cyLD2KBXyJKMlAEig+FC90GuvK3FS7UtyKmrCL+aIm2k+fGDfceRc=,iv:bHl8NEP1lHONpqixNFNhbmoveCag8J6tYs0WzKzIMlc=,tag:CRpcYC3FZ1EI2+IPqfEa+Q==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:qyLsT3G4HHSR5JEHVKmU9Z4/8JGNw8BeGytddB8ZdDQ=,iv:KwCfLaXTf51rDJt1U4ZybHDhFyTmqqJEft9N04hL+Jg=,tag:ZkrIKZr6MmrSdiFwTVH33A==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:4Yo1FFsSQs5w6Gz+8tzgsfOL2Ay59kXKe5r1bOWDPFc=,iv:RCgDg/nnpwTyREJ4WpS0FHsVkHZ2PVUKmLhgB6sokWI=,tag:FpQi84TJGtl7EfofjDGZdw==,type:str]
sops:
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUlRWU1ZyUXZXaXY1UHlP
            NTh6dUlTV0xTdmpldjMwNGptWnpNMGFHZVJzClpncVVyd0VUNUpDaWh0Vjh0Vm1C
            cWpHSzdMaU9hVlZzbHdYVzFURHRVQjQKLS0tIGpyTXBsNVk4MHo5N0lrNDlwTVRp
            MlEvWmhBRHhSRDdkQ2M1MnJ5Vm9vTTgKpwcaschkV8QB/iGEuSXQluvqm3XoMhAQ
            gjIroRNAAs4Q5TTL+g6JXkOx9N358VBCyMSIMopkeLG+JUhJPhD14A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-28T18:07:40Z"
    mac: ENC[AES256_GCM,data:6BNXbvG7KNfFmerlPNyNq4FsG1D97PlO9fvxkCY1d0VOAmWn090VL1N5D/baqD+cL7qrgNtcT3ooiqUzBb5F60U7ZRE/kg6bfOsOvVZBQ3Tdsd5/tJoq79/kiVFyQmcx3WzDccyoRt6rKhUY6q8bTGsgIHKC/1CNGQbGEvGkBDM=,iv:ibdOm6KWqk7zXE38G8rgGfitjjsKPN0ZYpSuVuCkHgc=,tag:tYWQBo1cabyyrMhdPIcwjg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
