apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubernetes-sigs/gateway-api-inference-extension/releases/download/v1.6.0/manifests.yaml
  - https://raw.githubusercontent.com/llm-d/llm-d-router/v0.11.0/config/crd/bases/llm-d.ai_inferenceobjectives.yaml
  - https://raw.githubusercontent.com/llm-d/llm-d-router/v0.11.0/config/crd/bases/llm-d.ai_inferencemodelrewrites.yaml
