apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stalwart
  namespace: default
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: stalwart
    namespace: flux-system
  values:
    certificate:
      certmanager:
        enabled: true
        issuerRef:
          name: "letsencrypt"
        dnsNames:
          - &host stalwart.nahsi.dev
    service:
      type: LoadBalancer
      annotations:
        external-dns.alpha.kubernetes.io/hostname: *host
      ports:
        http: 80
        https: 443
        imaptls: 993
        smtp: 25
        submissions: 465
    persistence:
      existingClaim: stalwart
