apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stalwart
  namespace: default
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: stalwart
    namespace: flux-system
  values:
    certificate:
      secretName: stalwart-tls
      certmanager:
        issuerRef.name: "letsencrypt"
        dnsNames:
          - &host stalwart.nahsi.dev
    service:
      type: LoadBalancer
    ingress:
      enabled: false
      className: nginx
      annotations: 
        nginx.ingress.kubernetes.io/proxy-body-size: "1G"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: Stalwart
      hosts:
        - *host
      tls:
        - hosts:
            - *host
          secretName: stalwart-tls
    persistence:
      existingClaim: stalwart
