apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yml
generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: ketesa-config
    files:
      - config.json
