apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: flux-system
data:
  CLUSTER: nahsilabs-home
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  annotations:
  name: infra
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  timeout: 60s
  url: https://github.com/nahsilabs/infra.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  force: false
  interval: 5m
  path: ./flux/clusters/home
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: config
