apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: talos-cloud-controller-manager
  namespace: talos
spec:
  releaseName: talos-cloud-controller-manager
  chart:
    spec:
      chart: talos-cloud-controller-manager
      sourceRef:
        kind: HelmRepository
        name: talos-cloud-controller-manager
        namespace: flux-system
      version: "0.4.4"
  interval: 60m
