apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valkey-hyperspike-operator
spec:
  interval: 10m

  chartRef:
    kind: OCIRepository
    name: valkey-hyperspike-operator
    namespace: flux-system

  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
