apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: continuwuity-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-retain
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: continuwuity-media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-retain
  resources:
    requests:
      storage: 20Gi
