apiVersion: v1
kind: Secret
metadata:
    name: continuwuity-secret
stringData:
    CONTINUWUITY_EMERGENCY_PASSWORD: ENC[AES256_GCM,data:g9GKUcqJd3FzdnyQVHErFVERToLubpDWUH6xsyNKMPE=,iv:RBVcIvq8DPQW6DahpP+sRNk0K4Xs+K3S2qq4eek/pa8=,tag:1Y1TfvuXsaLjDIa/aVr/Fg==,type:str]
sops:
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cTk2VE1jU21ZUUNSa1ll
            eU9hbHM1RG5vbXA1ak55MVo3ZDdNZWRyUjM4CmpvcjhKd3pYaDJKMXNzRHd0d1N6
            K1R2YmFsS0NJN3MvK0RuY0tHSG9PWGsKLS0tIEpiRWZwUGNPSGRVMG50L3lpRGlJ
            MEk1cEhmZkRXemFJdXRBUzNDeDRTQVEKhfgIHotoRbGoEkdzKpKHtntxaMTcPVko
            0P7TEqEWgn0Fze3HNVJPhGbCiZMnZTPsi2uXbJcA88zBfvi+seByEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T19:09:59Z"
    mac: ENC[AES256_GCM,data:kkaRKT8lM6nk9wSCwrM5djoOpS3FrsfGJWCsdZXvnzlNu3jX/GFdpNZblgc6eb5oKDHFK7bIvWVyzZU2sjJWfX1juEvJDIo6lkuhDQbc8rLc6+7Au30YNaQa0Bz9X0iXWOVOS8kDNxTC3NFBgKgUwbfwlKfIBTvS1Y5ES2XljxA=,iv:+dcwBa9Wb0nGOiG1QpZr8gthcapfBD1zV38Rc+Grx7Y=,tag:n0HC1GNK+M7mIDK3BeZZkA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
