apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-memos
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.6@sha256:899d3ed526b659d77935dde0e6bf2d69dbbf17d3d8c6486ca8cfd04bd3c18533
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
    storageClass: ceph-rbd-retain
