apiVersion: v1
kind: Secret
metadata:
    name: memos-oidc
stringData:
    memos-idp-authentik.json: ENC[AES256_GCM,data:TYYhsjZ/DbhlqVEgURGYkDVqMtBoYXSRPCSXbt8P2ROx/T8pHT3B3LjLjXWCe2JpupUlyZnl8uKSrpLeDZUpJKttUlGQi2JQzOdX9fTwCGBgHGOOYGUuCHDZSGTuInRis7TjycHEZIiV10IwyB3TZhUq/gin50LKWobfXV8Da5w0FLqOwF8ra2Jg674SQ8BYIwFlceMYzgpabKdQ2IdP9G1aA7sfgRVwFXVw1mR1OP+b6LeVtyVrvDY5DUISYtOYuUpxctZpbyRwrDMoTvET+nQvphgYttmWofJ+xFaaf1v+BjX6QGiAmr0x0iGz0tZblw9bsD8TPuS8wh4n5HRu6lRPnby0R0CRTwFVctmXNrAAHqm+RLZK5l0mX2kIP7qifBfV3ofAocRWUgtdoQ9GHEXlDZxjP8OA4sfxCBz+zfpwVOeV0Fcefjx+W6rJZiC8Bw7y8zCCewd3VfH+6ndzzwV2RPQYKKI39ms4rSJowJPOxh4mHv4Z6GublAAcV14o6nbSsKpjSi0bTSn22NygZV5fPP8yB4fR36+PMQPmZfWJsL+Rky0qqypn9u5SuzE+Hk5+ElR5+/gTZPXitfF1XUM7Tf/kDx/Qdd4uVAX6yUuzWGU+/4C+/W3C7btwlTNpSeOVLal41dNPdRRkddYuYY5gIGqiXLHtr2/6zJHBERhQn/cDx7cIbzgjaoMdQUySh2FAJzlJ1n392MaPOYt1REpG44MUGYQFRdV9ukgutQ5/5b7vqwqcSWLmY6DDmluLAYknGWye8Y/s8ddjvYUDoNmhA8TbtsMVF1SeUqZM5p/cpdzgPgcei9mOLZv2EenhrpPnHyXY1xT9m40mbb3a0lQNWsm/OjmoGueIFvK4//vAXcV6r5pl5AY3zRQsUbNjgrRvJRb3mBqsRtTqkxuJpdcFTXLIF00yjoZ10pGrYjXJ+eL1,iv:itSmylU7ce45TnJi022VpwHjweqNdPhVfQsVP8VJ6FI=,tag:QepBdPjGC2tEoTwEzSWpzg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SEpBL2duRXJidytHaFVm
            cElXaXJ4UzJ6ZXdzby82MTNacjhaMTJtdWtjCi90SEZpVk51bk41Y2lGN2JDckg3
            L2RFeHl3RWk2NjhROHNXQ0hVWGo0YjQKLS0tIEhwcmpUd09wc1VwUklwTFB2dUtD
            UlFocllKdWxGYTlMNWx6UlpWbVROcHcK7jlTVLS4Bm3XVrxJdq6YAzKz1B7/Qgkk
            QHAwuttoiv/Ppf803dpeteiZ3V5ZUWiZfDWXhUqAf4SbE01/x+k68Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T11:38:14Z"
    mac: ENC[AES256_GCM,data:Thfb3Kh8KapvPAO0YNYP8IhBGSxUlE1EO5yQtcUUvucWCOZzpHXPy+/5rSirfOepg246Mf2SBDl/cDIZ/GQ8vDOt2rjT4tzQH8TP5NIlbj1X7hf/R8pPkDmPTyZ+UOJ6YY4xt+/7ltJPNGjE1Uewz5BPGGqd/aMw9G8EwHmXpsg=,iv:kSQUSHZ6BcgcwbsiVgQECxVa2Gn1GUIAFQnm+Oo9K5s=,tag:lSVhkaM6dYz+n5HCGlBx2g==,type:str]
    version: 3.13.1
