apiVersion: v1
kind: Secret
metadata:
    name: memos-oidc
stringData:
    memos-idp-authentik.json: ENC[AES256_GCM,data:tYhDnVL+5zMJFMy/4ModAC65gHeO3TjFy8aDMuX/8/V1W4CQk2HP3eGDAabOT2gh8LqvDp5yYQCKuXt1Nw3pEtCvhHoONSDYcY5hrzhBTDQ/RJkSK3O+l2+kvP1x+tPoN+sXDAdWcenuHS5MuoF+Ov5UBGfj12/aq+OYUxSDBcsBbg/K7oNm0ktcMh+9RAtX5/vFvQ+0tM2+KnY2ZqodptockRGXrZkethDgCIRkyV8QKRgYToKeUUjZ1HgFT2yqutHkB99GluVMCpoGcRRxWqNl4FzEFTnunhGi//OS3vSldlmezVsLcUVBemzo8TUvAZxqsEPJHVVRB0Rxb3XPrKNQl4Nlz9tATWL/AB1YTd8+CpFsB8M06Cs6YbcZWLSvWw2YNy4a1BF1qZY5gLu51XNgXM3cdUxU75XWz2yal9sklVtiOT+WldleI/4+m8ZNSRErKKZBbJD1RcsWtKK0fa3MCyFS8MkyMQKzO+Dr8lycolOJ8PVEIqN5D8r1UAMXqG7SYRYNYhF8iPG9Nlg+aHQz2ZalZgN5Ig4UIQmSlT0GFKmAsNePmtLqmkX+CZNDWIuasWouACUtJnGheoOXdnQlD59isc3+Jqlw6w1kr/TrHMYADVR8HHBHGrLPbeYsyHIVOQ/tIV32ch8zTj7VCsc1t27L7Z/kBha+B1gowuVBNwiMhnSfTeIyUDIo/Ct86tJZn/5bVLHAi7DgrwNHVeZEtxi/t1QirKV5Km8fu/A4ImQu4cVirVLIiS+di3IhV2pG0eVCiXoDh10fLRsni2XlEinBf9WXDDGoiAcrZkfzgGlwaRSRs+8UmYJf8IrBIY7giWpoAt+UhRZwrHODW2GV2sasLkdMLUdgwBlo3CYXfHY0zbX9Wb4TNWto4M8JfJxmPM8MwLwld7SYL4iPqtjYzZI3V7/cCQ==,iv:T69dSQqz6/FBz/W8PKPGsT61VVlmuuEuCeahgobXzTo=,tag:J4ymXZdRr4ZYoaBHWrd8XA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZGVWSUJEZGo5VmZFenQy
            cjkzdUpNYjZvZmxHc3pIbnZDYWIwcE1HZlQ0CldPUjlzUTZuMVZhY3FiUHJpUFli
            NThNRVo3cnNHUGZMV3VSYnd5b3N2NFUKLS0tIDVMaU1CWTVYT2JnNklxY0h0U2JP
            L3Rqa1dHU1A5enJKcTgxbEh5dnZPYlkKOeydVDUIwPy32b9iz/zfQF+kTeKAi34M
            pcnzINcIRxfNLnPC7SA0WacxnOmI4p6edeWHyWMOLLlnWLdDVJKhxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T11:06:10Z"
    mac: ENC[AES256_GCM,data:LpZKOmI3hozLYVq/5WJEBp5tbL4bi6XZIFYZF222zMoKikYWtFVe4pVq0PwL1CGP+Pi61IwiEbUkR7RcJOh5SVgdYhs2HDUhVmHkiSK35ErmsEDVhLuGHyhy8wyMpo5Ai9FHhNhk19huD+QXA8q+UJhvRY8lqY8cLIqkw+Ee3ME=,iv:kh3gyp13cGw/9cqQOyKMdAVJvlZtiRDbSFmirBDc+Kc=,tag:nyAuSi50IQOnNF7q4W/bdA==,type:str]
    version: 3.13.1
