apiVersion: v1
kind: Secret
metadata:
    name: memos-oidc
stringData:
    memos-idp-authentik.json: ENC[AES256_GCM,data:ToLfrNBpoUkXuum04GEdDNlpo1BNxMGXa4Eqd6pMGQBN+T6Da74pqbmkgJrVeA0n7q5tC8A6RLDwP6Jg0IRkDw6tSVLOG8KIvALrw6YSMQrRdhAauwA20JyvCmEvIinWtD4DMdLxtZ/NJS+dJE0qwHJ4jwjPUX/0NjiKNtz59nS7M763o6wDo+Jvlob3acOTaaMl0HUkgMQupBbfgb5E6EHYw9hcv0REIPL2jtZp1Fo3QwhQ8Wt5z3UyjSuXQ05bgg6ANk91nU+icYxUVSA/Cq4TAi53DPEy/FJHRFR1yAHskzaMn7RjTxUwOh/my0Jyzh6iNdYQQ4Xc7K18Fkr4YHLq6blSJMgqmFH4YPv7qLBRG1XC9eqyY5NQ2FvhcPyaAzMXRzyZSd8u0Qp1gKV14km39QzbOgKRi6mqO/XbwOLnKyh8/HjasXFeQrB5OsbyuoweHh2jxNkHOr0bAmwmKgfjpuf9nLQYnqAA6+OM2gSVxhL1fluaYtOPWso134O3N9ZCMQl4ZIyobQUCfIYlemRxb/B4uuZ6osOPu7MTTYHWTclMP/dHitignBxOh9LCHts3hzMKRuTcg1YeIwmMI3HQcgfYZBib8xYHgFq6GfCAlqilAAAxRTEhy8i6glSUba+vOFJV6vuzEQMeqFbVOwnhdXe9O9vofPKZfieXqAEff4MF6oOt2cI+/D6YIryNrLYLkSxQPajdVlxK7XvBq6MA48DEO35li2LUHwNaOY8lJLggScB+TZgEow06siJDDFc1tbw9/lK84fggnJhULhw0Az+RYb+bHlZSkOQb69+iFC1rqCRlSMkGyzRqP2M7+5JQVmlBS4+pxNao9DXoS4Wokf7mxiOtLZava3gprHTgR3+9NrzidgKxUhvWN6kylENH7uG6FBzQgO1252CUX03LPio2emLMYnQoxIKfXiVnzGW+,iv:BpAKBsYoZiOnG01uo9Ch0XUgbG9+g+KxopPw4d/4lKA=,tag:Hhe6HW3FFrzJyeHGlPfVGQ==,type:str]
    memos-instance-setting-general.json: ENC[AES256_GCM,data:hIhK8BogxJVW91BzliYcNMQy6xBuiJ1Lmr9ueYi39Q1rhgRJdnVlW0R4iriDtApWtpSnjSBQE1jvpH0RzLiy9kI4B3XPHvK0vAfaz+0HjOf37csyRJjUP7gD3EQK/kf55K6KjS93wcE7DyBYmb2wICh6NbPJcbZMdx3IzZH9AxeSlLokVJK45R0HsNVcp8WsPhOR4nW1,iv:wxgylI2wFnV7+MEHSDOHC99nTo/olgR1wLwTpzXNTRM=,tag:5PdXy+uVp0J/J2wdDOodjw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6a2owVXRkN2gxYUlCRWlh
            ckczMi9FZEtVaUovSndkc2NRVTd6Tmc1Y2o0Cm5CZGNUYzltdFNQNTBRMVdMc0J4
            L1hjVHM4elZSSkF0UjhqMlAxQzlicEEKLS0tIGxKRG1pQmsvTTJpQ1o4K0NaZHVt
            dGhuTHhKSFV2RkxqQ0pMQ2RLR1pkZEkK6XcbnBj3PwV1d5yeJ4N2NF25/3I9crTx
            8IUkMP63JGNkgBuX8FPD18iCGBvU6P1C+VqddqwLIvMx0AgJO2itaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T11:48:02Z"
    mac: ENC[AES256_GCM,data:h25UjxLHnuH61PrBypLhm9poj4GxfX+wVFO9U33ZzHXforaak4/ylmcAwoPCYODJbIApB4F5pNBZeJ7J3lVj2SEl7lDNI3ua5DYTkIK5lNSmXwxqB2CgyxeOPYtUdR7M7vwbxeF0hyZQRCGL3U5/dmUh9iT9a4y7Cva4wHdTlpQ=,iv:cWHYYI4yuS6D4KNB7EL/pRR0yjwsrHjqQOjXq38aR5w=,tag:f10w8H7Tc8vUtDfncmvLkA==,type:str]
    version: 3.13.1
