apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yml
configMapGenerator:
  - name: kubelet-csr-approver-values
    files:
      - values.yaml=./values.yml
configurations:
  - kustomizeconfig.yml
