apiVersion: v1
kind: Secret
metadata:
    name: invidious-secret
stringData:
    INVIDIOUS_HMAC_KEY: ENC[AES256_GCM,data:/b3oz9H32h14bxamcBM9EtHgmdpcvahHdKazYnWown97Bpiow2o09rR44Dnj9s+ayXYjOXjWxXlDdIYguM79zg==,iv:eFknUwCPD2v9WAbv817UZq58eU67EAYEOgJBsoxc58I=,tag:VU526X9oKk5e8q98Xqx1uA==,type:str]
sops:
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NHdJRitITnFSZlNkWmZE
            RWRIU0JSZnBlNEJtcTBFY2xwTE5NRVpXZlRzCnlMS0tHd3lmTnAvb0xlWlgybDBZ
            OThLMHo4UXpZVzR0M2QzTis4emlod00KLS0tIDVJb1o4U1UydUd4aExzSHhxaXNG
            TU94VUtPQUhQQXIrMXg5YzR3VVpzWEEKAa0UcXaAeLNmSA72jT84Q+S/++IQ+Szi
            sTPGubkP3G+zNECdNtHfgqlBD0SqAQxJLzHockEXhV7QYJEaz9CM+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T20:57:34Z"
    mac: ENC[AES256_GCM,data:PDP6xfd2Y8RQqBlxgomquXenlAZzhLFw2jgY27JatIhXSAr377xAgxdZU54PYJpfoqBzfJ7rdC/xXrl+xAPjUTsOSFXSLhGDnMnX0tqr1oY1iU0Z537Nl9KqDEYuKQBAvNHuRVXgbTpdmTcqKwQhyPT6D6QMTwudsHNOr3390EQ=,iv:gPGGTv4OtGDVTUI0UqiLzDDPQQs56Zy6TqOC33cSUSs=,tag:VT1SgGFgvai0KnSqn2Js0g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: companion-secret
stringData:
    COMPANION_KEY: ENC[AES256_GCM,data:/dz2dOqS3xoQyvTYdkZshw==,iv:96lLGQmE/H2tvhleFgvUh4U4GSQjOncwxTW0zIkdmww=,tag:aGuKcQeLlM0mF6x6G9MC+Q==,type:str]
sops:
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NHdJRitITnFSZlNkWmZE
            RWRIU0JSZnBlNEJtcTBFY2xwTE5NRVpXZlRzCnlMS0tHd3lmTnAvb0xlWlgybDBZ
            OThLMHo4UXpZVzR0M2QzTis4emlod00KLS0tIDVJb1o4U1UydUd4aExzSHhxaXNG
            TU94VUtPQUhQQXIrMXg5YzR3VVpzWEEKAa0UcXaAeLNmSA72jT84Q+S/++IQ+Szi
            sTPGubkP3G+zNECdNtHfgqlBD0SqAQxJLzHockEXhV7QYJEaz9CM+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T20:57:34Z"
    mac: ENC[AES256_GCM,data:PDP6xfd2Y8RQqBlxgomquXenlAZzhLFw2jgY27JatIhXSAr377xAgxdZU54PYJpfoqBzfJ7rdC/xXrl+xAPjUTsOSFXSLhGDnMnX0tqr1oY1iU0Z537Nl9KqDEYuKQBAvNHuRVXgbTpdmTcqKwQhyPT6D6QMTwudsHNOr3390EQ=,iv:gPGGTv4OtGDVTUI0UqiLzDDPQQs56Zy6TqOC33cSUSs=,tag:VT1SgGFgvai0KnSqn2Js0g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
