apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: intel-igpu-exporter
  labels:
    obs.nahsilabs/metrics: "true"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: intel-igpu-exporter
  endpoints:
    - port: metrics
      path: /metrics
      relabelConfigs:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: instance
          regex: (.*)
          replacement: ${1}.talos
      metricRelabelConfigs:
        - action: labeldrop
          regex: exported_instance
