apiVersion: v1
kind: Service
metadata:
  name: intel-igpu-exporter
  labels:
    app.kubernetes.io/name: intel-igpu-exporter
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: intel-igpu-exporter
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
