apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-cloudflare
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: 1.15.1
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      interval: 5m
  values:
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns-cloudflare
            key: CF_API_TOKEN
    sources:
      - ingress
      - service
    policy: sync
    txtOwnerId: "${CLUSTER}"
    domainFilters:
      - "nahsi.dev"
    provider: cloudflare
    extraArgs:
      - --ingress-class=cilium
      - --ingress-class=nginx
