---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-soularr-downloads
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
    - nconnect=8
    - noatime
    - soft
    - softerr
    - timeo=50
    - retrans=3
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nfs.lan#mnt/storage/media/music/slskd#soularr
    volumeAttributes:
      server: nfs.lan
      share: /mnt/storage/media/music/slskd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soularr-downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: nfs-soularr-downloads
  resources:
    requests:
      storage: 1Gi
