apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: myspeed
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: germannewsmaker/myspeed
              # renovate: datasource=docker depName=germannewsmaker/myspeed
              tag: development@sha256:043c2f00980f5f1a91b44ad918a52ebb2d47dd6adc9c1abb738f048bf8a2ee94
            env:
              TZ: Europe/Athens
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true

    service:
      main:
        controller: main
        ports:
          http:
            port: 5216

    serviceMonitor:
      main:
        enabled: true
        labels:
          obs.nahsilabs/metrics: "true"
        endpoints:
          - port: http
            path: /api/prometheus/metrics
            interval: 15s
            relabelings:
              - action: replace
                regex: .*
                replacement: myspeed
                targetLabel: instance

    persistence:
      config:
        existingClaim: myspeed-config
        globalMounts:
          - path: /myspeed/data

    route:
      main:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: "Observability"
          gethomepage.dev/name: MySpeed
          gethomepage.dev/icon: myspeed.png
          gethomepage.dev/pod-selector: "app.kubernetes.io/name=myspeed"
        parentRefs:
          - name: private-gateway
            namespace: envoy-gateway
            sectionName: https
        hostnames:
          - myspeed.nahsi.dev
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - identifier: main
                port: http
                weight: 1
