apiVersion: v1
kind: Secret
metadata:
    name: ntfy-vars
stringData:
    S3_ACCESS_KEY: ENC[AES256_GCM,data:UApDKg==,iv:KR9LLUAzAA3pNc8z+OAZyLRwBiC+9jw0py2XP8kWF4A=,tag:c/ocWSaLFXDOL1Y4dObTkg==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:CNfGniQCmLl84wgV2/nFERoFzLeKfNXEn8EUwbD5c7GrQHAhbZoexMHLo+m5gVPFrrtmqeEVQaI=,iv:sWb6eGhQ5ncsllkfuad32bpkyb8ZldpL+sz2mNOepBs=,tag:neLCyBM7kt96fN24vdV2Tw==,type:str]
    ADMIN_USER: ENC[AES256_GCM,data:kaJhS5Nynufjr3HbPq2yoZwNijjxJ9OvO3t8agFW9L8nmtFdI7xs1XTh5KFBDLVp0ODDee3C5XgUttK3cdQsrco4q27kdPLO,iv:2uWb9DezOal0E+HtlEj80s753jRLxPkCCK2R4E5Mxt8=,tag:2cE+ww9oD1hws1/Zf295yw==,type:str]
sops:
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUTBMNFpyaVNuYVFzcnc2
            M0YrcXY4ZHR6Ym83S3N6REhNcStvdDdCT3pFCi8yRTF5ckozWHZ4M24vQS9Pekdj
            QXE4MXlwZ0RxQ084Y0g1WmwzV0VDVUkKLS0tIEl2Ti9KNVlPMmlJWWNJT1lTTEg5
            TmtyTFZJZWJmeWdJVzdaTytVYzl6TkEKXjwRhBPdDBAC3pN8sfOSvF759wJmmj7p
            4TAsEU2HcGOtkhDzm+xNzRSuNGQzj4S1D4Kku3V8F2qpiLnvrtNwrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T07:29:46Z"
    mac: ENC[AES256_GCM,data:+LQGUGHyx0KWYRuKY2mL6qh2MSUIkNQHW3zD71HE6QDJIrG/8Sy9FcheTCrnt0mHW/PrVVxE4IdrhbwtD9uraPqYz9QN7XD5Gin+Lnt2l/jSKVB4tf1TbKN1MXI2LnlTckRp0i81megmX//lZacTpUgqHLAc5OTFcCAZi/CKj7M=,iv:rPX8FL5Xrt7aeWtgxRTRHKwX4RPAQhXW4SkJD/PPhEE=,tag:rLbT71E3SxawXXc61GqAng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
