---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-synapse-deps
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-cloudnative-pg
    - name: app-mas-deps
    - name: app-mautrix-telegram-deps
    - name: app-matrix-secret-store
  path: ./flux/apps/matrix/synapse/deps
  targetNamespace: matrix
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 10m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-synapse
  namespace: flux-system
spec:
  dependsOn:
    - name: app-synapse-deps
  path: ./flux/apps/matrix/synapse/app
  targetNamespace: matrix
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 10m
