apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy-gateway-private
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  description: "Private Envoy Gateway for internal traffic"
