---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-downloads
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-qbittorrent-downloads
  mountOptions:
    - nconnect=8
    - hard
    - noatime
  nfs:
    server: nfs.lan
    path: /mnt/storage/downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-qbittorrent-downloads
  volumeName: qbittorrent-downloads
  resources:
    requests:
      storage: 1Gi
