apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-snapshot-class
  namespace: flux-system
spec:
  interval: 1h
  timeout: 5m
  retryInterval: 2m
  prune: true
  dependsOn:
    - name: infra-snapshot-controller
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  path: ./flux/infrastructure/configs/snapshot-class/app
