apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      jellyfin:
        pod:
          nodeSelector:
            intel.feature.node.kubernetes.io/gpu: "true"
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: docker.io/jellyfin/jellyfin
              tag: "10.10.6@sha256:96b09723b22fdde74283274bdc1f63b9b76768afd6045dd80d4a4559fc4bb7f3"
            env:
              DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
              JELLYFIN_PublishedServerUrl: https://jellyfin/nahsi.dev
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8096
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 100m
                gpu.intel.com/i915: 1
                memory: 512Mi
              limits:
                gpu.intel.com/i915: 1
                memory: 4Gi

    service:
      app:
        controller: jellyfin
        type: ClusterIP
        ports:
          http:
            port: 8096

    ingress:
      public:
        annotations:
          cert-manager.io/cluster-issuer: nahsi.dev
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: "Media"
          gethomepage.dev/name: Jellyfin
          gethomepage.dev/icon: jellyfin.png
        className: "nginx-public"
        hosts:
          - host: &host jellyfin.nahsi.dev
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

        tls:
          - hosts:
              - *host
            secretName: jellyfin-public-tls

      # private:
      #   annotations:
      #     cert-manager.io/cluster-issuer: nahsi.dev
      #   className: "nginx-private"
      #   hosts:
      #     - host: &host jellyfin.nahsi.dev
      #       paths:
      #         - path: /
      #           service:
      #             identifier: app
      #             port: http
      #
      #   tls:
      #     - hosts:
      #         - *host
      #       secretName: jellyfin-private-tls

    persistence:
      config:
        existingClaim: jellyfin-config
        advancedMounts:
          jellyfin:
            app:
              - path: /config

      nfs-nas-video-library:
        type: nfs
        server: nfs.lan
        path: /share/media/video
        advancedMounts:
          jellyfin:
            app:
              - path: /data/video
      tmpfs:
        type: emptyDir
        advancedMounts:
          jellyfin:
            app:
              - path: /cache
                subPath: cache
              - path: /transcode
                subPath: transcode
