apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  persistentVolumeReclaimPolicy: Retain
  resources:
    requests:
      storage: 5Gi
