---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  persistentVolumeReclaimPolicy: Retain
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-video
spec:
  capacity:
    storage: 1Gi # doesn't matter
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-jellyfin-video
  mountOptions: 
    - "nfsvers=4.2"
    - "nconnect=8"
    - "hard" 
    - "noatime"
  nfs:
    server: nfs.lan
    path: /share/media/video
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-video
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-jellyfin-video
  volumeName: jellyfin-video
  resources:
    requests:
      storage: 1Gi
