apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen3-8-27b
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-delete
  resources:
    requests:
      storage: 25Gi
