apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: llama-cpp
  labels:
    obs.nahsilabs/metrics: "true"
spec:
  selector:
    matchExpressions:
      - key: app.kubernetes.io/part-of
        operator: In
        values:
          - llama-cpp
          - ninfer
  endpoints:
    - port: http
      path: /metrics
