apiVersion: v1
kind: Secret
metadata:
    name: fastcrw-auth
    namespace: search
type: Opaque
stringData:
    CRW_AUTH__API_KEYS: ENC[AES256_GCM,data:jSAiFdVyvYJSJTINk0S7H9vB+unDQtzx0+E92AxLmqu55xrDd5jNASE1C32azVi6oQifSXlYPfU210aPyxO0Sg==,iv:coHrw7H8/gnKPljL3RIBFREnkQZgCSMuLob2W1EXAyI=,tag:qEoTtfTT9ISzlLXOSKhSLA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJM2l1VlhrSmZSWmlnLzZv
            cElqdGxKYTRZQ21ITHovcjIzWFJpUis2YlFJClF5YXZuU2pWNk51dFRKRG9pNW03
            RzFQWmt2NVBKNkJYNmRIenUxblU5M0UKLS0tIGVhTFQ4VldrWEMrc1ZINldRSndR
            enZOK1lqZDdwMUJMQ3ZxWjVMNXQ5MHcKae+vXdlOSirXTzk26HLlI9n7il401Qc/
            T4XoqaGyW9dbqc5fs+9zwMfRXO0/nxJSVqTsKUtq7Aa+Tn0YtCfxXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T09:16:41Z"
    mac: ENC[AES256_GCM,data:jETJvXnYxX3YphfJC1RVqNV0e5VyouS9z4CzQXFuJubcn6/eacOSLLqslqTFsCHP2gL79OxiB1KZ7mA6BgK/AzWyh8vnPXRXg4GBK2rJvQYanZctB0GkmHCf0QmuUfklaRLxlgLIhiW+YveCGq/ZkY5iqX+wC3lAJ765QgWA8A8=,iv:XAywd2zkQW4mFoYVxFcxILAG/8092M7NAyji1lR/t3E=,tag:gR3RLY1w6jVkyks6oKKL5g==,type:str]
    version: 3.13.1
