apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dashboard.yml
configMapGenerator:
  - name: intel-xpumd-dashboard
    files:
      - intel-xpumd.json
generatorOptions:
  disableNameSuffixHash: true
