apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: owncast
  namespace: default
spec:
  persistentVolumeReclaimPolicy: retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
