apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-dawarich
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-minimal-trixie@sha256:4c993b05333eedf197565deda1234334a4e1ff63fd8a5e6e3371cf261d2bb73e
  primaryUpdateStrategy: unsupervised
  postgresql:
    extensions:
      - name: postgis
        image:
          reference: ghcr.io/cloudnative-pg/postgis-extension:3.6.2-18-trixie@sha256:93584892e25a57e47e988b0f80ad9988035d1396d4a87824307eddf2242348c8
        ld_library_path:
          - system
  storage:
    size: 10Gi
    storageClass: ceph-rbd-retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: app
spec:
  cluster:
    name: pg-dawarich
  name: app
  owner: app
  extensions:
    - name: postgis
      ensure: present
