apiVersion: v1
kind: Secret
metadata:
    name: dawarich-smtp
type: Opaque
stringData:
    SMTP_SERVER: ENC[AES256_GCM,data:5/ZaWIcRmg7NtYEsGNQ=,iv:xn+/RnWHb7nAnw0GUC2EQs+GYu7NhTxJGpL5zYPj3cc=,tag:baMB0ebaPhoaQ4I2bINnRw==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:Qok7,iv:2Z8tfPP4ycvw1YTVPUtmi3xz/MzamLgHfICr+X7P7BM=,tag:ISJ6chbt8gaJCldFPJlNZg==,type:str]
    SMTP_DOMAIN: ENC[AES256_GCM,data:Pd30q1K+TFKC,iv:QkPXXoPcjkuFPfZrkf8uKSL4UZdKpwp2052T8WjfjQw=,tag:vAWdJbY+7ocxOPeuiW17RQ==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:K55z+2i8InaCNxF1ui1zMJc=,iv:xvSfpsupdNgjSyr6Wn/y22k3ZriFwheYHV311nDTmas=,tag:eC0e5MEc4PngW+nuroMKOQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:dk4gpXvql+5Lye0CZv0RryDIhupr14Qh,iv:BVwy9cVHY2rNqXmksZLdy3TttL+B9ucOYs0ZOjmElh0=,tag:gYsNpvDIjIZAK2khnVGq0Q==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:1hhnxK73e4VKm5mrNbyTn44=,iv:AgIyHRKh36sME+0Bt6IRWXpJd4INyRjnD2yp03n5bio=,tag:FtgR251pvoKK0Z6txNlpfw==,type:str]
    SMTP_OPEN_TIMEOUT: ENC[AES256_GCM,data:eg==,iv:MvcWdWSEVUNDnNEVx1pCG6yHq7ABxbmnvJIIzg1GU6U=,tag:AXmgvXp+++mfM6nu61BX6g==,type:str]
    SMTP_READ_TIMEOUT: ENC[AES256_GCM,data:nQ==,iv:3MruI2+D1k5JJOW0zTAV/FHQVZAdyufCyn4ke2hJyEQ=,tag:Zke9fpllbxXlVvOdqHmSMg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdSsxT2g5aVRXc015TE9H
            TVY2a09RSDVyRU9DdGF5SnU0Z3EwZ0g5TTFZClJqbUpobU5XSnFMbERQZ283MFpU
            VVRyVzYvdVlha2lnRnBRQ0MzdDBYUXMKLS0tIGdWZHBMUlhXZ3g0Tml2VkcwTWNl
            K1BWK0QzNnI3b3pGOC9vdG9RNjFTdk0KIyMLUe/3rV3SU7QiUgRhvM8xjohsZCFr
            9VKN/as0jieRpL+zFX/3WxbAlz+RQb2A+/9HhSLErjSpKSPFTzLf2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T20:14:34Z"
    mac: ENC[AES256_GCM,data:gneydKq+dUkAef9Ut1Hm+qZjPjmZQcx2halqiz5Kk38u18y3PJL56G2+CeUXXHiv32udxlSzcxjPBARvL/i73LxiRsuhPS6TlNgg2SyMPTqwRewrexQDYmmXYkDjBxJMZdln9XkMVXFIcPYGlPa8Ma1e5x2uMAvAypJKdgXN0O0=,iv:+9RQC++2kQBoQVGwXOWCjosfF7GE/EhPifoTc3qKAVc=,tag:OFg00pCHBKIRetYBWciS7A==,type:str]
    version: 3.13.1
