apiVersion: v1
kind: Secret
metadata:
    name: dawarich-secret
type: Opaque
stringData:
    SECRET_KEY_BASE: ENC[AES256_GCM,data:o6BRT++8disIhL4An1CiQtJs7h1/Ta67O0SDPoHJyQrshIRxYuCikdoaN2L1OOasjyxm7cD3THsjzoP6SYV2rA==,iv:DpdLv3khKrUZni7/KA/U1Y89lQhz6qD1GIv3ILYjPs8=,tag:BleY4SubAD3QrElbD+ne/Q==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:AUuG0ren+6+y102It91GYQ==,iv:ENUGNkGcQBSLLnTvHLxb/m2OMxOnr9j/3XM0uc0gNJI=,tag:uKhVcBHrOXHyP5uvP6AvBQ==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:ilUeeBtbkGzH3MoGfe5MNjWubKUGYNZuVl9rDroTxZV6GADO9hx3jECp7+GhaNaFrevrnH2T0xOrKELwTwV/HFJsdew0PFa+fm0ziGgKv83JfUJCF1/Au6Q/gr9kabA4m8sMAR2CCyzxsNi/60qvNcZDgFJnixKrbHveXe3Fwcc=,iv:KxZ5Jtku+svQsS43gGvTaaj0z2KXMDFYDkGCX0JnJnQ=,tag:5438xo0JOk/Yt5NTQqyEAg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaGdHQWw1aHpvd3ZWcDVy
            RjFDRitmNUlhMk5DQVJZaDBDZ1VXQit6ZUNBCkc0U05CcC8xUGI2WW1NcVUxM05W
            Y1JMYVFSdEpRRWtXSHlkYVpHb1pHcFUKLS0tIEFMMWZsWkxjMjM3UGhyMUlMRXJh
            KzNuWlBVdkZzNXZkek9LWFZ0SFRzSmcK6dTcfGxQNIRUAYN7g24jR4i17MMJ4iZ4
            jWfnzsUda9s+ryDPvwnjsUdPTsRxw9EPlKWGA/2I9JPJPZ7e1TDdFw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T20:14:28Z"
    mac: ENC[AES256_GCM,data:h8AFTYLRIE8AYuHP2aWdb/OI2lPdMfr/DmQGbIsMTtNTGac644Es22smoQE4wsm4YObey8PaDtZLZaRfZRdY7dZpQ2+npxlOobE7U+9oL4MGVWOI6rg+mLEVaQktTzzKcRnCFrtei6dMmxAlnuNDafEHSGjsJ7pf6FJwBDvO3eg=,iv:u3zT5TS8+OvCXOi6DYXWDI0qADO5SzBilTZvTEOz/2g=,tag:bS5pnID5itdP42hNPmUryQ==,type:str]
    version: 3.13.1
