apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: translategemma-4b-llm
spec:
  ai:
    provider:
      custom:
        backendRef:
          group: inference.networking.k8s.io
          kind: InferencePool
          name: translategemma-4b-inference-pool
          port: 8000
        formats:
          - type: Completions
            path: /v1/chat/completions
        model: google/translategemma-4b-it
