---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: navidrome-music
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-navidrome-music
  mountOptions:
    - nconnect=8
    - hard
    - noatime
  nfs:
    server: nfs.lan
    path: /mnt/storage/media/music/library
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-music
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-navidrome-music
  volumeName: navidrome-music
  resources:
    requests:
      storage: 1Gi
