apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: owncast
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        replicas: 1
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: owncast/owncast
              tag: 0.2.1
              pullPolicy: IfNotPresent
            env:
              TZ: Europe/Athens
    service:
      main:
        ports:
          http:
            port: 8080
      rtmp:
        controller: main
        enabled: true
        #type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname:  owncast.nahsi.dev
        ports:
          rtmp:
            enabled: true
            port: 1935
            protocol: TCP
            targetPort: 1935
    ingress:
      main:
        enabled: true
        className: cilium
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: stream.nahsi.dev
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - stream.nahsi.dev
            secretName: owncast-tls
    persistence:
      config:
        enabled: true
        existingClaim: owncast
        globalMounts:
          - path: /app/data
