apiVersion: v1
kind: Secret
metadata:
    name: flux-mcp-oauth-proxy
type: Opaque
stringData:
    OIDC_ISSUER_URL: ENC[AES256_GCM,data:IGUFKcMq4MQjboL9/I9EuV9VB0a2Wz1WuE51xTPNIjxak21tR1kYXYyrvMDj6w==,iv:g4blWXF5EGRaz7h1SaTBN/vxirZVlUKdhwrkAUN4TM0=,tag:zZi6Eaz7TUv8qzUG8/InPw==,type:str]
    OIDC_AUDIENCE: ENC[AES256_GCM,data:QFZ9gx2LFY2FlHso/sfvaA==,iv:sVbKlCSEL4yVdLslVuqxTc8ZVVV8nNzHLQ67De5zYIc=,tag:Cn+nWWtz/io8ssZy2vRyVQ==,type:str]
    RESOURCE_URL: ENC[AES256_GCM,data:Vy1wITdTZK6msHWSJS2PYFhAhhc9qSpTebF5h28=,iv:QvP+0sTIu2OTVcWH3KoSu3E6tZaBMtesPJiavJI5CkY=,tag:6ZuqZmxgzjsiBwN9zEMmxA==,type:str]
    ALLOW_GROUPS: ENC[AES256_GCM,data:eA+5zqUAJAn2aA==,iv:ZYYQF6NBQQLga6W/yKo4PObgm/FdkF2bSmyOqhLn3pQ=,tag:/Lu6nF9cWRXYj+9SwUbmAg==,type:str]
    MCP_UPSTREAM_URL: ENC[AES256_GCM,data:5KKucjW490FhGzq9d+sDTPbs6wPDQENioNCbGzHY2rjTpDQ7xIfzOxo=,iv:2Z3FqDFVo1D8S5yY7iF8gxmq0yqU101zUbYS6u2FwHo=,tag:FPzyzc9AVjbDtTQnhoqdtw==,type:str]
    MCP_UPSTREAM_PATH: ENC[AES256_GCM,data:n3ASdA==,iv:9ZU1WMDscD6t2bDcwYrwwvQYMk4jrWGCsph0digUnk0=,tag:qBte06L7UAQHn1u3T37PMA==,type:str]
    STATIC_CLIENT_ID: ENC[AES256_GCM,data:tZoVTyADCbORT4Sqf4Xruw==,iv:wopQkck+gtgH+QU6mafZqUz3Qg4VTCK9N8GvqdKr9Is=,tag:4CUfK03mz8xLGCWZM6ljfQ==,type:str]
    STATIC_CLIENT_SECRET: ENC[AES256_GCM,data:d7+1n8xPaVQ3aNDCp8BqI5FDgvUXh5xhRD0WypttHhts1KprY1m+CxHJrewB4n7Zc+XQz7i+BYSrC+bFLpwPEuQjI33xZlGZGIm7hcC/kxB4T715nBEHuRMrkohmoyBRfOBCeBxYitlu46n11SoapjA5/Emm4Pd3uE6SKBUWikI=,iv:a7HajHzckvOI4IhaCOIyxlSebvel/R6r5pEn3pMAOc0=,tag:rKCkV/Ig9FtTth91dxxbDw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3YW43a3h5SHUvOW5jZG55
            bDhCeTlKTXk3ZW00NGNjdzBkNDlTaHR1QW1zCmYybFdGellLUHR5V1Y0U3dVSklE
            R09xQUdEbTdPSDFVR1RoL2tPdmJwd2sKLS0tIC9NN0VscURmZ212YmJINEpvTXNH
            NHA2SFgzZWdoTTM1RVJHV1JDWFRkZEEKP1w2s0GSaEoNVNmYgxumLmXyVsT1oO0o
            OrH3TZ40HJ//xNj6MpT1zxpr6sIk/L+5EjnmqoqaQ9kmOAQPJdW+9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T08:11:48Z"
    mac: ENC[AES256_GCM,data:T+JFdVP+Aqz6n8r6aIANNaYILH2GGwz+KJwZ1AlKgn1gHB4IsK1Lj3JykmRZqIo0bztqC6SKwAFMyvmPxq1wShQ4q9XSYlL6xwmv8qOkbhA81ZCAKGgOm0MWXYgBgdq1oMsA+0/Ei0O0cl2zMqEyyR1Yq8nc90Il7iQ+SKENlVs=,iv:T3Qvx6vHSUcgwMb2JIlXP+9OMSYBDSrKXXtKObJf8Z0=,tag:sk7fCwzUyH/B+F6h/93Obw==,type:str]
    version: 3.13.1
