apiVersion: v1
kind: ConfigMap
metadata:
  name: evebox-config
data:
  evebox.yaml: |
    authentication:
      required: true

    agents:
      allow-unauthenticated: false

    database:
      retention:
        days: 7
        size: 8 GB

    input:
      enabled: false
