apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-grafana
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4@sha256:b38bee8f92acd6d7276d5be32e9af36a0ea72c9d339945f1ae205a2acc3cbb89
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
    storageClass: ceph-rbd-retain
