proxmox_grub_cmdline: "quiet amd_pstate=active iommu=pt kvm_amd.nested=1 kvm_amd.avic=1 kvm_amd.vapic=1 amd_iommu=on hugepagesz=1G hugepages=84"
proxmox_modules: |
  vfio
  vfio_iommu_type1
  vfio_pci
proxmox_modules_options: |
  options vfio-pci ids=15b7:5006,1b21:1182,10ec:8125,1000:0087
  softdep vfio-pci pre: pci_stub
  blacklist nvme
  blacklist r8169
  blacklist mpt3sas

proxmox_network: |
  auto lo
  iface lo inet loopback

  iface enx5e46417fa2c3 inet manual

  auto enp41s0
  iface enp41s0 inet manual

  auto enp42s0
  iface enp42s0 inet manual

  auto bond0
  iface bond0 inet manual
      bond-slaves enp41s0 enp42s0
      bond-miimon 100
      bond-mode 802.3ad
      bond-xmit-hash-policy layer3+4
      bond-lacp-rate 1
  #Management

  auto vmbr0
  iface vmbr0 inet manual
      bridge-ports bond0
      bridge-stp off
      bridge-fd 0
      bridge-vlan-aware yes
      bridge-vids 2-4000

  auto vmbr0.10
  iface vmbr0.10 inet static
      address 10.2.10.40/24
      gateway 10.2.10.1
  #Infrastructure
  
  auto vmbr0.11
  iface vmbr0.11 inet static
      address 10.2.11.40/24
  #Proxmox

  source /etc/network/interfaces.d/*
