proxmox_network: |
  auto lo
  iface lo inet loopback

  auto enp1s0
  iface enp1s0 inet manual

  auto enp2s0
  iface enp2s0 inet manual

  auto bond0
  iface bond0 inet manual
      bond-slaves enp1s0 enp2s0
      bond-miimon 100
      bond-mode 802.3ad
      bond-xmit-hash-policy layer3+4
      bond-lacp-rate 1
  #Management

  auto vmbr0
  iface vmbr0 inet manual
      bridge-ports bond0
      bridge-stp off
      bridge-fd 0
      bridge-vlan-aware yes
      bridge-vids 2-4000

  auto vmbr0.10
  iface vmbr0.10 inet static
      address 10.2.10.20/24
      gateway 10.2.10.1
  #Infrastructure
  
  auto vmbr0.11
  iface vmbr0.11 inet static
      address 10.2.11.20/24
  #Proxmox
  
  auto vmbr0.12
  iface vmbr0.12 inet static
      address 10.2.12.20/24
  #Ceph private
  
  auto vmbr0.13
  iface vmbr0.13 inet static
      address 10.2.13.20/24
      post-up ip -4 route replace table 113 10.2.13.0/24 dev vmbr0.13 src 10.2.13.20
      post-up ip -4 route replace table 113 default via 10.2.13.1 dev vmbr0.13
      post-up test -n "$(ip -4 rule show priority 100 from 10.2.13.20/32 table 113)" || ip -4 rule add priority 100 from 10.2.13.20/32 table 113
      pre-down test -z "$(ip -4 rule show priority 100 from 10.2.13.20/32 table 113)" || ip -4 rule del priority 100 from 10.2.13.20/32 table 113
      post-down ip -4 route flush table 113
  #Storage
  
  source /etc/network/interfaces.d/*
