proxmox_modules_options: |
  blacklist nvidia
  blacklist nvidia_drm
  blacklist nvidia_modeset
  blacklist nouveau

proxmox_network: |
  auto lo
  iface lo inet loopback

  iface nic0 inet manual
  iface nic1 inet manual
  iface wlp5s0 inet manual

  #Management
  auto vmbr0
  iface vmbr0 inet manual
      bridge-ports nic1
      bridge-stp off
      bridge-fd 0
      bridge-vlan-aware yes
      bridge-vids 2-4000

  #Infrastructure
  auto vmbr0.10
  iface vmbr0.10 inet static
      address 10.2.10.70/24
      gateway 10.2.10.1
  
  #Proxmox
  auto vmbr0.11
  iface vmbr0.11 inet static
      address 10.2.11.70/24

  source /etc/network/interfaces.d/*
