apiVersion: v1
kind: Secret
metadata:
    name: searxng-secret
stringData:
    SEARXNG_SECRET_KEY: ENC[AES256_GCM,data:GCy6osL45fzEBSJZtFe6JRxGqBpa9rL6vPBGYA48JDONePIbSJzAx3sFCQRypeSem/jMDL8+/SmO/TNPkNVjcg==,iv:eq1v1HaU6LqilvK1pE5VTJV+NCYfgtzKsKMcXZoKuWI=,tag:JjSKCOxVbhmm7sQkrVQ6AQ==,type:str]
sops:
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVS2UrNjlWYVhtUW0vd0w3
            VXRCTW5SZDI2czJKblFxbDM1WHhTM3c2RW5JCnRyTUI2Q1VKWUVpbFJBZ2pjdC9l
            T3JwWWQwVmZmY1pibUREREt2Y25qNzgKLS0tIDVidDY2NkVFaENBWXp4aktLSDNa
            b09Ic1R4c2ZhVDFQaktRbHJ6cHdVK00KI9Z1d5Z+jic/t7sbvRX3kKI9q5NmiMJa
            Ymo+j901UMuN4lLCvS9qD0er1AE5x6CwEvhIpIpA7gsr2dmGTLlJGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T19:33:02Z"
    mac: ENC[AES256_GCM,data:bMWxqJrhaZjS3wi+amukZNrRH7UoSxgp8LFQE8T54WARDtbv1cI56rq9TeKuge6bjxe+bKQOUUm7nEFHeEFOOW1ckgTc638YwUJ8tjZEtlHSj/aNiWqB4a7c4MQgexRI8ZT/nI8VGlgzF2eWfkW9KyZxVIy98pbj14lDT1t1zug=,iv:YcJwF8Jm7bOIaXhUkn4G2qUaU/2uqUaF8wu2Cjyv138=,tag:gLqHqNidigPmO2EyfVyyIw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
