apiVersion: v1
kind: Secret
metadata:
    name: searxng-secret
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:S4l7Oad6RIwdl2tXPSCM+1Ur/PmBo2zTVvz7wxLYqyA5z9qImC25sLjO1MhoKevEnJzrMCHXxFLmR1HAAeWwXA==,iv:hQxPSdSp9wJrigYg7Kffo6j5rMiF1UgVp4mmKTmMxQo=,tag:I5g1zZg5SaTWyF4JXzYOAw==,type:str]
sops:
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MSt5WSs3UGZ2UGxlNmxK
            amZCLzFpTGlkZXlEamJWb2lCOG1jcFlvdjJzClRVdDZXZzBneHg0dWljcDZWREJ2
            V2tTSUdodUtnOEo4WE4wUG1XZ0lBYjAKLS0tIGtDNGtCMDVJM3dqc2hXQm56c1NH
            SkJTeHlUVjBwZkxFd2RvWUh6Yit4U0EK87aVMRfWubQYO2Dm8NwtKDFU1NOK4WZE
            SpX7ldfTbHpim9S34+ocYMLVHkUufZe5d3sNfXJGw+lMQKC0bUPvWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T20:20:09Z"
    mac: ENC[AES256_GCM,data:mF7Kj44JPxy+2QWlUeCwsx3i63HPJ7pg8Bpg0R2wEZ/oQZmae2vDdWcUyRm7jZBdw42XKVV4pnj/6gpHXyJQSsCZ4FJu8C7ffgpeFXTeZv/RebCz23BZcWe654f8D96+aJdoDP3ZkfWYzEipQ4ooryI25azFbq2cqh5XphmfTEc=,iv:LxuJHE3PsU9M8KXxq0NtrJu9HOlkruy+HWlL4zr5+uU=,tag:1i1/r49tVt7tDYtoyAxPbA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
