use_default_settings:
  engines:
    keep_only:
      - brave
      - duckduckgo
      - startpage
      - github
      - stackoverflow
      - reddit
      - duckduckgo images
      - brave.images
      - startpage images
      - duckduckgo videos
      - brave.videos
      - youtube
      - openstreetmap

general:
  instance_name: "SearXNG"
  enable_metrics: false

server:
  limiter: true
  image_proxy: true
  method: GET
  public_instance: false

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json
  ban_time_on_fail: 5
  max_ban_time_on_fail: 120

outgoing:
  request_timeout: 5.0
  max_request_timeout: 15.0
  pool_connections: 100
  pool_maxsize: 20
  enable_http2: true

ui:
  default_theme: simple
  theme_args:
    simple_style: dark
  infinite_scroll: true
  query_in_title: false
  results_on_new_tab: false
  url_formatting: pretty

plugins:
  searx.plugins.calculator.SXNGPlugin:
    active: true
  searx.plugins.hash_plugin.SXNGPlugin:
    active: true
  searx.plugins.self_info.SXNGPlugin:
    active: true
  searx.plugins.tracker_url_remover.SXNGPlugin:
    active: true
  searx.plugins.unit_converter.SXNGPlugin:
    active: true
  searx.plugins.infinite_scroll.SXNGPlugin:
    active: true
  searx.plugins.ahmia_filter.SXNGPlugin:
    active: true
  searx.plugins.hostnames.SXNGPlugin:
    active: true
