apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kroki
spec:
  interval: 1h
  chart:
    spec:
      chart: kroki
      version: 6.1.0
      sourceRef:
        kind: HelmRepository
        name: cowboysysop
        namespace: flux-system

  values:
    image:
      registry: docker.io
      repository: yuzutech/kroki
      # renovate: datasource=github-releases depName=yuzutech/kroki
      tag: 0.31.1@sha256:9cdc4aac5f54fabc7f8bb041ea7c4c0f0a0ffa178cc0a31541a6d312daa3731b

    ingress:
      enabled: false

    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi

    diagramsnet:
      enabled: true
      image:
        registry: docker.io
        repository: yuzutech/kroki-diagramsnet
        # renovate: datasource=github-releases depName=yuzutech/kroki
        tag: 0.31.1@sha256:195f89d3af451659916ec54fbd2ebba1d5c02914e0d35216b8515b3df7c218cb

    excalidraw:
      enabled: true
      image:
        registry: docker.io
        repository: yuzutech/kroki-excalidraw
        # renovate: datasource=github-releases depName=yuzutech/kroki
        tag: 0.31.1@sha256:9b3b1f6e8d8fd9a9c4356fd1353a04c89881971417d14bcf5a0cbfff80aa550e

    mermaid:
      enabled: true
      image:
        registry: docker.io
        repository: yuzutech/kroki-mermaid
        # renovate: datasource=github-releases depName=yuzutech/kroki
        tag: 0.31.1@sha256:d711507b5c4c0ab5764a188e5643119dc084f222c1cc951e8c2512fc20f80a0f
