apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kroki
spec:
  interval: 1h
  chart:
    spec:
      chart: kroki
      version: 6.1.0
      sourceRef:
        kind: HelmRepository
        name: cowboysysop
        namespace: flux-system

  values:
    image:
      registry: docker.io
      repository: yuzutech/kroki
      # renovate: datasource=github-releases depName=yuzutech/kroki
      tag: 0.32.1@sha256:6980bfb218b48b74ea14b888d9c7e8c032d1cb6325f3292277abdf62483abd9d

    ingress:
      enabled: false

    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi

    diagramsnet:
      enabled: true
      image:
        registry: docker.io
        repository: yuzutech/kroki-diagramsnet
        # renovate: datasource=github-releases depName=yuzutech/kroki
        tag: 0.32.1@sha256:71e7082f736ec003fb33b5cd1c5c40af54c9bfb6351d50fbe73b56fe8f1bd5eb

    excalidraw:
      enabled: true
      image:
        registry: docker.io
        repository: yuzutech/kroki-excalidraw
        # renovate: datasource=github-releases depName=yuzutech/kroki
        tag: 0.32.1@sha256:214f13c1cd3c3f79a18a83631a900fedbed71b2f39d3a0c5630ac5fa5ad40046

    mermaid:
      enabled: true
      image:
        registry: docker.io
        repository: yuzutech/kroki-mermaid
        # renovate: datasource=github-releases depName=yuzutech/kroki
        tag: 0.32.1@sha256:ad6721646aabfb8b5f5005db2daa6e37189c25e18aab19a8ef8590b6171cd192
