apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kroki
spec:
  interval: 1h
  chart:
    spec:
      chart: kroki
      version: 5.6.0
      sourceRef:
        kind: HelmRepository
        name: cowboysysop
        namespace: flux-system

  values:
    image:
      registry: docker.io
      repository: yuzutech/kroki
      # renovate: datasource=github-releases depName=yuzutech/kroki
      tag: 0.30.1@sha256:4cfb9d48a1d9e18c346d505fd85c9ad16121d1691602b0e580db904b00c04320

    ingress:
      enabled: false

    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi

    bpmn:
      image:
        tag: 0.27.0
        digest: sha256:b86f1c08f71c62ac9e4c218e40bcc7f913f3b671d23b117ecead0eb939f62048

    diagramsnet:
      enabled: true
      image:
        registry: docker.io
        repository: yuzutech/kroki-diagramsnet
        # renovate: datasource=github-releases depName=yuzutech/kroki
        tag: 0.30.1@sha256:2130f32b4ad72a84be743456b65fa7e736fc1bb92db467e4be0c7ad23e259c74

    excalidraw:
      enabled: true
      image:
        registry: docker.io
        repository: yuzutech/kroki-excalidraw
        # renovate: datasource=github-releases depName=yuzutech/kroki
        tag: 0.30.1@sha256:091441d2fc45e8ec9ab3a65ac98fff0d73ae1d355652bebd3d2cc21ed8efd3f2

    mermaid:
      enabled: true
      image:
        registry: docker.io
        repository: yuzutech/kroki-mermaid
        # renovate: datasource=github-releases depName=yuzutech/kroki
        tag: 0.30.1@sha256:2216fa675936bbc47c984aecb867dd995561d6e8e1bc20ad3d87c473bb26ce6d
