apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stirling-pdf
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/stirling-tools/s-pdf
              tag: 2.14.1@sha256:986ae1d17bd41661351006526332a29a1ff7ca6799e69a51a8bb549c55941044
            env:
              TZ: Europe/Athens
              SECURITY_ENABLELOGIN: "false"
              DISABLE_ADDITIONAL_FEATURES: "true"
              SYSTEM_ENABLEANALYTICS: "false"
              ALLOW_GOOGLE_VISIBILITY: "false"
              SYSTEM_GOOGLEVISIBILITY: "false"
            probes:
              liveness:
                enabled: true
                type: HTTP
                path: /api/v1/info/status
              readiness:
                enabled: true
                type: HTTP
                path: /api/v1/info/status
              startup:
                enabled: true
                type: HTTP
                path: /api/v1/info/status
                spec:
                  failureThreshold: 90
                  periodSeconds: 5

    service:
      main:
        controller: main
        ports:
          http:
            port: 8080

    persistence:
      config:
        existingClaim: stirling-pdf-config
        globalMounts:
          - path: /configs
      logs:
        type: emptyDir
        globalMounts:
          - path: /logs
      customfiles:
        type: emptyDir
        globalMounts:
          - path: /customFiles
      pipeline:
        type: emptyDir
        globalMounts:
          - path: /pipeline
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
      tessdata:
        type: emptyDir
        globalMounts:
          - path: /usr/share/tessdata

    route:
      private:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Stirling PDF
          gethomepage.dev/description: PDF Viewer and Editor
          gethomepage.dev/group: Apps
          gethomepage.dev/icon: stirling-pdf.png
          gethomepage.dev/pod-selector: "app.kubernetes.io/name=stirling-pdf"
        parentRefs:
          - name: private-gateway
            namespace: envoy-gateway
            sectionName: https
        hostnames:
          - pdf.nahsi.dev
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - identifier: main
                port: http
                weight: 1
