apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - actual
  - arr
  - audiobookshelf
  - grimmory
  - homepage
  - immich
  - jellyfin
  - kroki
  - memos
  - miniflux
  - myspeed
  - stirling-pdf
  - supersync
  - vaultwarden
  - ai
  - downloads
  - navidrome
  - matrix
  - searxng
  - lemmy
