apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: grafana-mcp
spec:
  mcp:
    sessionRouting: Stateful
    targets:
      - name: grafana
        static:
          host: grafana-mcp.obs-stack.svc.cluster.local
          port: 8000
          path: /mcp
          protocol: StreamableHTTP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-mcp
spec:
  parentRefs:
    - name: agenticgateway-internal
      namespace: agenticgateway
      sectionName: https
  hostnames:
    - ai.nahsi.dev
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /mcp/grafana
        - path:
            type: PathPrefix
            value: /.well-known/oauth-protected-resource/mcp/grafana
        - path:
            type: PathPrefix
            value: /.well-known/oauth-authorization-server/mcp/grafana
      backendRefs:
        - group: agentgateway.dev
          kind: AgentgatewayBackend
          name: grafana-mcp
---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: grafana-mcp
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: grafana-mcp
  traffic:
    jwtAuthentication:
      mode: Strict
      providers:
        - issuer: https://auth.nahsi.dev/application/o/grafana-mcp/
          audiences:
            - https://ai.nahsi.dev/mcp/grafana
            - "9c9f8850dc579f51"
          jwks:
            remote:
              backendRef:
                kind: Service
                name: authentik-server
                namespace: authentik
                port: 80
              jwksPath: /application/o/grafana-mcp/jwks/
      mcp:
        provider: Okta
        clientId: "9c9f8850dc579f51"
        resourceMetadata:
          resource: https://ai.nahsi.dev/mcp/grafana
          scopesSupported:
            - openid
            - profile
            - email
          bearerMethodsSupported:
            - header
