apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-mcp
spec:
  interval: 1h
  chart:
    spec:
      chart: grafana-mcp
      version: 0.18.1
      sourceRef:
        kind: HelmRepository
        name: grafana-community
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: grafana-mcp
    command:
      - /app/mcp-grafana
      - --transport
      - streamable-http
      - --address
      - 0.0.0.0:8000
      - --enabled-tools
      - dashboard,search,datasource,navigation
    grafana:
      url: http://grafana-service.obs-stack:3000
      apiKeySecret:
        name: grafana-mcp-token
        key: token
