apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:kl36gmvttFCHslybf7XaYA==,iv:RljQ56T24y+KZnIkIs+VqT1QoOs55FejLT2XOkF5O7k=,tag:nFU2j1W1fy3bAcoWR62bmg==,type:str]
    client_secret: ENC[AES256_GCM,data:hPnhrjXh3Oi2ayG890xq+t/yhnO24kf3aoCh3Y8iO1l+HJZ980BIDKpl81OEqwil5N7ngzR9ypeeDtGMWD7qhBqtBgcrI7ar3BmOQnEtDi/ffDN6fkuXyhA0JsAXyDKyV1u8gOL4dtGJyAVyQKXtOJon8dDbUqSGIzoYaWmihok=,iv:gMZ5F4KnCxRBNzcOzaz+Gv3MLiu6ik9KSHT0l9kLBRw=,tag:BJOMswI1XnPr83oQa7NmPg==,type:str]
sops:
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmY0hvcFBLTWFhNDJpSSs0
            TTltU2RlL1M5MkEyME1jTmtreVRkRm5lQ0hNCkNLeWVrV0tpZElpUjc0MFVjR2RG
            dHF5aGswVk0zL1N5ZzZiVE5lcVZTTW8KLS0tIDJybWVvdkhXUExNeEI2cVdmN2hQ
            R3ljNGRnZUVpbS8vaWJFU05rbUtSbXMKRhBKDOrCZ73XgNKB2FHLceauSHI46kY4
            S8tPndoBn1YeHwn9kYy6f0yQ2psayFJ9JgWLgfggnmHsTHHTMl90Pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-12T14:24:02Z"
    mac: ENC[AES256_GCM,data:+yv+b3oLhiqmYEV43hlVzq1b9OUi17al1JLexo2KNEjbplsDb0E/2aY51SHp8cLwUjW2nC7+QxdbLIq7LJFuH4YEc7z/wjt1BqLN7HTanDBDc/PtpOuxF0PQItlYLqcgmEIXv6hKApVHbgTvhlZKtMIKmFP/Jf6h3Ya/RSIkZbQ=,iv:kODkYFqn5Rx5esAgGzf+kSnvjyNVmbfDumRXqjrsXYY=,tag:5a/yuL/mmsCvd1HyRdjqeg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
