apiVersion: v1
kind: Secret
metadata:
    name: hindsight-secret
stringData:
    HINDSIGHT_API_LLM_API_KEY: ENC[AES256_GCM,data:S8Z+voTApQVFm895GMxAt/DbM2uNtkOh6iQPSWYAoMqZr+Y2nT7pTr1LPO+4Tq7oU+qCb8TKDwQNC7fIKD+EMQ==,iv:crOpAvCCm6vkqhZgyK3nJ1gXzH0h4L9CceKUByIUvLo=,tag:ae/+hONjVUPRW9NitRNG5w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRW9ybUtXcElpREIrNnN4
            YXhFYjF0bTFZdXBoeGJYcEFSUGYyWUJRUDNFCklWMXNIYnZWelBkRHFlL0RZZzRT
            L2NuZzlUcmVodUVmOFd2OFJUVnBmdnMKLS0tIG1HTFFaVmpLcy9SN2thbi94OTJN
            VEhMQUIweVBUWjNweUxKakZweDNLcWcKNNF6lUZ2xtlAhhjv9gtDln9BARJUjY+T
            gmB7luk8PNPRlew2Mh07cuJrhrn4QkJ8vWNUnmUZIW8cXByQzcy6gA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T20:50:44Z"
    mac: ENC[AES256_GCM,data:DyqOX95RCwpTLlQRp+zqUk4mKZ6+E0GnjJMuM0ceDTqVLhP5vLcmS3rOkJABHUY30Gp265eEuCqVvXDwn+oy2DmxJ9y5gWehdNZCYmikDlqlBEd2ASU7ds02lAXLLJcSRu37e8VgCB3KocTo3xGLTCBEUxGPTl4/b20THYiHuTM=,iv:n7IeHqSRkR61hbpwD8sYsEyRa2ThWxk0gatqWegiSH4=,tag:6bCk9cis7clyYqPtb6qwZw==,type:str]
    version: 3.13.1
