apiVersion: v1
kind: Secret
metadata:
    name: hindsight-inference-auth
stringData:
    token: ENC[AES256_GCM,data:yk8cmsVZsfnFcJha8cGSAj0EJ+JlWQeAHI7LYtEQR9rQl2uoeRURq9YdNg7XvJHWJ6y5t0hBkQE/3cTuhsiJ1w==,iv:lydf1g6H9lnlV8nRnsfaPqcNe27eGn33yHve0CaMeDs=,tag:OeP6WiN62a2HDhyLWLwJfg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVnNNT3hSMlVRblVEelBK
            bEpXZzV6RGlweFFOenVEUDBTcVNBZ0NDMXlnCnJvYk5taXpJbG9FZmtyOSt5ZVhk
            bktuK1FWRlhGWWs0dWczK0JRZjExU2MKLS0tIE9qWDJOdnRqeXkybTFnckpaZzc5
            eFA3UWRnTURhdGJVVmpRY0c2cVRISXcKFOD1lRBFdeWkLKr0Uu0ksE83SBzxYFkV
            87y4B3/mevwPhKJHkEs8Q6szh12DrbWkZq+RZLD2rwUcHJFuNMxzSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T19:35:51Z"
    mac: ENC[AES256_GCM,data:cYzMdbHR77UmwgsfjjeCkB8hjxRTtL8eZA2WAr9nJ1eyALk/9wg+HZIiT6MyKB0CCZHdI9qDe+PIYOxdC7Xb26aeDE0v5zQDy3qhKY4+jn4AOCMS39PpS0S/n/zVYZWXurblAqj3VNketnn4GqxCC4TaS/06LVRJl6tR8tfoNMk=,iv:GEf/qp1VqbMYf254OTaVqAclkDeXXFK7VPlZC5JQDfc=,tag:SdDWJVHVe5MknIq+u4VhcQ==,type:str]
    version: 3.13.3
