apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-digarr
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4@sha256:6138f19539304b585c6cafd1af82ca407f184139459a8e06f0880df4556d3588
  storage:
    storageClass: ceph-rbd-retain
    size: 4Gi
