apiVersion: v1
kind: Secret
metadata:
    name: digarr-secret
stringData:
    DIGARR_INITIAL_USERNAME: ENC[AES256_GCM,data:5CeCi9Q=,iv:jsAm91JMpwb7h5KXD8Gb0D+iUfpxekk8Ty1kdnek9EM=,tag:4YCZxhun53yQ6s2qIX970w==,type:str]
    DIGARR_INITIAL_PASSWORD: ENC[AES256_GCM,data:Qbb7X055nGVo+GVYbfM=,iv:NDa1mhx+R1UaNQgc7N8cvY0IQqFavXZKV2sRssp2GBI=,tag:SqYSohavpuCh6bsmoYvKow==,type:str]
    DIGARR_ENCRYPTION_KEY: ENC[AES256_GCM,data:TUnHv7RdPTjnrM7n0/K3g6VC3FgV+vPkMfDI9iDxRlN081Us4s8IMQUK6UhJBAi4GB7rsLzJjCkCadDWVhYInQ==,iv:cpCenQARL/sG/qwp/eHiSlvTkm6sgdnstCZgUPObd0g=,tag:jf2CEyOiDetzwv/ggOFVjA==,type:str]
    AI_API_KEY: ENC[AES256_GCM,data:PCN+P8zgCvkloE5O2Z7NGgLmcnqcOcOZMSEJ1scWEXmdaa49VvUKY0/Qnj7JPQI3Nzy/anXbwywZ1NXnw3BsjRX95wE9CjvzMqagYrfTHC9xp0mUJhSRaoGWBM4Hcp15oQVZ1qF80YRSCR/fPpYSD1HkL37Xh5VXC/qQAO+b3HkCwlLiIkyXNWWkXgZ/2Rkh4/GAmyCKnla+Ro3bIgaOw7+IFWc=,iv:Yg8YNfvQ3jDnmtUBtkJI7oXLNiwc8muqvxSdM+0KgAc=,tag:5z1Kd8f9RqtiUd6gl1v0VA==,type:str]
    LIDARR_API_KEY: ENC[AES256_GCM,data:CY2Ajd4blTSvxTYzQH9LOb1hEvluAK1yiYPoLic88F8=,iv:vEMDAB5/pFcHZ7uMnaacPiAs04V4f1FYhPd4ZxAihLc=,tag:g1mWQgilBew88fkh7SkoJA==,type:str]
sops:
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMlVDVG9JYjBnTEVRdVJN
            ekhzV1JzM2NjVVhHcDUzajNxNzFvZ0hJN1JnCi9MS0pJNnMrc3FiOEo4aTNabGEw
            VEZuMEJRQ1JkYTZaYm0xRlVxYUhKbmsKLS0tIHZCNUxHWnNSNnZ1cWM2NTNXdVJp
            TkZ4R1BBcnJ5anJVK0swUERFcWw0dVkKQ9nAjnsVhDjNTdme2DYiOjKK4NIaT9yG
            DS2T5xnzIgRIcj00VPVAYNn16hOomtwMM5uvZru+g8ykpcLYqoBTcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T19:52:46Z"
    mac: ENC[AES256_GCM,data:2Ao3Ro64hv2FmrFcgXofb+HhzsnxcnYOnQysbIjpRa0uMHG1N3HVsqjSgaQC7Q3rxxZURHAB+CTHYoxz9JUKzD+A3LmKJXxhwycxA/JzKpXXLZ5eqd/+0Wsn0h0tzo5VnSqHqvZNqIXe4ftljetKnvGzcQ99UnF8WTVRwLkWOlw=,iv:YvtqQhufzhcpEtkgFzgwQXEj9byBu1T+e431tTLUiGk=,tag:RMRxPxtIUrVaxb2UePJFmA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
