apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.11.3"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 12h
  values:
    controller:
      kind: DaemonSet
      config:
        use-proxy-protocol: true
      publishService:
        enabled: true
      service:
        type: LoadBalancer
        annotations:
          load-balancer.hetzner.cloud/uses-proxyprotocol: "true"
        nodePorts:
          http: 30102
          https: 30103
        externalTrafficPolicy: Local

