apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: lfm2-5-2-6b
spec:
  ai:
    provider:
      openai:
        model: LiquidAI/LFM2.5-2.6B
      host: lfm2-5-2-6b.ai.svc.cluster.local
      port: 8080
