apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayParameters
metadata:
  name: agenticgateway-private
spec:
  rawConfig:
    config:
      adminAddr: 0.0.0.0:15000
      storage:
        mode: readOnly
  service:
    metadata:
      labels:
        cilium-bgp-private: "true"
    spec:
      type: LoadBalancer
      externalTrafficPolicy: Local
