apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayParameters
metadata:
  name: agenticgateway-private
spec:
  modelCatalog:
    sources:
      - configMap:
          name: llm-model-costs
          key: llm-model-costs.json
  service:
    metadata:
      labels:
        cilium-bgp-private: "true"
    spec:
      type: LoadBalancer
      externalTrafficPolicy: Local
