apiVersion: v1
kind: Secret
metadata:
    name: open-webui-fastcrw
    namespace: open-webui
type: Opaque
stringData:
    FIRECRAWL_API_KEY: ENC[AES256_GCM,data:Asl1sP1nyQplJ15JIGwhgbGyM+BrNzqCf0rdnfECR6Tb2E8stFCjy8GRG+WQxKm21LHzAgx3dCHRZYGI++kDww==,iv:pmTclqAqBz9tbk7n6vFQyvg0TlMbQzRy9Sz3TVv6vPY=,tag:oYzreGN49kRbLTk1M8viFw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOeUxBQ1ljZ3lkakVnUjFJ
            cjhjSTI3V1BGYVZoRTlCSTg1cEtoMjFLNldrCnJKWlp2Mmw4RXVvcVpXNFlZVFhH
            TnUrb3V3aEttSW5CQ2xoMXpUd0trVUEKLS0tIExVNjg3NlZCemlFRE1JdkVTeUlp
            Q1BqZks4ZlRKdGpkKzZqK1gvY21BWjAKORGX7YlBXZ48GMETut7IFzeOeKcinJ/5
            BTqg4uqfjNQ1wTnVwyPlI4YeiXgnrRphNGWh1Q7Jv3DnS2sbMMMf8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T09:12:31Z"
    mac: ENC[AES256_GCM,data:sAfugdbr2YOTB4QwRrmSBmEZ/D2YwHGnF2v2ymW+3lbnYgA0nyByTqIfkOvjSnaimtlJEo9tjHZCTSN1F0kL3v6+/RZAng1Ea8zEDmsDvTIDhINKif690B5kfNbV2gujq5kixcKOtshgwzKIm7DqYzPGjgoh5xklq/plUDwh9IE=,iv:8xaKZJjjfo1PuCjC36cowa5Wid4CHG3TeAWSBEK1+Y8=,tag:CIJbShNX9rLA3nzTCbI5ng==,type:str]
    version: 3.13.1
