apiVersion: v1
kind: Secret
metadata:
    name: open-webui-secret
    namespace: ai
stringData:
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:8/JCubwbWOpfAZoQYA7kFec0RNROaVBGP7uWkMQAGR9mS9YpmarMT/nEuHUE7jGQB5ne+erdhjp/mDu9vUXoeA==,iv:f13XYnTrV2kv/8jbHriVKdkcpUqGGCUKh1m41g9lJtw=,tag:2WzGN//K1DJQEy0/kbf1/w==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:Gpi6onUDqyKI0xH6VJAJEQ==,iv:pLu7W7jAOXTYX0TC3Et0a2olWdu7+a4uISm0zoABtHU=,tag:yo2Ak6KzdwnvpfTqj6+sTw==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:k1l26lgC6Z1QwCTzcDDMLDvlTq06q9CO7KL077aUxHk3a7MD3P1sMS8RXNmwIO3jWpDUh06Qj8dCY7n7xh+TkBB1CT1/NhWXS+mwET+qQG7+p/Xa0FJjw0Hkk2XRoj1BdeANHlXT0HETYYRGL5+IG25lMrQiB3wRj0oAFf3t1l8=,iv:mfjAunMeRPnANIYwnGBxkVn7MudZf2x707zaw1HWkcI=,tag:mbCm9My9zsxYey7jEbsGAg==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:XZ3SulxnzaY7SA==,iv:BsRHHJCLqc656K6QU2ryJfDQMFYlVDy7qrPjiL37rVY=,tag:52WYuOl1viXu+G4UxkYYPA==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:372hlZvMsstji2m10XR3OMKcA/s5JvAhEA0GlasWqtQ04Tuqt9Ma+3hc9hn4+LvoacuNRiYDWS8=,iv:go5mG9zwyMKnpXh4XAcHgslV18E8Z0pN76jRMp7JSEk=,tag:J/4p8UdEdwgxTfntDVzkBQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTGlkR0hHdnMzeFNZSnp0
            anNIZ2xzQno5VWhZTUpBd3FFS2Fab1RtR0Q0Cm1tSkxaLy9rZzFWZi9JZlh6NHFl
            U3NIQUhoaUtibVJHczFGVjIwZFZFcVEKLS0tIE5sQzdIbjlEc05kVkxVVnNJSWVT
            SVhYQjBsTW5VN1ppODZyWDE2bzdaNHMKgDipbJaE7aGfBbx1NZdAvsRj+i/SI8cu
            q7dYQVfJ0/kmpS+IwHHrHvLk/9nGmzYg7DCIqGJmYvoCt7stUDReQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T20:08:18Z"
    mac: ENC[AES256_GCM,data:hd9QUs0oNxUBY/0Vs+9cgtcQVTx3A3FwV9Q8D/ufuQtMl0zDPopT+QtMkrPI0Rt/3p6ws++8nKePhWmsNB4idVsXXifOsRimW0p6MYGoFk+IJVEkm/VPfTnMFu+2nVY5aCVH8tHfNULu35tRybHXzvMxo1EssCJF6oF/XmAnYIg=,iv:M8ocqfIfI9GY/ekMwTpaK7koQOPddtB3PwvPOQIrPFM=,tag:jrEqWef8mELk6ekKI3+0zQ==,type:str]
    version: 3.13.1
