apiVersion: v1
kind: Secret
metadata:
    name: open-webui-secret
    namespace: open-webui
type: Opaque
data:
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:tQZmG+1NC3E1j2/Y3Ct2YGFqEA6lCGu3,iv:j+zEOr3oBVcPOBKOl8X7aFtrrJMCM1j7+NP9YrbZxy0=,tag:/Rvslxe6MYmdUz659U5iKw==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:er4XKIu4AcE+XTHwB3rUkEiSo5/Fy2r51AuhGLBWFaTeYCClgdrJVTecO9pRzySoMUvWh04ogPLQcQeSecXMDHePWvkayTbkqe9puB1TY76xRn/VMcX8hehbW5IpTZ2PNWyKybJKDE5XWglrayvvIr4ksm8bFiob/fVPHIZRtT49GCIja40e0TBhNnwq4iuZ1dLUyaUulyf86biTjyN3sABlLNFW1RhfAKVrvg==,iv:peSUTAxcvAxf8FC56PFrFKA9RDTVnsXsZzmJjz3OF3I=,tag:sFGHG/RWuA5npMjOnVe6Eg==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:5sGAHTC0RMtrOTVcCSP60Q==,iv:f8OLmyrfd0TLCiR/xWlUczv+QQMm5eOIihiVA5XqA18=,tag:wcDng5oLjesz4VmV03meFQ==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:UPUvBRlNSHYLc4cFwj1mlHTdq/xq9b9UnSNRTNNXiK6SGd4qaMWxTOc8eaoutfr7HF2FsHrXGQJ8aqfeA1RCDMKQoE7fEpxjwRK+gw==,iv:mm9mukK7pkFyC10fDFRUqM1QwUYGJHIe/Uw/BdKb9Lo=,tag:LhHWa/iZFLzFveriLCV4Tg==,type:str]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:lQMmxb4ctXUJHP21zOqKrtEjJb0bIT4jMNryU+i1iQeukG3VSoEM5L+SjrOL/bG6KFu/NLJk1vcCZTZtzK17CuQF0jT5brbbvP+1mJ5FxaLkESVdZpNw6g==,iv:gk3GopwghjIySK0b8KpfLXFA/KMx/LJkkVucVY6yyjo=,tag:rKI9YFCScP2sR9nGdF3J/Q==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:G+8Tr4QXlCcTr6SKs7Cf10+O70Exk4ZBuRuslllOwx/BbVw3boZ6Kwb5dPa6hk5luesiodqRJ1rNmXFqRrwDGUfN3+9d8DTEJ7MmZ/Xt9rpxXaI76Tg4Gg==,iv:wdUtZXRtqrdRvLbhS4mze8assHRzcTG3pgwSm6Ycw1E=,tag:0PdfMlRo7FWD9fE6qflLAg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCV0huV3J0ZVN1ZmhxZktx
            UVFBRzFrckR1bEtiMFdiaWNVb2tGVjZzRkZ3ClRCTlhEZlVGb1E5dDUzT21wVTJn
            b2hPK0wwbksrQkFhTytjSkFFNE82ZWcKLS0tIGFvNWs4Z1BqM0swcmswd1IzZFRp
            dUZNcEdYb09vQlNXOVdhSmZKUDVGN28KBeUuR436nP1uMrHsUiU1fvW7SlIdgKAE
            NHDM5ZFzQduq8qT5p7mYCumMyW3LZlBKr0gYmiJDHsjVw+RqFRn10g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T05:20:26Z"
    mac: ENC[AES256_GCM,data:j5XvtMDGh+6sdEOH185TUVQDvqQip+dY2CHxx88KtzKlbmA0dubRIoLn771mxcQXL5jSyam2WNSbJwgqDqdHttEprytQWUpm/CqktgCLN5IHmLZHjL7ZCUMiX9EOmkEFMwDYgxWxCdVo3pZF2ENnKCFqjNQJvcK602IPUs6jMsU=,iv:sL66NaOzxS89p3STo49Nj4bokW4YvfLzUNv3EVSQbIM=,tag:k/KVNChMK9GOhwuoxVhquw==,type:str]
    version: 3.13.1
