apiVersion: v1
kind: Secret
metadata:
    name: sharetab-app
stringData:
    AUTH_SECRET: ENC[AES256_GCM,data:21GbqlpyBIsL7qjmmD/kQW8FIFf5tTA43teAtyWnMtrpdTcyJQK/pU+r+8o=,iv:m2E5iQqB9yWvLVuhszVUfYznMSlzOhcKtM4RSHzVpOA=,tag:nvvL1YJfqMIn4JvEvbgttw==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:9NrzAuC0YHGrr/2Qu1G67QKNeMoXvDn8kvQIZnxI0rEqpTN4oV2CF+0Pk3M=,iv:9fKc4RwAwu7cHinhHhi1A5Dii1JV69eojNq4qXeOkL0=,tag:z6lWPIsaHy8U4fvzTbb3Zw==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:9t6wKonxWh2UumYcd+is0A==,iv:0d9b6qVChFtndkn9pFmkXFX6T2UMZ6V6t5oEESA6W0Y=,tag:aqh12MwUmpFgRsMGOk2IPg==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:bVJAh+UpCOxulGEoZdwxXN8RW2iymMrsK9sHd48GPHuUby/1GCqJs5rmxN1uBYKj4AsZiYmbY5RrkqmRIA62eudbe2VuiWjhjTZR2Q8yWCo4CgnZaUif2y2EgAsPHbZYuaZ2tX/Zx9DFPox5tF9WwUjKpwGYCO55rBoltKRZTH8=,iv:wPNrCvCIhAr+ZHy6gJrQsPIsAqjEkL7J5RH9xhH0sfE=,tag:SPOQ0HTLrH+3hSkWrqbDFg==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:Irj6IAIU06bIB1WIfjo+Kv0IO5jhZZJp/BtKykK7qyGSwrlGoVm1CnlhaBdgKvfhU4lT,iv:ZK3NiUBFW/Wd0mfKpIC16F1q4Hck5308YewWBKt+d4M=,tag:ckFYaFfKlGbtw0+2HJO4ag==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:inpLNTNV9NMOl/hsGOUO,iv:HLo4qOJ+17e4+jZJQClw2Jw/58T+4WtvXjMMJeucxW8=,tag:QG9BplX2WsUl2yW7W3ikuA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VUdoTDRzRjhLZDBJZElG
            N0M3UGRuUHpTQlF5eTJwQzlVZmVNYWhvVG1FCmlXS2NKaEs3UXNibWhuWEd2dG9G
            b1dsUWltUFAxT2ZyT2I0aVhPMjU3dG8KLS0tIHU5YzZXMzBtOSs2Kzd3dnNvUHRF
            V0tkMVpCcXdyZmpjUlZIOVQ1UUtWbUUKPTDn1xy0Uh/LwW7RFntyT+wqo168PE9f
            aRWp9AGq1e/WI17VLato9Fmurw5yaBh0ac4pE7y8qpG0RgCt+/4Kxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T07:31:41Z"
    mac: ENC[AES256_GCM,data:8F+imQT40VL61uhsysHm3inZDS2GtTz7GZtFN/PPFxoYMV+GN0IzRFBgGCrqo/b8EDSbjD/jB5VeJz4Bsdv73RfteRCPVWBphObHklMH6D5fgf5LzWLgGjnTpuUYd5ci66PiqkGN/x2F9q4qKzbcU42I4NB2FyVcPL4oGlAFh5A=,iv:6kK3CrF5FovE5ly8mlACIKT3aKl3DWHKlcT8rsTVU40=,tag:fbKaDDlTWx80b3QafPRX5w==,type:str]
    version: 3.13.1
