apiVersion: v1
kind: Secret
metadata:
    name: actual-oidc
stringData:
    ACTUAL_OPENID_DISCOVERY_URL: ENC[AES256_GCM,data:JIFlg4XwFjsJOV/G93/hedldHCTJgxtgpzTydY8LJOaghbhRA7tQuqM1RNXeFyjw2LtECVfIDoDIng2FAcrHjVJqqy2OKHoCEH+9Iw==,iv:BZuJAyMtnV9aGKjZkyAt2RXwnbznxh+9Q+qTiChlBhE=,tag:eTAoF6+OEzmdAGOX2QjkxA==,type:str]
    ACTUAL_OPENID_CLIENT_ID: ENC[AES256_GCM,data:cbHDGU5e3KnzQUN0g6FLEw==,iv:gy382LEqJ7UQWcLIuG7elEGWonvuWd0nan3Qs1g4nBs=,tag:l86THytklcHUQD8juw15gQ==,type:str]
    ACTUAL_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:/bM/7bpUYg0IHzoWTo1bjjl6xF3l5IDki0ArXDob2U1PNxM0s3CUNfyqT4DtRRcErEKBrZ3382w08NTAJAk8nWhiv0lHjecMW1yU407N6X1yNn+tONAak9MrnDUBKV+KIBhLxmpk7ibiWiEBDBdAFaEsVi0k24gaK/JMXQYidRI=,iv:6afFf3KtgB3WIpdUjrEbaZq6JV7rKiSKsZUxdvsTY8M=,tag:LHHqVDqbVSe7DzC7pd1Z1g==,type:str]
    ACTUAL_OPENID_SERVER_HOSTNAME: ENC[AES256_GCM,data:lU81Q14Ab7MCGbM/oxfdoht/16gfkXOz,iv:4zQVIIalFOaX82D6dJCnjYn43PHovKEAkHdFtmeolRc=,tag:CtqH76aZCIk6QZrGlme1bQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTXVSaG8xRzJ0aVgvdC80
            bzVvTDM5Znk5dlZheC9oUTZKS0M2TEozc0F3CjdpcFc5dGY0Wm13VzlnMjZwNDFk
            TUZYeGViVU9JSlZYci9Ya3F0cE1KZjAKLS0tIGpsMlJXaFdWMVBFdy9WK2F0eW5z
            VDFJWVhRcVUyOGFUZmlGQ0ZFd25HNHMKy+dNSskkgvFjIngFbn75c0kT7ZEA2Aiy
            AiDwxdVpw2fc0G6e94HJmFFFcGbG/kVhwahS52/8P7OWKMb7HLku8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T17:25:27Z"
    mac: ENC[AES256_GCM,data:9tmWV2bFVTd9vM8Ub6p6DeR8PNCH8JFvfr0foXd1Qh9UgN9vsLjQpUPldElXV5jm5LXz1W9lbbJYPyVj5wVdV0fINPcmOBkG4vySOVRxsGuhsQgqJ9k+9fd5xVnE7v/Q/y1e8KpewfbnHsAbF4cFvuZl5et0G1ksFZlaKrqsdtw=,iv:hd0VYOd9cfsGAUmWNar7snUT7nrXru3oB1wfsK8lHr0=,tag:vTBYMokEZ7t3uaMD8roKhQ==,type:str]
    version: 3.13.1
