apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vm-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: victoria-metrics-operator
      version: 0.43.0
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    env:
    fullnameOverride: vm-operator
    operator:
      disable_prometheus_converter: true
    admissionWebhooks:
      enabled: true
      certManager:
        enabled: true
    serviceMonitor:
      enabled: true
