apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-ai-llm-lfm2-5-8b-a1b
  namespace: flux-system
spec:
  dependsOn:
    - name: app-ai-gateway
    - name: infra-intel-device-plugins-gpu
  path: ./flux/apps/ai/llm/catalog/lfm2-5-8b-a1b/app
  targetNamespace: ai
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 15m
