---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: soulsync-transfer
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-soulsync-transfer
  mountOptions:
    - nconnect=8
    - hard
    - noatime
  nfs:
    server: nfs.lan
    path: /mnt/storage/media/music
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soulsync-transfer
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-soulsync-transfer
  volumeName: soulsync-transfer
  resources:
    requests:
      storage: 1Gi
