---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: soulsync-staging
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-soulsync-staging
  mountOptions:
    - nconnect=8
    - hard
    - noatime
  nfs:
    server: nfs.lan
    path: /mnt/storage/downloads/soulsync
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soulsync-staging
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-soulsync-staging
  volumeName: soulsync-staging
  resources:
    requests:
      storage: 1Gi
