apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: audiobookshelf
  namespace: default
spec:
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      audiobookshelf:
        containers:
          audiobookshelf:
            image:
              repository: ghcr.io/advplyr/audiobookshelf
              tag: 2.16.2
            env:
              TZ: Europe/Athens
              PORT: &port 8080
              CONFIG_PATH: /config
              METADATA_PATH: /config/metadata
            resources:
              requests:
                cpu: 50m
                memory: 200Mi
              limits:
                memory: 600Mi
    service:
      audiobookshelf:
        controller: audiobookshelf
        ports:
          http:
            port: *port
    ingress:
      audiobookshelf:
        className: cilium
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: &host audio.nahsi.dev
            paths:
              - path: /
                service:
                  identifier: audiobookshelf
                  port: http
        tls:
          - hosts:
              - *host
            secretName: audiobookshelf-tls
    persistence:
      config:
        existingClaim: audiobookshelf-config
      media:
        existingClaim: audiobookshelf-datastore
        globalMounts:
          - path: /audiobooks
            subPath: Audiobooks
          - path: /podcasts
            subPath: Podcasts
