---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: agenticgateway-crds
  namespace: flux-system
spec:
  interval: 30m
  path: ./flux/apps/networking/agenticgateway/crds
  prune: true
  targetNamespace: networking
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  dependsOn:
    - name: gateway-api-crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: agenticgateway
  namespace: flux-system
spec:
  interval: 30m
  path: ./flux/apps/networking/agenticgateway/app
  prune: true
  targetNamespace: networking
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  dependsOn:
    - name: agenticgateway-crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: agenticgateway-gateway
  namespace: flux-system
spec:
  interval: 30m
  path: ./flux/apps/networking/agenticgateway/gateway
  prune: true
  targetNamespace: networking
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  dependsOn:
    - name: cert-manager
    - name: agenticgateway-crds
    - name: agenticgateway
