apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: docker.io/jellyfin/jellyfin
              tag: "10.11.9@sha256:bc9fa8e1462fffe3d8d4255fc62af478602641f4c0e5f4875fea8563d1189837"
            env:
              DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
              JELLYFIN_PublishedServerUrl: https://jellyfin.nahsi.dev
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 8096
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 8096
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              startup:
                enabled: false
            resources:
              requests:
                cpu: 100m
                gpu.intel.com/i915: 1
                memory: 512Mi
              limits:
                gpu.intel.com/i915: 1
                memory: 8Gi

    defaultPodOptions:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch

    service:
      main:
        controller: main
        ports:
          http:
            port: 8096

    persistence:
      config:
        existingClaim: jellyfin-config
        globalMounts:
          - path: /config

      video:
        type: nfs
        server: nfs.lan
        path: /mnt/storage/media/video
        globalMounts:
          - path: /data/video

      music:
        type: nfs
        server: nfs.lan
        path: /mnt/storage/media/music/library
        globalMounts:
          - path: /data/music

      tmpfs:
        type: emptyDir
        advancedMounts:
          main:
            main:
              - path: /cache
                subPath: cache
              - path: /transcode
                subPath: transcode

    route:
      main:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: "Media"
          gethomepage.dev/name: Jellyfin
          gethomepage.dev/icon: jellyfin.png
          gethomepage.dev/pod-selector: "app.kubernetes.io/name=jellyfin"
        parentRefs:
          - name: private-gateway
            namespace: envoy-gateway
            sectionName: https
          - name: public-gateway
            namespace: envoy-gateway
            sectionName: https
        hostnames:
          - jellyfin.nahsi.dev
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - identifier: main
                port: http
                weight: 1
