apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen3-tts-cache
  labels:
    app.kubernetes.io/name: qwen3-tts
    app.kubernetes.io/part-of: vllm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-delete
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen3-tts-voices
  labels:
    app.kubernetes.io/name: qwen3-tts
    app.kubernetes.io/part-of: vllm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-retain
  resources:
    requests:
      storage: 1Gi
