---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-browsertrix-deps
  namespace: flux-system
spec:
  path: ./flux/apps/browsertrix/deps
  targetNamespace: browsertrix
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 10m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-browsertrix
  namespace: flux-system
spec:
  dependsOn:
    - name: app-browsertrix-deps
    - name: infra-ceph-csi-rbd
    - name: infra-gateway-api-crds
  path: ./flux/apps/browsertrix/app
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 15m
