apiVersion: v1
kind: Secret
metadata:
    name: lightrag-secret
    namespace: lightrag
type: Opaque
stringData:
    AUTH_ACCOUNTS: ENC[AES256_GCM,data:D2rmm/Md1KH7VtAdVK6DWfImkr4TrwCdR3a4AAatWtAxx+HPjxsl4zj/QMm4Ydy9YCB19WUn4NOn9gRZPpkStDl7ZvIZqyzJPsjCSb0o,iv:f63BCPMB7GjttgiCN0RW/52r4/y4J2sdv2epHNAQxcE=,tag:eCXAo62UEil0WBsGYTqmig==,type:str]
    LIGHTRAG_API_KEY: ENC[AES256_GCM,data:+8QmyOaRlRORBCi9/50EMmK4LnPweT36lyLecG1rWXrjCjLjy9p6nV/IvVsOrTwr9FnNn6sPqsGhEJqaj98OlDyzRdEbEkDW,iv:uK1/qtCAWFeVnjcFYE2Yv2+dVYKhWpc/ZfsMyG6wqhA=,tag:s66AX4FG3XO0er22dOUdtQ==,type:str]
    TOKEN_SECRET: ENC[AES256_GCM,data:qtA98f+ui0G9MHa9yv2ZymtS35zvMqaQVy7SGfzfQznX6MQzAz32a4Q3pUQKD5A8pfZ4XKcfUa83/mNJO4mkkRtMWIyqLNMP,iv:vypNDRuId2AKx17/IiVmc2ymrM6TNdTnz8zwPwONQRQ=,tag:Bg9BzFuXrsF+G/4+RvIrmA==,type:str]
    LLM_BINDING_API_KEY: ENC[AES256_GCM,data:ud37wt1jpjkbN+4oVdwcnzfBu5PVglyDRQUqM1sedQwQAgI3W9sLHlRdnBmLvjxcILLn+YWotqzcl6QD671AoA==,iv:2BFeQ5h6c1vYoufRKs63WMy76MYToSVqhYWsjB3FGMo=,tag:no/iYyy4msOnB1mEwT2xaQ==,type:str]
    EMBEDDING_BINDING_API_KEY: ENC[AES256_GCM,data:/a0nsNbMLUkUsY/vPtR1AmW6GNnHicFklpUHKnyOqz5KhHjcjtUQg2hpSwZuSRwtnc4vx8srCm/Varcno+LUPg==,iv:FH18/hdemHS/ylhbJciLDByfy44b+vQCLHKQpgf/tlk=,tag:wIcw1q+doetIy0cu8AAzNA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVlNaTUlaWHNuWFd1UDZh
            eXdzbCtLTmVmNU5LQzg5WGJWQTNVbjZsUVVRCjV5cGExelJ1QmxDL3FCNVFiWjJB
            ZTZCOGlKZ0dxNWYvQXc3a0NGUTk1SG8KLS0tIDYwbCtSYmUyZEY0L1JNUDlVWWpU
            ZDQ3aVZ5bHlhLzFsWlpSUUtoaTJtRUUKvyGyYKCpuFdQg5313C0skB8PJjirf1T2
            DPxvDhLno8Tijm+bashHFgqtVjBJVlj4SJVHpM/akdoCcJVxG88fEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T19:36:17Z"
    mac: ENC[AES256_GCM,data:S7U2ksh2zs+ljCSQrru7+vdotDLgTqEKuJkAqkpaQXEgt4o/J3edfUxwCtHWXjjKSHy6td3aRsSOoaJZTwd7Z3TrwVSp6IvDrDwJIdWWOT4WvpyWpG++haHyhZZpjbBC9giuoIPy549EeICw1mAyjxwqQ8hE1QwWx6liYEwDTdY=,iv:gZW1RpDV0Z1cVOZIhenf3Iozu8HyvHNEGhARM0PoHLA=,tag:3KcRQI0LR4RO0w2m9rGKAw==,type:str]
    version: 3.13.1
