apiVersion: v1
kind: Secret
metadata:
    name: searxng-vars
stringData:
    MARGINALIA_API_KEY: ENC[AES256_GCM,data:XtvKy1+67EB3tcjPBlmtZugiNqjtZ6UsnXukFJ/2po8+X6U5tiqXOtqNzA==,iv:PYK6H8FyO2+HuZN3vFKBhj0JcbiQG1mh7oybyj3jGmk=,tag:700DAmEiqunVJV20Y0sKrw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxS3NVZit6R2ZQMjRYeW9x
            K0tZNElwSWxUMm1WZVF6cksxNFF6T3RDZlU4Cnk4U3BMbnc2M3BCcCtBNXFwQ1Z2
            M3lreFRvbmRjVmFkNkk2WjZTbGZvTXcKLS0tIFBsa2hPQTcxejE5My84UXVYTkxk
            MjBIaUUrbFk3MlRzVlV6eGhvWm9yb00KT0iRB02Hf76NsHuzmWJX39G7zyrYKUoL
            HWRyGHki8LHGPexcSvwFeDg5YDTurQA7pHYWhiOEXyRqJfpi68Fmkw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-01T16:14:46Z"
    mac: ENC[AES256_GCM,data:Pl2mV4cQGpy5h972fWWHfGlpRFqEZ/+5b5b80cUOgNqibmRLZxEs5MgofppNcVb9rZlEd50LuSL5ZXEEBmYpU156KHg01JqMxtWkKOxWamwf2rnLsCMGAq7EoaOOspNkI2L10D9KbZTFkz2Gp5vQKamF0p/EPPHi1Aw5ii4Wmns=,iv:kg+EsVthTbcjsEiE52bGrETaNnhLLFj29ULrLU2OG5I=,tag:XJwL8Ma54a9WzugQsg11fA==,type:str]
    version: 3.13.1
