apiVersion: v1
kind: Secret
metadata:
    name: navidrome-lastfm
stringData:
    ND_LASTFM_APIKEY: ENC[AES256_GCM,data:VQmcztF+xkpXgwj1OT42p5iy109FAOtzKEG3gRGfGXw=,iv:UPWybJ9eWmptY7MdGHiVOeP2TCKh66TGE2s3JaPIhNQ=,tag:I5io/O879Yp8AIYHu5ctzA==,type:str]
    ND_LASTFM_SECRET: ENC[AES256_GCM,data:TiLJ08h/zJyJ7x8yr4O6V73PfClP0X8b7EDt3FHf2lM=,iv:pmk9S4N0DtkaUp/rHZJSh8s5m6TqjYbqSmTDGAti3BA=,tag:b4WBTOoZUk8S7bSAlwSOUg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UHlOV0xEMnFlV1JwRHBt
            bXB5SVpvQjBKdVRUSmxUOUtqOXhkODYzNmpzCmNCOXcvS3lweFRWUWpMNEJDa3lq
            TVVEeVQwcHB0R1prNVIzYXhVeXV5UFkKLS0tIFNETmxoT2NZSUp3YXJGM0JvNXJG
            ZSszV21qbGFiSldFRjJncDNVWFM3dkEKpJfQ1Hs+Ye5LoKP2oBPIypQiT3lIfYIN
            3Ez9sv9xRE8z3/nOveqV9kS85f2bg0MUfiLvi7pozuDqLjBw+/X6yw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-07T11:40:04Z"
    mac: ENC[AES256_GCM,data:jFRLg0fA9oxpdHTtna4O0cAXCWi+yXycQMmxpgHxaeee1Uwta03FnCu0VIG7Pl8Q5xUZnI+gKBHCFdlHU/CeIqRGYa5F7qkYBvW8+rpVNb2crn3wYSL1ssd1wlKB6D1VqpCY5RSU5qxvG7l/djRnoHPgILzE8DVdLRxy5nLwewA=,iv:4yZbdrmwBtGpb50B8h+j3H4iy1z9XII5lwitET6rJE0=,tag:c6ixPyJQQ9aKkf66SOSkrw==,type:str]
    version: 3.13.1
