apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium
  - flux-operator
  - cert-manager
  - metrics-server
  - kubelet-csr-approver
  - ceph-csi-rbd
  - csi-driver-nfs
  - envoy-gateway
  - agenticgateway
  - kserve
  - cloudnative-pg
  - mariadb-operator
  - external-dns
  - node-feature-discovery
  - intel-device-plugins
  - nvidia-operator
  - vm-operator
  - grafana-operator
  - snapshot-controller
  - external-secrets
