apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yml
  - secret.yml
  - postgres.yml
  - backend.yml
  - frontend.yml
  - ingress.yml

commonLabels:
  app.kubernetes.io/name: clovalink
  app.kubernetes.io/part-of: clovalink
