apiVersion: v1
kind: PersistentVolume
metadata:
  name: clovalink-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Ti # doesn't matter
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-clovalink-data
  mountOptions: 
    - "nconnect=8"
    - "hard" 
    - "noatime"
  nfs:
    server: nfs.lan
    path: /mnt/storage/data/clovalink
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clovalink-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-clovalink-data
  volumeName: clovalink-data
  resources:
    requests:
      storage: 2Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clovalink-redis-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-delete
  resources:
    requests:
      storage: 1Gi
