apiVersion: v1
kind: Secret
metadata:
    name: clovalink-secret
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:7o6Zda1fsRyxuv5PDpnUwbO0qT+yQwUdDJJMxTFoaXxjp0KFpwV0ub8QQi0=,iv:qqJH0IdzhESmZJaMe/0FSePqc3gvoqX6RJIunZd10Q8=,tag:zMsgJrklRJcLwVk71Tpnog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TXYyTGptRUNEemNLbFpp
            MU1TaUhUT0szd201aHhCVm9XS2Z0Z1hEMXpzCjFDSjRHbTJDaG9ZSGE4VGpJUnUw
            c1VIN2VPSHBRNnNZWHlQQ0MrdUM4OTAKLS0tIHdNemVLRDhrK29vZVEyNXoxUEdC
            UFUvdmhXOEJ2VWNxNzNneGQrUVcySHcK7A5Vhf0Kf675iDSYUG4s/MTko83ACpK8
            OCy5848lGEFi56R3Ii4uCS7WqjfU+8ESgsNwz9JoyPbDZzHMADYDjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T19:08:37Z"
    mac: ENC[AES256_GCM,data:d+us3oX8YpePQmjbIV5SZo5r9XDYpeSHIfmcJNGR2u/EGlXztbywwCCodG6dHVZWFehLaT/aCQhMdd3Zn3HQcnU65dcEFnOUhbaf624RpsHrqEoIyP5SPCfGB03cjbzAD2d+JpSIZKU02NonTnUnYxXl5hqEn2L8+NWR443J5Ks=,iv:rohZAQzds7yBq63WUdqU5NiPwIYlPJ8YwpvaHOesA0Q=,tag:QPcnG+HVFVkFgU484KXo3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
