apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux/apps/kube-system/cert-manager/manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-issuers
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./flux/apps/kube-system/cert-manager/issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  dependsOn:
    - name: cert-manager
