apiVersion: v1
kind: Secret
metadata:
    name: mautrix-telegram-registration
stringData:
    registration.yaml: ENC[AES256_GCM,data:wjykECfO4nobdm5NoZ0ovlvjSg87/zV7gqNpkbZNxPgI82y11MXwS3OX7ZLeXk2tR0NTYh8E/YqT1aknsuakP3/3xFRntndGTesD/0X9RJgjYHInuogIj+Jv2NwgmTdWfnfQYRuDdulkdMaw+ssIGjUqmI+KEc56as7dc6iVN9YDZPjV9SRz8VgYuqRBA1+n32yapOlpZgIYCV1+crpm6oIidBqqFyz2W3Wu3DhG76puAnDw4TMEj53WP1df/oWSztn4I/T4EPhM4yj0c/yt5Lri6UJUFJ6SbbDkKtxCDMhqz01xtUDaTwnuIKWBnJLbdCL4GPH7BCeZdaxKA9DEWUuRa5z+wiYzhJQFztT6ZJzwursDvYdVH3L5P/on1f4g2nSoVeUrFDGTnjjz3c4GrGzChlUw23FFuOpaxQaYbgpA4oM/mt3UsqBu7EXTkf8sshMOraw5A/AgyWgdGeXz8EQ5fwv0rvm4rds+wJ+bZiZYNHX1qfocfmvSpfTLW69oyFiGzeKUs62TWEFIOz811LXMP1GvnThUd2NVRVUbsfN6VPIEvwMSq96HhxB6OAwLy+5P6K5SXdDGK1MIWCRqfnk6MlYxvrjxZJl52v95HyTj4djluEUnkhRt/Yxc8nwfrcEbtbeHHhoOLQcWT4bdXWTFvdZcTd3s/mBhxYDsPFeygA==,iv:7lodYJwI6VCwwRAjSef7qz62FQWv7JVODRBJJp+BrXU=,tag:7vwVViE2JUMRhxc0Qhy8Tw==,type:str]
    double-puppet-registration.yaml: ENC[AES256_GCM,data:7YuwF+1JXUzwIdT7oCFuB6lHeQgOjz5XtFC7AFSyRLMHq6xK01raCdrJB0M5uybMYSLpZVN3zMFHZaNLtsU2edPz8lKRTtxQ9Dbp8k+P5owqAaKNMIVJbPl28DGOYcvIth/CO49/6HbzHP2/+IsTY8McZYrwPuY52cfFVAVH0bTrXiy643GPG+CBvnpUJxf4h4Cc0ceAlZYwBtDFrnLV7y/rm3wSya0CdJRg8ws6tnbpC82yrXQqYYm+l5jMorpb1tfv4MZq/HKlejxTD1oKFrg5hb1h2dcrew0u59NF0WJTz2AjXXPy1zpG/aGKSi1ro2cOD/92mKlm1G7YlePD0vGp3pW+4TE8hmmR4bJMqNMKQtB9Yi6/JCkvlo52IKqB9K7Dpz2mtVREXIwsZFy468EhUHBSofTtuZSbP3Q=,iv:2vqyEa1x3lTj3GCxyyjEM78/7e0cGWu+yHVLaQDqE08=,tag:sRmW5gh5sPSQu0ItHHvQ3A==,type:str]
sops:
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcnFaZ0IwY0pJOFQ1U1Mz
            a09CbW1LVVpLV1BWRm5VdjR6eTBzK0h5LzBvCkYzWjVFWUhEaDRBYmE4K2duU1B4
            THk2Z3NRakRmU2o0bUlNRTZXSmFuQzQKLS0tIFlQTVpUVmtPZEZ2aWxmQndROUNM
            eDBkN3NvdXh6TWF3WDB5YVB6b2pLVUEKepfHaSeW0PJpCudCIye3RrIYhmxp2sYv
            APxIGdGMH8FExw+gwWn/i8SDi/7LNJ2I/l3XRfKAx0QF0OhCiNBuTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T20:40:35Z"
    mac: ENC[AES256_GCM,data:g0aoGF0ggSct0S9T87EulZNhyXv0qeU9HcyaVM903Zb3twoB7LxCTznGLnUURnqbYw8s0sxVfCEnlzeaf8X8zuUPzZyOYWxRWvmNYZUaqHe9BGHsOM+A0xBVvcgERipIuE/8AhhR07xH7QWeswQG4z1tTTuv83Qj7URKlTeG2zM=,iv:levo6WagClMvDCw2lCEFFmQR3HZba6LCCFQEkKTIAc4=,tag:Td2I7ofId+gb7VgXb7Hfsg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
