apiVersion: v1
kind: Secret
metadata:
    name: mautrix-telegram-secret
stringData:
    api_id: ENC[AES256_GCM,data:kFPyQP8TVzw=,iv:yx4HC166bnU1h3/r/9bsrC05dufJuogEiHBggpzAEhs=,tag:D51HDuE6qVQNxkJZuMFMyQ==,type:str]
    api_hash: ENC[AES256_GCM,data:Jlf9cJHsD9c2q2BT30h2A/WNJUUgzVql7Vq3l+DN93E=,iv:ZFo9S8K16a/tDNLuZDCN28wcaT3/c1+RMHNDAzYnGwc=,tag:fMM9Kx2tASwD8VvWzKRhww==,type:str]
    as_token: ENC[AES256_GCM,data:vnVamJZ7QfEdhkwpJ3wKgTnyMc05GiiUoG5COqDnBSAWNyV7+oKXwboQoKGKW8dpQLoUbJz5Q0SAV/eFxmLn7g==,iv:1YeDj3z4V6aLRZy/rbWb1luANTdwUt15hq7Js/fM1Eo=,tag:9eo3wxoWX+3Jzes0x7dreA==,type:str]
    hs_token: ENC[AES256_GCM,data:J3tjfwnVf7ZNquL2rZ/dFxK5LsE1CziYNPq/lbxn1GI+3iusuHQfVDLWl8xfpVnl+ZgU5bFGXjelBzrsZVPUiA==,iv:W62kFj50UifQ5sFaIgnSCZw+O00Vy4ztdOlOw7CdodY=,tag:sIyPu+c3mKlH0b+6WguPLA==,type:str]
    pickle_key: ENC[AES256_GCM,data:MS/YN1e81t2htyvhS+aa0r3C6DjVifYuZPIRA3xqqASzAo1zTOsEWonqIJYnMNXhhr8e9WnXAYhdhmmkLeicXQ==,iv:eSQbnQDasNYwMYGnSRTR3YJRVwYsdDbRGgDQdgVYv2c=,tag:qBBqw3MqIDFo5P7kASy18g==,type:str]
sops:
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bjloUjVkWjBSajF1aWJI
            RFN4T3VldlJRcG56NGNpbkR4bHlnNkNMaVdBCm85aDIyQTFoZWM3ZENneXhWaHl6
            K080V0FzMGRPUHlkekVRNHNBeXczNEUKLS0tIE9SSWdOMnNJMDNONnlOWEVXOWVZ
            ZjlxMUF5OW1NUXNDZGkrbXRDWXFyZ28KLN/af0a+VxWSwHDu2l6UjF4PKnFHGC10
            YXxf4d+5MXFRA0WhwKCBSVB60cuDxoCXC8SK7VnUvEoS2AjbrzHgeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T23:14:53Z"
    mac: ENC[AES256_GCM,data:Qr5E8IJiCM9Ywpu4dXlQsnq0rJUe8zM4jN8hIndE1cpd6WWK4DSl/955VxQEyNnEeXRaOW9O1ODLIO02lABObjVy95MYilRR1lsTJBQno+WvnuhihttQRYA2j5jb6Jbm51S8WmM4tFPsUcLSvbfuypEj1fMFFaKygEoboS+VR+w=,iv:rJZ7yw/PKemNpJnf9hOPQDiikn9r7QNTGOH1iALckjs=,tag:znmo5TDxTJE3xvO99xEMEg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
