apiVersion: v1
kind: Secret
metadata:
    name: mautrix-telegram-secret
stringData:
    api_id: ENC[AES256_GCM,data:23am94nbCqg=,iv:BYNvxGVv9a9sJSncn+Vc02H0y8jEPQbmHySR/s7BVLM=,tag:hNRmlE8vnSNO1wATT7gfkw==,type:str]
    api_hash: ENC[AES256_GCM,data:qLAR8wqE0umfHThAKk6ijupDFUkQJna1MLVxCb3/TPc=,iv:sGDgH0lMGvnaAQwasgMINNYasjkKJg+K54tYwOArrz4=,tag:huh+SekFDCy80jaSeTmwMg==,type:str]
    as_token: ENC[AES256_GCM,data:jB1iEuvYNtZ64mibwFMk6cwW6f+xCBCzCquoA/NcvQx2lZdhIILgOOj7WNRf2nm3I9sjHRyMOlwQg3+k/zRW2w==,iv:s0cxc46LaKofEG/NvGOne2S1ApkcApDYJzKmO5CAb7w=,tag:BCCIkXVvYgru7azqjcod3g==,type:str]
    hs_token: ENC[AES256_GCM,data:jVwDM0b0eWmOLTWGieaTdTYzsEpgYjrk9QYibjloTLCOmmdiegahkg+5pyUX8yAELlNYPDE97RlX0hSvTUoHOg==,iv:GuOUCjFyuRJQoscw6IEystrhYW503cYkLn7Xzi4GyE0=,tag:ilNE+iptZKl1glB825xxUg==,type:str]
    pickle_key: ENC[AES256_GCM,data:w1Wi8xUOuEOPydFMC1YzDJGu43DO+mDOJWY2dE0nOO5IWQqlSOraVasq6MeYY9VpjwoFFMF/aZKxDD8eDTW1Pw==,iv:+ZdQapAsun9H1oqkNP7PriMBbUrPOzGKAQkpYShtcvo=,tag:8sKQLmQSY7Z2R+5DCj/GUA==,type:str]
    DOUBLE_PUPPET_SECRET: ENC[AES256_GCM,data:Jbs5DrE2N+c+R5yu3VBUm2o65/88eHXoOMsVt5XoxOhol5RqFuC2xvvKOctwgHj+/K8YbyCCCRXtqm/Ij/eSIEP5C39H6hw7vg==,iv:0NOfDYKq+RMMSrgdLr5h2YkcU8Zcuu90wLgG+QnSR/8=,tag:gGCYUynDhvZ4FuuYrkUlbg==,type:str]
sops:
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTkZJZUtnbVlUT2xsc0VX
            MWdUTmgwVnFDZXBvcWpXbEVrSjZUV21sM25VCldKSnlhVDM4bHp5K0thYzY1SGhZ
            ZUdPNnRJbWVyekZKb0pUN0wrTWRvVGcKLS0tIDNmbmp0UXh0b0NNMWhlOE9sWkZG
            ZGhEUXlvOVBIa2FqZkdnbkNOa2xPclkKnd72Ikmaq+zy+lVvDP3LY6W7NF1Qw4iH
            qkviCz2Ks0LCBhFDG8bl8ArugFi+hUSdVox9C+EJz1WVbsaq6Kkhwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T20:40:35Z"
    mac: ENC[AES256_GCM,data:t+wn8L9pjRE6tICIPCS6UXqU8nQojzU5Ts2Bbj8/WCp9o7L/mj83jSY+ZbrMVYoa9fcCckwHN+CJkIkGREhmoj6xyOqoTK/ogeFKRJClR2bofscatd8TNdCnYHtS95dGmA/jdi066Xhe6DaTQ/dwpvaxA+0JQdB9Wd80TsTVeRo=,iv:a1GwJFOWYb9fzSeVGpU3Bzv/GCQ3gB+YaZAkxlIkOc4=,tag:cnYNyjyjmSCGirBgfWNlEg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
