apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dashboard.yml
configMapGenerator:
  - name: companion-dashboard
    files:
      - companion.json
generatorOptions:
  disableNameSuffixHash: true
