apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app stirling-pdf
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      app:
        containers:
          app:
            image:
              repository: ghcr.io/stirling-tools/s-pdf
              tag: 0.45.6@sha256:fc53d48a018cc36446a4b1373db633be51301b828755e312c386b7700cdf2318
              pullPolicy: IfNotPresent
            env:
              TZ: Europe/Athens
              SECURITY_ENABLELOGIN: "false"
            probes:
              liveness: &probe
                enabled: true
                type: HTTP
                path: /api/v1/info/status
              readiness: *probe
              startup:
                <<: *probe
                spec:
                  failureThreshold: 90
                  periodSeconds: 5
            securityContext:
              readOnlyRootFilesystem: true
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch

    persistence:
      config:
        enabled: true
        existingClaim: stirling-pdf-config
        globalMounts:
          - path: /configs
      logs:
        enabled: true
        type: emptyDir
      tmp:
        enabled: true
        type: emptyDir
      tessdata:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /usr/share/tessdata

    service:
      app:
        controller: app
        ports:
          http:
            port: 8080

    ingress:
      app:
        enabled: true
        className: "nginx-private"
        annotations:
          cert-manager.io/cluster-issuer: nahsi.dev
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Stirling PDF
          gethomepage.dev/description: PDF Viewer and Editor
          gethomepage.dev/group: Apps
          gethomepage.dev/icon: https://cdn-icons-png.flaticon.com/512/4208/4208479.png

        hosts:
          - host: &host pdf.nahsi.dev
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: sterling-pdf-tls
