apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stirling-pdf-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-retain
  resources:
    requests:
      storage: 5Gi
