apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: intel-xpumd
  labels:
    obs.nahsilabs/metrics: "true"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: xpumd
      app.kubernetes.io/instance: intel-xpumd
  endpoints:
    - port: http
      path: /metrics
      interval: 5s
      relabelConfigs:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: instance
          regex: (.*)
          replacement: ${1}.talos
