apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grimmory
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        initContainers:
          wait-db:
            image:
              repository: busybox
              tag: 1.38.0@sha256:b6762ddf4a50aabb5f4d21aa6f447d05d5633fb09f09c08b33f22356a2f98be0
            command: ['sh', '-c', 'until nc -z grimmory-mariadb.grimmory.svc.cluster.local 3306; do sleep 2; done']
        containers:
          main:
            image:
              repository: ghcr.io/grimmory-tools/grimmory
              tag: v3.2.0@sha256:a228db61f0898ab7268664093b2a17b08d80387ed7f1c39c1c7bc30fd7360022
            env:
              TZ: Europe/Athens
              USER_ID: "1000"
              GROUP_ID: "1000"
              SWAGGER_ENABLED: "false"
              ALLOWED_ORIGINS: https://books.nahsi.dev
              DATABASE_URL: jdbc:mariadb://grimmory-mariadb.grimmory.svc.cluster.local:3306/grimmory
              DATABASE_USERNAME: grimmory
              DATABASE_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: grimmory-mariadb-user
                    key: password

    service:
      main:
        controller: main
        ports:
          http:
            port: 6060

    persistence:
      books:
        existingClaim: grimmory-books
        globalMounts:
          - path: /books
      data:
        existingClaim: grimmory-data
        globalMounts:
          - path: /app/data

    route:
      main:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: "Media"
          gethomepage.dev/name: Grimmory
          gethomepage.dev/icon: booklore.png
          gethomepage.dev/pod-selector: "app.kubernetes.io/name=grimmory"
        parentRefs:
          - name: private-gateway
            namespace: envoy-gateway
            sectionName: https
          - name: public-gateway
            namespace: envoy-gateway
            sectionName: https
        hostnames:
          - books.nahsi.dev
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - identifier: main
                port: http
                weight: 1
