apiVersion: v1
kind: PersistentVolume
metadata:
  name: grimmory-books
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-grimmory-books
  mountOptions:
    - "nconnect=8"
    - "hard"
    - "noatime"
  nfs:
    server: nfs.lan
    path: /mnt/storage/media/books
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grimmory-books
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-grimmory-books
  volumeName: grimmory-books
  resources:
    requests:
      storage: 1Gi
