apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-lidarr
  namespace: flux-system
spec:
  path: ./flux/apps/arr/lidarr/app
  targetNamespace: arr
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
