apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: cilium
    namespace: flux-system
  values:
    operator:
      rollOutPods: true

    rollOutCiliumPods: true
    envoy.rollOutPods: true

    ipam:
      mode: kubernetes

    k8sServiceHost: localhost
    k8sServicePort: 7445

    kubeProxyReplacement: true

    enableIPv4BIGTCP: true

    bpf:
      masquerade: true

    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
          - PERFMON
          - BPF
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
          - PERFMON
          - BPF

    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup

    bgpControlPlane:
      enabled: true

    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
      metrics:
        enableOpenMetrics: true
        enabled:
          - dns
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - "httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction"
