apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dashboard.yml
configMapGenerator:
  - name: nvidia-gpu-dashboard
    files:
      - nvidia-gpu.json
generatorOptions:
  disableNameSuffixHash: true
