apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: qwen3-8-27b
  labels:
    obs.nahsilabs/metrics: "true"
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: qwen3-8-27b
      app.kubernetes.io/part-of: ninfer
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
