apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: comfyui
spec:
  interval: 1h
  timeout: 10m
  chart:
    spec:
      chart: app-template
      version: 5.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        strategy: Recreate
        replicas: 0
        containers:
          main:
            image:
              repository: ghcr.io/radiatingreverberations/comfyui-extensions
              tag: v0.39.0@sha256:51a03c0782e780a12372a3b9f4e2bae05c4e30fcdae8675a2251c7a93f927315
            args:
              - --multi-user
              - --disable-metadata
            probes:
              startup:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 8188
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 60
            resources:
              requests:
                cpu: "4"
                memory: 22Gi
                nvidia.com/gpu: "1"
              limits:
                cpu: "4"
                memory: 22Gi
                nvidia.com/gpu: "1"
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL

    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: pergamon

    service:
      main:
        controller: main
        ports:
          http:
            port: 8188

    route:
      main:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Productivity
          gethomepage.dev/name: ComfyUI
          gethomepage.dev/icon: comfyui.png
          gethomepage.dev/pod-selector: "app.kubernetes.io/name=comfyui"
        parentRefs:
          - name: private-gateway
            namespace: envoy-gateway
            sectionName: https
        hostnames:
          - comfyui.nahsi.dev
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - identifier: main
                port: http
                weight: 1

    persistence:
      data:
        existingClaim: comfyui-root
        globalMounts:
          - path: /comfyui/user
            subPath: user
          - path: /comfyui/custom_nodes
            subPath: custom_nodes
      models:
        existingClaim: comfyui-models
        globalMounts:
          - path: /comfyui/models
      images:
        type: emptyDir
        sizeLimit: 10Gi
        globalMounts:
          - path: /comfyui/output
            subPath: output
          - path: /comfyui/input
            subPath: input
          - path: /comfyui/temp
            subPath: temp
