---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-root
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-comfyui-models
spec:
  capacity:
    storage: 900Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /var/mnt/comfyui-models
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pergamon
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-models
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: local-comfyui-models
  resources:
    requests:
      storage: 900Gi
