apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: qwen3-6-27b-llm
spec:
  ai:
    provider:
      custom:
        backendRef:
          group: inference.networking.k8s.io
          kind: InferencePool
          name: qwen3-6-27b-inference-pool
          port: 8000
        formats:
          - type: Completions
            path: /v1/chat/completions
        model: Qwen/Qwen3.6-27B
