apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: qwen3-6-27b-auth
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: qwen3-6-27b-ai
  traffic:
    apiKeyAuthentication:
      mode: Strict
      secretRef:
        name: llm-apikeys
