apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: inferencepool-base
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: gateway-api-inference-extension
    namespace: flux-system
  values:
    inferencePool:
      modelServerType: vllm
      modelServers:
        matchLabels:
          app: MODEL_APP
    provider:
      name: none
    experimentalHttpRoute:
      enabled: false
