apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: cadvisor
spec:
  path: /metrics/cadvisor
  scheme: https
  bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  tlsConfig:
    caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecureSkipVerify: true
  honorLabels: true
  honorTimestamps: false
  interval: 30s
  scrapeTimeout: 5s
  selector: {}
  metricRelabelConfigs:
    - action: labeldrop
      regex: (uid)
    - action: labeldrop
      regex: (id|name)
  relabelConfigs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - sourceLabels: [__metrics_path__]
      targetLabel: metrics_path
    - replacement: kubelet
      targetLabel: job
