apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: kubelet
spec:
  scheme: https
  bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  tlsConfig:
    caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecureSkipVerify: true
  honorLabels: true
  honorTimestamps: false
  interval: 30s
  scrapeTimeout: 5s
  selector: {}
  metricRelabelConfigs:
    - action: labeldrop
      regex: (uid)
    - action: labeldrop
      regex: (id|name)
    - action: drop
      regex: (rest_client_request_duration_seconds_bucket|rest_client_request_duration_seconds_sum|rest_client_request_duration_seconds_count)
      sourceLabels: [__name__]
  relabelConfigs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - sourceLabels: [__metrics_path__]
      targetLabel: metrics_path
    - replacement: kubelet
      targetLabel: job
