apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zerank-2-cache
  labels:
    app.kubernetes.io/name: zerank-2
    app.kubernetes.io/part-of: llama-cpp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-delete
  resources:
    requests:
      storage: 10Gi
