apiVersion: v1
kind: Secret
metadata:
    name: open-notebook
stringData:
    OPEN_NOTEBOOK_ENCRYPTION_KEY: ENC[AES256_GCM,data:xIouRktitzd+5+FswBOygat78Sf7GOTm4COLLVSgeWt9tZSRU/rr+TTunFtwSEwgk31vRWNUXvGseg/DHm141w==,iv:D1jhEUOS6hWL/rX1IPB3lL94wt4peIsD4kwq3pKeuc0=,tag:RNiHAr8z6f0Iqg+MKRG72Q==,type:str]
    SURREAL_USER: ENC[AES256_GCM,data:61VwjA==,iv:pqNWY7cQcJSy+Yeqd33TrzvL3x1hT3nhbauePGPsQV0=,tag:3LhLrDW614X9dG8VLjbqqQ==,type:str]
    SURREAL_PASSWORD: ENC[AES256_GCM,data:QukxkhXRe5k0hrJw6yjadT4HoPjFEx8jyjPVx+NERIDtFdLN9E4XUjzI5lAo8ds3Mxd0v3JNm7DA/UXOo0ZT4A==,iv:D8x3ShOHcGuY5oTMuErRYFhil4UzTzp5ApFTAOj1B5s=,tag:2VORvCEMf2Tg8mt/OkIiqQ==,type:str]
    FIRECRAWL_API_KEY: ENC[AES256_GCM,data:E8u01Zl+VoymXVbP0OuTTeAytun7TrmxKZxWDspwp/U7xio=,iv:Un69L/3UBYKoE7t2/PQkFkecgBqH8WQsWoI7k8gFhwI=,tag:BpdZL9atNyiN9T9LF0xKfg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueG1YbzBXWjFCaEVnTXBp
            MDNRUDFIMTJGU2NwaUNIYWJacndOdUVkRkZZClB2clRmUkRzL0dPaUE3S050WmtG
            bGd1ZUg2T1pWQzZnNmd0cnhPbk1HLzAKLS0tIGVUS1V3REJOLzhuUWJNdU5QN1NM
            NGhiNmsvWlhqTkNhcUpKNzJ3T0doL2sKjg9q9hcs0pr1EGjEWA+mxmRSfACL09ir
            Uom6izgVgzfkMiu4KTQQndmt8D45gJsMn+Wg+mvHSWVE2ds2VH3Stg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T18:43:53Z"
    mac: ENC[AES256_GCM,data:fwrMP8JHCAboVVIwL7KnQviflfrLxHFMRNTLrDFetBFdJMZaHTDvhpP7nSzqxKkmGVkp8rWDn8g6sQdSP7P0gFXpgWgXV8JtW2e4z8UqJMr1rT8R3WYYj0Tk17LqWwIfj5h/pDFpBfkoBXe3UM/MKpnylyLf6lutogoxCiFdl40=,iv:OmH/ArWtEzt6UhB2Xf1NlULI2o2hUixoKphz6d3AANk=,tag:c6t7mZpoIiAbiR885imYnQ==,type:str]
    version: 3.13.1
