apiVersion: v1
kind: Secret
metadata:
    name: open-notebook
stringData:
    encryption-key: ENC[AES256_GCM,data:pjQ8Dd+ESeCZU9txe7njpsmsHI8u1eVpJlTucXuOnjIXRpk1iXt2/aZ5a/gdKn8Dj0xmmdArDbCDmMUsPBzwSA==,iv:ELZ/Emq9yXZxyUEASaLv+h6yqaL64jrRJ+DrGn7zWwc=,tag:AaCd9E6txSELj0MwtWFdAQ==,type:str]
    surreal-username: ENC[AES256_GCM,data:rqwVBA==,iv:dzLlqJQvu37Q0mgXNGBPneQrYTuZAqglPw6TxlbwaO4=,tag:WtwCCxl5fOykhEIoOpP1JQ==,type:str]
    surreal-password: ENC[AES256_GCM,data:MMFAXHt9yP0j6i3jk3F7AN9Bew9dcEX8pYu95eD6YoL8aAbm5zzENAe5D6X6r23O3Kl4jhqXVMKg5JR/irSmNw==,iv:FKEPm5gToruPJIFUZBoVvO+fGTLQbftBj7n5qXi8B3o=,tag:Oc0EomocZo+gmiDyjA7YjA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueG1YbzBXWjFCaEVnTXBp
            MDNRUDFIMTJGU2NwaUNIYWJacndOdUVkRkZZClB2clRmUkRzL0dPaUE3S050WmtG
            bGd1ZUg2T1pWQzZnNmd0cnhPbk1HLzAKLS0tIGVUS1V3REJOLzhuUWJNdU5QN1NM
            NGhiNmsvWlhqTkNhcUpKNzJ3T0doL2sKjg9q9hcs0pr1EGjEWA+mxmRSfACL09ir
            Uom6izgVgzfkMiu4KTQQndmt8D45gJsMn+Wg+mvHSWVE2ds2VH3Stg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T18:10:25Z"
    mac: ENC[AES256_GCM,data:fEzYr+VQBu6pmlLlmiJ++y3+xEBOkYniucHZlinB2Dvs7wHJctRPvvdJvIK3ACTnviBYEzp5zZW7t6zTcA3Tui80CA4OtpFniGuuG/KG4pZ1dAsA5uI481pYYaZnN+PIRVRr2/xUqCAagTEfuAGlNRh4JEmTdsFPDYN9ketKeZk=,iv:lDgeFpE37EiVieve+RUiaXgRiLh5s5u86cnBlb5amI8=,tag:BaCWtY9FsJh3s+OXAsi6nA==,type:str]
    version: 3.13.1
