apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-ai-llm
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-kserve-config
    - name: infra-agenticgateway-config
  path: ./flux/apps/ai/llm/models
  targetNamespace: ai
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 30m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-ai-llm-obs
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-prometheus-operator-crds
  path: ./flux/apps/ai/llm/obs
  targetNamespace: ai
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
