apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-qwen3-8-flash-next-models
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /var/mnt/models
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ephesus
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen3-8-flash-next-models
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: local-qwen3-8-flash-next-models
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-qwen3-8-flash-next-ngram
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /var/mnt/ngram
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ephesus
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen3-8-flash-next-ngram
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: local-qwen3-8-flash-next-ngram
  resources:
    requests:
      storage: 100Gi
