apiVersion: v1
kind: Secret
metadata:
    name: supersync-secret
type: Opaque
stringData:
    allowed_emails: ENC[AES256_GCM,data:6uPYi8URqnsUIAsDkNC6KFLE5u8mOg==,iv:OumeKFYKw/DAcTPz2ZIgb8rTK6yq9uk1eiQQ3GkCijQ=,tag:COWl1eMLgZavdKrX6Zla1A==,type:str]
    jwt: ENC[AES256_GCM,data:5XdQnKsJj0YOZQSc/Jndr0yAyKExHCOfg+eIO299mW113GLjxz8aTSujr64=,iv:WVb8nRwfmY21o6wh0cnERfbXkWhEfX1d5x5XASTxuCw=,tag:ATHaKWP+wfNhwo2NyHEOyQ==,type:str]
sops:
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIeVlVSGRKYldreENWekRi
            T0REREQzMzNaaktVcTFIUC9JOHF6ZFNIKzNnCnpyZXh6NmpCSW5HRlFkMlNMMVpv
            TFdxL1J2MXArSjYrRTFuNEMvb2pXRncKLS0tIEJRbWVHQ1lHbDBHeVBYY3hkTUlJ
            QnlieHpLdTVkblJoZkJnZjg5YnJzYnMKzgJIUShH7h7YwtlEyYyLCn1qer6LDTGt
            R0wauU+8PfZmEoqoDrC+k0A6cvqGVcwBgxxsu2A/OeoYM3Gt9vfGWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T07:13:30Z"
    mac: ENC[AES256_GCM,data:6CNzHYL1sin56tuD4TPWhjLw94xMUhUnQEx1gISpr/0dmlgQ0weCG+r0n7zvedOYn8Q8xDYkvOQZGgb8lfUzTqwqF0Ipha66xaOo7y4+Aq1L3nQRJCJL6bdzPOuXI3VUwDAepDN7I3w1DrnQy7g9FXkCJFRJw+QkOrGwgWTYrGM=,iv:XbwuObHdqK9SutZqX+J0+pUdAVFqPAV/jApNBr3jg+E=,tag:Y1Sjqk5UHWePLRxLkuC/QQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
