apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  path: ./flux/apps
  dependsOn:
    - name: cluster-infra-configs
  decryption:
    provider: sops
    secretRef:
      name: sops-age
