---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: public-pool
spec:
  blocks:
  - start: "37.98.199.179"
    stop: "37.98.199.182"
  serviceSelector:
    matchExpressions:
      - {key: "io.cilium/bgp-public", operator: NotIn, values: ['false']}
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: bgp-peering-policy
spec:
  virtualRouters:
    - localASN: 64513
      serviceSelector:
        matchExpressions:
          - {key: "io.cilium/bgp-announce", operator: NotIn, values: ['false']}
      neighbors:
        - peerAddress: "10.2.1.1/32"
          peerASN: 64512
          eBGPMultihopTTL: 10
          connectRetryTimeSeconds: 120
          holdTimeSeconds: 90
          keepAliveTimeSeconds: 30
          gracefulRestart:
            enabled: true
            restartTimeSeconds: 120
