---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-observability-server
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-infra-configs
  interval: 1h
  retryInterval: 1m
  prune: false
  path: ./flux/observability/server
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-observability-collect
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-infra-configs
  interval: 1h
  retryInterval: 1m
  prune: false
  path: ./flux/observability/collect
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
