apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: kubelet
  labels:
    obs.nahsilabs/metrics: "true"
spec:
  scheme: https
  honorLabels: true
  interval: 30s
  tlsConfig:
    insecureSkipVerify: true
  bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  relabelConfigs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: cadvisor
  labels:
    obs.nahsilabs/metrics: "true"
spec:
  scheme: https
  path: /metrics/cadvisor
  honorLabels: true
  honorTimestamps: false
  interval: 30s
  tlsConfig:
    insecureSkipVerify: true
  bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  relabelConfigs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
