apiVersion: v1
kind: Secret
metadata:
    name: slskd-gluetun
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:iyG3C6fHMcbYsvcJ/L0Y0Vv7DHqAk2F53AHU/lvPNaKjAi/fICyYn9cbg/Q=,iv:Gfh5puc8sSJvX3mjiynYBYC8G92UoWIXQnHIiiw3P/8=,tag:sqJ412ElS+0DeU0dAjksqA==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:gwYdAkxXunRvvdDw0/jj1mDxuLauv2uwOIO9snT3nOKWzqmGad9OlslzmOQ=,iv:EHwXlmJHjlWjSDG/j83o9/M2cap7NXmEDlWrbrAJ2aM=,tag:drrxsQ0YDGhNLwHx5zM9DQ==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:AvIjiKvw0RvsrMdzjNXdYbSm+0HdEAxf9iTc/JkDWuNNKEpbO49GtZRhp3Y=,iv:TUfVyWdlxvoA8MHS2BZGGeBx14PfQpzd4wzWfTFDf2g=,tag:PHVANEStL/d24DnO9ucChA==,type:str]
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:PWlP6W6lAd+ylvJ7hQ==,iv:a3ok564A3gMe9JubnGlQxr8JYuHVKTcTBhXOfaGccO0=,tag:siUAo7TqP38hjHY78qBmBw==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:dDkH0Uo=,iv:HFcgOZCz1nST3nlzzJVKGUehDK2p9wS93PXsVUsci/A=,tag:CvY4mFnkVpnhSQqqU78V1g==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:t6Ojprq5PiLRf016U9NJZg==,iv:yomZvuosz8i44s9z+4qCknO+K8ZftXnQDcLSPYwvBLg=,tag:/jqmvGpPbE9Ze4Hv/2XVdA==,type:str]
sops:
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQUFEV0JzdysyTzVqMmo1
            ZlFINnAxdEVaZEFxYlFrNW9TbENjdnBYMGlNClFEclNQeUhlYTRKeE1yZDkxOXVn
            cGw2aU0rbU1yTXZnSjhzR3JQZC9oVTQKLS0tIDdOKzdmSnJzOVJidVBobEQvZmEx
            dlZlUTZydFd2RzFVK1hLcnhMbW9odWMK5PBmj9+XTt3f4vwalB1j0vxWvy5Pmm/T
            E7M7Jt5HJ56p0V5hUgop1unWTgrYWzoMCNO/ibKdGMsx6nTlTIYZPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T09:34:07Z"
    mac: ENC[AES256_GCM,data:DU5QNtmrh7MIIz7UWLi3ZdeQbPpTTLrSWf4w2C6/h/q/CTwkmbvIzvwsiIiNpnD5krwfweoQBIu5wY/0U3qkgdjjk7cEBq8aQDDcI9kiubwP5iC3+s8bvV+6/bVW50+6Co7KxJMdfDz5p2EOBnRtvHXOfOQ8Nu9FYLVopCiAIDM=,iv:CtBHH60XO740jOQVTz//KnuAASOxDpoU1jou5FfKIgw=,tag:zwS0u3c6dnDhz9qk1BLsyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
