apiVersion: v1
kind: Secret
metadata:
    name: slskd-credentials
stringData:
    SLSKD_USERNAME: ENC[AES256_GCM,data:MLSew8w=,iv:7hSYIopf+6p6V6ZupCsBpEp5FcIaMOUggsryqsAvHjM=,tag:E0pjDhM9KYf2pUP/uuOmzg==,type:str]
    SLSKD_PASSWORD: ENC[AES256_GCM,data:iKXnwL449ZAaCNZuH6qUlPys,iv:8QBg59hy5izfpJ2QsDMVb9gqMLdqkXM7Mpo+lDxQeQA=,tag:pb59+BEq7ugoFzWPQQNcEw==,type:str]
sops:
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQVdUSnRZYSs2SlluL1hV
            cmJIZlNaOTNVcTc5TmI0V0F3UURBY1B1bVFVCk1tM3VBNm9vdXdtR0R1eFQ1T0Iz
            WFVsQTROOWo2SnlUWENmdjJHMU1rc28KLS0tIGM1eXlTNGlyWUNuYzRxZGl6S3li
            SVE1L2JhUFVVMlRydlFwRzRjakltY00KkMFeAYUZGC5DP38zkf6xGIue7KzwHRxu
            Zfi1VPiqNQ8bvdWntRMddeKMQYG5MZNYCsQ18tnyYxAHkhLiccjbXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T10:37:40Z"
    mac: ENC[AES256_GCM,data:FJlB6ehqAKHQlLNoeBq6BK18UDlMC8JBhJLlLW+y6VIqcdEchLQmneCFIJpNWALz0pMji8UQJsomfyspgIBFFJCmvzGKmcojVsAs0cxHHSzV3kX9ABnH6FNdLm7bCp38sDF8CXcvAbTyw6yFHHeH2cGcxcofa51STZkWG6agRrE=,iv:NGS6U48RvYAZW4GtbLt7OziWH0MEWHUhOPXWyrMjTds=,tag:sNxxunKSYGZIY0XmUkci8w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
