type: Opaque
apiVersion: v1
kind: Secret
metadata:
    name: slskd-credentials
stringData:
    SLSKD_USERNAME: ENC[AES256_GCM,data:/7OzUEo=,iv:RcgnbVHm1oNA8Pw3c7w/YeTDTVGDTSuIkiI0dnMFvq0=,tag:AVHoM5AE3KAfp74j6ve18A==,type:str]
    SLSKD_PASSWORD: ENC[AES256_GCM,data:HgW2duQYNCuifPUASHViV8l7,iv:6/rKOlgrqtlUZ4mDM6vzNuXhFExI55p2vf+CpLOgFTc=,tag:OAtk40JhNGSkJbXceg/a9g==,type:str]
    SLSKD_SLSK_USERNAME: ENC[AES256_GCM,data:hAeWNtU/cl9r1Wfc,iv:e7jMzO2h3CyFriW5viI5a+tgy/GyjRw94+SBfDD40pc=,tag:ugpEVOIdeUh2ScoftSe/GA==,type:str]
    SLSKD_SLSK_PASSWORD: ENC[AES256_GCM,data:eg5Fk3olYqVA3+5xpIY=,iv:EKt5Bt9CeHYL4woXlvJm/DBlGErwsJTllWV3SSl1c5Y=,tag:pmxSntEK1AEmq4SZBXmtlg==,type:str]
    SLSKD_API_KEY: ENC[AES256_GCM,data:G5tDxSaV2sx1pRM8zwlrGBFymynXhI45PIuigVFC9dOZHVSxxnAX77Ee9aV8uDeT2VqwbEXJuA8gTs7UTjY1Yw==,iv:1DlomVUZeVzmffleRPv252kqq2SiAQbqPG8ze1LAWw0=,tag:wxGPa6wzidvxZm533C/ZlA==,type:str]
sops:
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZ29yNmpPRy91ZDd3VnVo
            NFVmR3kxUGRjRjRjclhid3N2OHYrM1liZWkwCjRwQ0lRdkR0QmgvU3VEYS9nQWc1
            dy9qam43eVdabVQrUzJMSHRybUpRU3cKLS0tIDVsbXJVbWxJVFpzMWVyY3M2ckNX
            MkVreEt2Ym1ER0hCS2U5dVRQSjBzR1EKl3I27vHzURRQdSyQP7dXfWCAH2BcD7JW
            Jpj4PEoPeqc7kF7EYNAxlTVcLFlvU+XPU21dj7vMPdRRvsMXfQF4kA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T10:56:08Z"
    mac: ENC[AES256_GCM,data:uc7akEkF2CpOxIXiodR1lNb0g3UVnFg1wumr6+lYO39JMERQLfeRfBsx/W/Up7gEnDIT1+C9XzFAgs2wuVcN5a4RWd3q06x41T9L4ZNvVWt1KRtATfXGe57nY8zvMSqKDdngRJmPDU0G8pu8kEdhebPKNPUd0B2krwtZSDyNHl4=,iv:q6sXnQYIWY0fWIAZL5I7nbbUGG0vTFS3MQFqTRkDPUY=,tag:2EVFLlXkbphHgVD+H9cLGA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
