apiVersion: v1
kind: Secret
metadata:
    name: slskd-credentials
stringData:
    SLSKD_USERNAME: ENC[AES256_GCM,data:fa7ycWg=,iv:ZweskEP4aS+N3baJmLJl4vfrbpzJT9ufKv+SWUVyJuk=,tag:EOSUBTCJZfcSTPkpoK0L8g==,type:str]
    SLSKD_PASSWORD: ENC[AES256_GCM,data:sNnJkrFSrkpLte/F13iQ4eeu,iv:DAGf4O2KE3kf8o6TpoFHTA6FzEAY5cTS55fEvmaZcHs=,tag:EI0GHMCFIscFer7sv1Y6Bg==,type:str]
    SLSKD_SLSK_USERNAME: ENC[AES256_GCM,data:q27T5J+yRbnO/OQlMfgP+Vo=,iv:V2nYt8cQKj3Q8A8bxFzFVwxhHFIZw/wzvC3VumuyBJ4=,tag:RZRkXwa1SN/LlZyIMyVq8Q==,type:str]
    SLSKD_SLSK_PASSWORD: ENC[AES256_GCM,data:l/HjFAcWQ6pfHUyEEgw=,iv:CY0kmUOuS/fjdhWIxBwh/y8BPlYueCJkXvLF2Fw7KEI=,tag:8y3rAgm3S90ewqjOn2uQpw==,type:str]
sops:
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZklEWkJDZGhrUmNzcXp3
            dVdCanM3VXdSRmJabng1aW9lRjR3OWFPL0NnCjRvQ0d1VUJMVEM0cGwycUJSZlNk
            bFBTRkV3NFBuaUNXZlpsdE4zOTM3ZHcKLS0tIDRmZ2hSVmhLVzUrTXV5RSswN0p2
            aXRkbzhxRVhodjVQNlpMSGpBSzZpTHMKLs+t2O8gjuvP95yrHI1Mz7qw7gRSb1b+
            9eNIIXLMClczDmjea/b5k9mpFVhCfM+c72S57jX/0n7N1Qx1FFD3qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T10:40:57Z"
    mac: ENC[AES256_GCM,data:8ffYqlnAUJARyizlFjHXrnvUX4Xur21bR4Yw2dv3MCYdij7i9Kogf8OMu/v9auS7JYl3PsB02fEPu7MbPr1CRpttxxGQxfYa0Zvx8OoLysPZRWQbudSzpxkmTbE7IKWHiYTdb0sl4PeM2vDpG9WigdTo/Tu/bZVfkwiM6PcBuJY=,iv:il7ptRtTCoVS2mVrXprMLaElxmkgT6dWltAbmgLI360=,tag:y594UmECEQf+5yTgHiQZ2g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
