apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-adguard
spec:
  interval: 1h
  chart:
    spec:
      chart: external-dns
      version: 1.21.1
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  values:
    domainFilters: ["nahsi.dev"]
    sources:
      - gateway-httproute
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/muhlba91/external-dns-provider-adguard
          tag: v11.1.3@sha256:d00e350712c328ab97ba442ce4ac881688cb19c286d1bc0fa51e75608e580053
          pullPolicy: IfNotPresent
        env:
          - name: ADGUARD_URL
            value: https://adguard.nahsi.dev
          - name: &name ADGUARD_USER
            valueFrom:
              secretKeyRef:
                name: &secret external-dns-adguard-secret
                key: *name
          - name: &name ADGUARD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: *secret
                key: *name
          - name: SERVER_HOST
            value: 0.0.0.0
        securityContext:
          readOnlyRootFilesystem: true
    interval: 1h
    triggerLoopOnEvent: true
    policy: sync
    registry: noop
    extraArgs:
      - --webhook-provider-url=http://localhost:8888
      - --target-net-filter=192.168.78.0/24
    serviceMonitor:
      enabled: true
      additionalLabels:
        scrape: "true"
