apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-testapp
  namespace: testapp
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18
  primaryUpdateStrategy: unsupervised
  storage:
    size: 5Gi
    storageClass: ceph-rbd-delete
