apiVersion: v1
data:
    token: ENC[AES256_GCM,data:hnDVS9PZJs0wNCXHpy3BHGwApzuRnlN5/CoNbHiInBHnTNIXIo/cq+3acFsTFiQbCxRWjxPZfxk=,iv:ZY9AppKBYGLBzD87X66Ebjnygs/jw3OY/ucfQVrY9wQ=,tag:YyLTc1GY5sz+tae9rp9Gkg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cloudflare-api-token
    namespace: kube-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dWpsdXBCUjRTa1F1T2Yz
            Lzk3K2tKY3k0L1JLaU14UHJHdkxXaktiTFZRCldiUVducklzZ3EzUm1ld1gwckFt
            OUlhTVJma2FJSnVTckEwajBFSGt3TU0KLS0tIDlZamx4Wk05MDg3MVFDdHhwM3pN
            V2UyWDdOZmpJNzlpL2VlQVBoZDB2L3cKr7F6k/apooG5Sc0P0gwqTMUCbb3au7Jt
            vbtM3rvmL3PK6/Wxz6QRsgZ3ednMJp7lt1ozyRoj01mhrfcJyKyMpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-08T14:59:28Z"
    mac: ENC[AES256_GCM,data:czzihOJjxwpPzE5HCe2BZRNf4FnBaLmvZ6r5IS1fNWSD4NS0funcu5YMqK2ZdSpncJp30s8JVJ+/9xuzmiuK/q2CSRvgMX2PtZAyvwAk4GjfG2C6hlvnknNDjDXpexRXDQpw2OX/gAaf8QnXki20IxHcv7TEHibItT3dzkeX/D4=,iv:AiiJVD3XNfRkIsWLFGo8ZsAt56XJU6PEqAkj23eafJI=,tag:uluWDbasicrgunqS2D45Pg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
