apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dashboard.yml
configMapGenerator:
  - name: myspeed-dashboard
    files:
      - myspeed.json
generatorOptions:
  disableNameSuffixHash: true
