apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-exporter
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: prometheus-node-exporter
    namespace: flux-system
  values:
    fullnameOverride: node-exporter

    image:
      registry: quay.io
      repository: prometheus/node-exporter

      extraArgs:
        - --no-collector.wifi
        - --no-collector.hwmon
        - --collector.filesystem.ignored-mount-points=^/(run|etc|dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+|run)($|/)
        - --collector.netclass.ignored-devices=^(veth.*)$

    prometheus:
      monitor:
        enabled: true
        jobLabel: app.kubernetes.io/instance
        additionalLabels:
          scrape: "true"

        relabelings:
          - action: replace
            regex: (.*)
            replacement: $1
            sourceLabels:
              - __meta_kubernetes_pod_node_name
            targetLabel: kubernetes_node
          - action: replace
            regex: (.*)
            replacement: $1
            sourceLabels:
              - __meta_kubernetes_pod_node_name
            targetLabel: nodename
          - action: replace
            regex: (.*)
            replacement: $1.talos
            sourceLabels:
              - kubernetes_node
            targetLabel: instance

    resources:
      requests:
        cpu: 23m
        memory: 64M
      limits:
        memory: 64M

    hostNetwork: false
