apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-gluetun
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:CFQTsyaHECPhqgIphU0ANYO4hHKoq6bsZH75+6L4xhswB7RQLyzc2hV7g58=,iv:5rqkitmgpgNa0+dux6Gl3YahcngEywncWmPTyWU16KU=,tag:zVtmESwG7EEEuKBYm/FIGg==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:WIlKlXPQ8WNcdAo/Nk8TdQueMBmliHc5Ng1gLcrxirapAEFXMXgy56ABoFw=,iv:sKhBzqG1jXcS+AMXqM//PkL4hVMfJFqy1eY3wcau9HQ=,tag:DPwGf747Q8/uw4lRVfEdZQ==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:drk2HmRqHKEDKEnMeHB3QW444qz74Qg5uqnhqwTshrZF/E36wbSWkgj9pg==,iv:YIFKN9ctLHuIf30eMkp3Mom9oaUBaltLMqMIhr2UjmQ=,tag:F5iO24DIdBuhaE+5PYKTcQ==,type:str]
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:ahuiElbMlapIMZiqXw==,iv:QIs6rPgmH7/h4XZBZwwhZ0oIwlRC6W5JlcS8Am/NvH4=,tag:lNcLnvUXj9iX0HY+p9eNvg==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:/aTRiVM=,iv:513Wu+z7m2kAi/zYYjHa89hrrsyScST+/c9luZkGrn4=,tag:lq6FdtU9uvHc43FWjy1CaA==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:lqefFaZjEoP9Sls8bnNwcQ==,iv:LfKUY39sOOTsZTT5Syscsximl17yxDFtLV17VRMLPR8=,tag:3sU9pgnAiTU/MYqxP2Z4IQ==,type:str]
sops:
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UURCWEx3MWQzR0ZzSk14
            SVlrSnk3YUQ2NDU2SmZzeGxNU24yS2RjbVRVCi91ZCtNcjhxaHF2N0R1Tnl3clFQ
            TmF4VGdORnFZV1lSWEd1MHR1OVBpRjgKLS0tIDNvenpvWnhMenRtS0M3c3k3ZXBZ
            VHJXRjN6MEVYcHA3S1YyeHkwaCtsbzAKo2jzxyVM4B3rIiBKXJ8OZdbs7s0SIUQ8
            eLqh7NmPe4M93JsSgW3ukucy57Dhz4EhIESJdaCSgaupzWAKi+Oomw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T16:38:04Z"
    mac: ENC[AES256_GCM,data:BEwcwBvlxbVhtHnQbEmT4H32eW2yZDt3jzLBA0i058heVP6W4Jrpcx2rB+WzB8+ycHK5t6EPhG/In5FM8LYXWnMuTUAxb7gglWtVwOHuypW9LhWVcWj0uXgmXSG1bCl3dTNApo32XDngOkov2P8XKQ6aP6+LntN6K9vx4ux8STY=,iv:nusgtZmtD3uHNlGj6JDRnMOGAYSywBeyqvhOvXLFxyI=,tag:qjhHcJAbIaLgZEFhPWSaiw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
