apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-gluetun
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:hf8hVOy6xbYOfxp5wcjhkwdY3x4m1RtitdF/LXSH4OAmKGK8TWPJWF0raVU=,iv:sKdazF1IzmvfqSmeJ5C88mTTAY2rwA4h2Pdxr638wHU=,tag:GTRdeRvn+qd0mFLT8LYmDQ==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:HCT+I/PF8XhbetnGcwPkFQmjijv7qJAwYnFm7NMcG1+6eIwy0S4M4R7azFM=,iv:QFkTXXZ+s+2Er3kbOPB+FUD0fCZ4vyp2Q2pfQwGcNA0=,tag:B9YXeOhMYeaCE53wSlABHg==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:FjQnwubrwZwkqUpg8yT/JzBhXLsk00qbmZeU9XndriuFga9EPV8MmNq/duo=,iv:ZCSvKaeMO6VdkogYCfDNXvrSpFaq9yKaoqNPX0bW7M0=,tag:PPoepOU7ZKZKuEakkSHa1g==,type:str]
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:5gf5VsgsSzyG3E3OIQ==,iv:dHbgEI16eKVwqQmHzZjsMXzAw67EgvibK9TAQMFJCU8=,tag:nRsyeP1aI2Ofj8wOMTytxg==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:eGhsChs=,iv:f5SZACdQfAYGdUnyh8ZaQs1sBSBEp/uDF0zIXM3a+nI=,tag:SDdd29vveChOQ59lsFQ/Bw==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:VyTaCAw09phrg/OGJiiY9Q==,iv:ToigDOSzTh8DIU5SZYheh6JuOfw7u11syCwh/LPBv5U=,tag:MXWt47b9lg/ZDqSM49puaw==,type:str]
sops:
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHc2I3RU1wTFE0UzZ6MWdL
            WWdRUWVtRUw4dCtzekM1N09sT2Q5cTBoZjM4CllYQkhRd3c0ZHEwUVFFV21HYkpV
            VHpjZ2R0TDNoMXEvWDR0c0p6L1FzNkEKLS0tIFFheWVZYTJ0NFJ1NGlWWHFER3VQ
            RERjbmh0a3QyOGJWRC9IWjc5RGJoME0KpQvjkXn2F4t+pJ7MuN6LlJu/tWm4y7UD
            S03kkz6Px1GNA9FX8A0Wr4YabqQEp2IYBHPQ1uRwktGcSfSi/n7oYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T16:52:38Z"
    mac: ENC[AES256_GCM,data:XFkFbhF1fcGZeaxvJiS/f0sLQzDOP64exG+IXLwil7U2SiImV0nkGyeh6Qyqrhvi7y0w8Zu8L9epQdXnhPOLQaOk8DBKho3GdCxzLWD92HU7WGuRvXjvwPQDLuzkgMGtP1NWSAQbojGXQkZtbGvP1rn8bgWXWXb04LIum+ZDeTE=,iv:IqCbRnOc1saq/SvPrwDwYKH7E8CkiG2zX2ca7phZ7es=,tag:FtpQNSs3c6llxjiJXo7ObA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
