apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-gluetun
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:5rKTKDB4bmSBBoPVnvyNBDhKdrFu4MnarO8VLZgRMiftWbuyxvZMp+Ji9eE=,iv:c72EmQBGpo+4zm+qEvKbWAwF6M0QGnzOjWjm2fZriM8=,tag:9qIXOf0Q/9ek0XJkFsvVhw==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:Oj+BTIaHpdPFdZmrKjydl+NPb+rSh7hg13U1zvFMSB0O2OrgpMVJ16WSRfs=,iv:1FKtNrMaA39p8KldNcaALKQI3KoKr/MCYAkxJUo8TjE=,tag:GgOVliGoDCE91a9cGmKT/w==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:BovBWLGdCzMkcnG2OzpQvfgtRDlG+B03bmvy9Eh7PcMVCJhGX3D5dVIB6Q==,iv:XuAbvrO46vzi9Q1RIyf4kFM7Vn+j7MzT4FqMiEJ/MoQ=,tag:7Qe1h7XQ/6hOPypnXG8s3g==,type:str]
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:tNCbNV4xJLQNgTn5RA==,iv:RMh4lMM+6DWQ95kVWI5Z9PXV/PhkHSA6wm1thX95W+Q=,tag:/R1EnxQuuMBOgbBSG7SkSQ==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:ccCF7LY=,iv:jqLIHgjQlyVgDA3U2WiCokeB3Gzs6ksIZ9UL5UZe3A8=,tag:zzmCplc1SQIDs+c/kFX9Uw==,type:int]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:3+9FY0OB1KY/45p9KRhDeg==,iv:Km5n6zGVpC7i46cWOp8nfsXUz07FQUPzW1QjvPcQEBI=,tag:oW5G1+t1JpKpZmp1JJV83Q==,type:str]
sops:
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSnR5RFlOTlBkRGlQVTd3
            c3h1eWlScVRvcjF5U3R3VVVXeTUwSEhSdVI0CkVvQmFHVWlOVk5WeitnUjNFejNm
            UjZUb240S1lwendaNXgxdTJiSUpmL1EKLS0tIGY0djlOTTRNdDRBZ1Nha0hmZnRw
            YlFTZFNKZ0xlTHZmdVBwMUZ6NWJKWDAKuu7TgN8oqu8h6sI6B0mIvVnwX+OOJCj3
            gxZcrLnpuc/m5xh/sfIdGXEuzTPGOop/aJRMnM2kt7tx6QB8CH7YRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T16:15:35Z"
    mac: ENC[AES256_GCM,data:3pgEE3wuJ8uKt9rDpELLq+ylky/CszeRJoTq8TpOQ30uiGmUhefNQFwMI4xYTLsUVZ3u4BuduY0J9iFD3VppyeF8VI6xevYTD8vXD6uoHAR5V5+TA0q/JUDElmeFHBW3g9CiPcDUGtbs+Z/koG1BzNbV83RjWfr9Im08GZmg5IQ=,iv:44rl2k4XkE7KgnlIs97Db8UASpocChO96FjRwlJmm4g=,tag:lrK666j17lMnPHGlR+RwOA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
