apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-prowlarr
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  bootstrap:
    initdb:
      database: prowlarr_main
      owner: prowlarr
  storage:
    storageClass: ceph-rbd-retain
    size: 4Gi
