apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/home-operations/prowlarr
      tag: 1.33.1.4997

    env:
      TZ: "Europe/Athens"
      COMPlus_EnableDiagnostics: "0"
      PROWLARR__APP__INSTANCENAME: Prowlarr
      PROWLARR__SERVER__PORT: &port 9696
      PROWLARR__LOG__DBENABLED: "False"
      PROWLARR__LOG__LEVEL: info
      PROWLARR__APP__THEME: dark
      PROWLARR__UPDATE__BRANCH: develop
      PROWLARR__POSTGRES__HOST:
        valueFrom:
          secretKeyRef:
            name: pg-prowlarr-app
            key: host
      PROWLARR__POSTGRES__USER:
        valueFrom:
          secretKeyRef:
            name: pg-prowlarr-app
            key: user
      PROWLARR__POSTGRES__PASSWORD:
        valueFrom:
          secretKeyRef:
            name: pg-prowlarr-app
            key: password
      PROWLARR__POSTGRES__MAINDB: prowlarr_main

    service:
      main:
        ports:
          http:
            port: *port

    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /ping
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false

    ingress:
      main:
        enabled: true
        ingressClassName: nginx-private
        annotations:
          cert-manager.io/cluster-issuer: nahsi.dev
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: "Arr"
          gethomepage.dev/name: Prowlarr
          gethomepage.dev/icon: prowlarr.png
        hosts:
          - host: &host prowlarr.nahsi.dev
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: prowlarr-tls

    podSecurityContext:
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534
      fsGroupChangePolicy: OnRootMismatch

    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config

    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi
