- name: Proxmox post install
  hosts: qotom
  user: root
  gather_facts: true
  vars:
    ntp_timezone: Europe/Athens
    ntp_servers:
      - 10.2.1.1
    ntp_config_file: /etc/ntpsec/ntp.conf
    ntp_manage_config: true

  roles:
    - geerlingguy.ntp
    - node-exporter

  tasks:
    - name: Ensure necessary packages are installed
      apt:
        name:
          - "ca-certificates"
          - "btop"
          - "vim"
          - "sysbench"
        state: present

    - name: Add ssh keys
      authorized_key:
        user: "root"
        key: "https://github.com/nahsi.keys"

    - name: Setup network
      copy:
        dest: /etc/network/interfaces
        content: "{{ proxmox_network }}"
      notify: restart network

    - name: Set kernel cmd
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='  
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="{{ proxmox_grub_cmdline }}"'
        backup: false
      notify: refresh boot
      when: proxmox_grub_cmdline is defined

    - name: Set modules
      copy:
        content: "{{ proxmox_modules }}"
        dest: "/etc/modules-load.d/ansible.conf"
      notify: refresh boot
      when: proxmox_modules is defined

    - name: Set modules options
      copy:
        content: "{{ proxmox_modules_options }}"
        dest: "/etc/modprobe.d/ansible.conf"
      notify: refresh boot
      when: proxmox_modules_options is defined

  handlers:
    - name: refresh boot
      command: update-grub && proxmox-boot-tool refresh

    - name: restart network
      ansible.builtin.systemd:
        name: networking
        state: restarted
