apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: agenticgateway
  namespace: flux-system
spec:
  interval: 2h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://cr.agentgateway.dev/charts/agentgateway
  ref:
    tag: v2.2.1
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: agenticgateway-crds
  namespace: flux-system
spec:
  interval: 2h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://cr.agentgateway.dev/charts/agentgateway-crds
  ref:
    tag: v2.2.1
