apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium.yml
  - flux-operator.yml
  - grafana-operator.yml
  - envoy-gateway.yml
  - prometheus.yml
  - agenticgateway.yml
  - kserve-llmisvc.yml
