apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium.yml
  - flux-operator.yml
  - grafana.yml
  - envoy-gateway.yml
  - prometheus.yml
  - agenticgateway.yml
  - gateway-api-inference-extension.yml
