---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: alertmanager
  namespace: flux-system
spec:
  interval: 2h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/prometheus-community/charts/alertmanager
  ref:
    tag: 1.39.2
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: blackbox-exporter
  namespace: flux-system
spec:
  interval: 2h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/prometheus-community/charts/prometheus-blackbox-exporter
  ref:
    tag: 11.12.0
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-state-metrics
  namespace: flux-system
spec:
  interval: 2h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/prometheus-community/charts/kube-state-metrics
  ref:
    tag: 7.5.1
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus-node-exporter
  namespace: flux-system
spec:
  interval: 2h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/prometheus-community/charts/prometheus-node-exporter
  ref:
    tag: 4.55.0
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus-operator-crds
  namespace: flux-system
spec:
  interval: 2h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/prometheus-community/charts/prometheus-operator-crds
  ref:
    tag: 29.0.0
