apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-vaultwarden
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  primaryUpdateStrategy: unsupervised
  storage:
    size: 2Gi
    storageClass: ceph-rbd
