apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
spec:
  interval: 1h
  chart:
    spec:
      chart: vaultwarden
      version: "0.31.x"
      sourceRef:
        kind: HelmRepository
        name: vaultwarden
        namespace: flux-system
      interval: 1h
  values:
    resourceType: Deployment
    domain: "https://secrets.nahsi.dev"
    signupsAllowed: false
    signupsVerify: false
    ingress:
      enabled: true
      class: "nginx"
      hostname: "secrets.nahsi.dev"
      tlsSecret: "vaultwarden-tls"
      nginxIngressAnnotations: true
      additionalAnnotations:
        cert-manager.io/cluster-issuer: nahsi.dev
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: Vaultwarden
        gethomepage.dev/icon: vaultwarden.png
    adminToken:
      existingSecret: vaultwarden-secret
      existingSecretKey: token
    storage:
      data:
        name: vaultwarden-data
        class: ceph-rbd
        accessMode: ReadWriteOnce
        size: 1Gi
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
    database:
      type: postgresql
      existingSecret: pg-vaultwarden-app
      existingSecretKey: uri
