apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: ms-marco-minilm-auth
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: ms-marco-minilm-ai
  traffic:
    apiKeyAuthentication:
      mode: Strict
      secretRef:
        name: llm-apikeys
