apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-vikunja
spec:
  instances: 1
  imageName: paradedb/paradedb:18-v0.22.2
  postgresUID: 999
  postgresGID: 999
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
    storageClass: ceph-rbd-retain
  bootstrap:
    initdb:
      database: vikunja
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS pg_search;
        - CREATE EXTENSION IF NOT EXISTS pg_ivm;
        - CREATE EXTENSION IF NOT EXISTS vector;
        - CREATE EXTENSION IF NOT EXISTS postgis;
        - CREATE EXTENSION IF NOT EXISTS postgis_topology;
        - CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;
        - CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder;
        - CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
        - ALTER DATABASE "vikunja" SET search_path TO public,paradedb;
      postInitTemplateSQL:
        - CREATE EXTENSION IF NOT EXISTS pg_search;
        - CREATE EXTENSION IF NOT EXISTS pg_ivm;
        - CREATE EXTENSION IF NOT EXISTS vector;
        - CREATE EXTENSION IF NOT EXISTS postgis;
        - CREATE EXTENSION IF NOT EXISTS postgis_topology;
        - CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;
        - CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder;
        - CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
        - ALTER DATABASE template1 SET search_path TO public,paradedb;
