apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secret
type: Opaque
data:
    jwt: ENC[AES256_GCM,data:2Lz9dOFTCd5/xjJFXAhkXMM09xdr9+Tu7YruE77GEFfJTAj/6exo0qcOyUQ=,iv:B2vnHmSR6sy+DEyAFMZQ9SyycItNDdDgc0UiYRTdyLM=,tag:iH0HMg7bVWeVbuEovAuqXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscGMreW1iL1pObDBGS2FW
            a25WdXR3cmZydHljS0RlWnNWRFo4WHhvVzJNCmROc2ZUbm5FMU8xdVkxSTU4czZV
            RDl5MkFTSUM3ZkljeWZCUFFXWDFlZUkKLS0tIDJsMUIwc0VaWFZrblpDRVdMUmlH
            cThkdHNPYzhZRWVEWkR3R3V0NW1oWFkKNpiKw7thBerHEC1Dix9m0RwMb7izGyQ4
            MU6Gq/T2XMSq5sQfwBO1EXXtDgT8iqjPizfL3JBr99s7q8o+CuDPJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T13:56:39Z"
    mac: ENC[AES256_GCM,data:QP668Q80n+yK27DjKrH8rnegKNl0/QkVWL1IuTJL2zBNxvbaPJIap4bRNjN90SxaxnOcw6wYRIUkXHAvmlLMVrKq3OrvyqSUYiHcjxybifQFeIcB75/PeSkGNqWu5VU+iADx9zV4ceLzap+UcIYKFWat8flWaX3ACeZnNcwgVO8=,iv:WlSXWeimikRPB28JAxYIPrDhXc2VLvzyqI/eqcIuDeQ=,tag:pBzVBWxE1dO856SUIloYqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
