apiVersion: v1
data:
    jwt: ENC[AES256_GCM,data:I2yo+rDxrpvClwSpgh/rOe28mXn01r/DVxDb7roURnvLwz6FwET/LaMEE6tBr6Bj072rSiX9CnViIKqv,iv:EEGNWuDKU4TEr/9hIGCpXVfC6mDSfR7R0vXyZtyMMVI=,tag:b8DDdmvM8zOT5ELnuKJyFg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: vikunja-secret
    namespace: general
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZnpDUzRiRG5rTmhXcXdy
            Vzd0L3ZWa0hjNFN1TldHdXRHTkJoOVQ2R3owCnVaenRqNkhPVkVLZlczc1pkNG9h
            RlcwQW5CblVGVmsvNy9OM01oR0tUcTQKLS0tIE1uQ3lDTW82YlhTc3BjWUt0Y2pB
            eXhMa21MUFJoUzhTbjhwb0pkdHlycTgK/BPQKrwsbT3f8RXVP2u8R2HbI2c2Ysqf
            mQNTNue+NmK++CDKi6E/xaDsxdD2YodLMfKum1Gf5k5lrcj8B5oq9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T14:47:21Z"
    mac: ENC[AES256_GCM,data:bEwi6McModiLBoCDMFc9ne6lThmPvKN+jgyXbkxnUamRr5uBy4FDvlpvkq3sO9+7sEj6FReUCjfxEsgOrxCK066V84+NF/xidok6cxIuf+VvLpFSnd4urw/+f0h43Uys4SRniGeT2pR04Rj5+FqUHwVenMJNuekTdCxt4CXTju4=,iv:PMmBvbnN4oJvAyhTX3staCMAst1ky7EHSfPmmTnTUac=,tag:coD9lKRQwBe2CJJ8DAXdUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
