apiVersion: v1
kind: Secret
metadata:
    name: llm-apikeys
    namespace: ai
stringData:
    nahsi: ENC[AES256_GCM,data:W7xnOG/fLMYv938jPHirdXzOUuKVmcM77ebHOvWcsBR0IJBfAag6/EYwhTHZdj7cts9kYX+gZsTnL3vldXixk+/LFrEmEfP8n2lkJ160F+CfR0x/D4jOK4YnwxJeU7K0jSqPeZpoorvlUEKuUbWkyaMRTFhJy70HvpGS,iv:fLEpjSFRp2LJSV6qPVxdq6A+EloxQOyOEqI2+fof4hQ=,tag:rOe1pv+hUbipEm95KtUYfw==,type:str]
    hindsight: ENC[AES256_GCM,data:uB6I7RIg0anepiwsmt4Ud1440dryyIknKxWw64SEw8jJqZwQTEKUOQaQVxjR/kRFCsfOJUumGcW+98fFALzUsCVAedqZOTyG4CRTMPl74RR2ISOeMXdNkQXAnFMBFHj0JMN5Mk8WYWjG5dJ+EhkJj41QOwN6VcUgMA==,iv:lNtPWteeOyVH5P+Dxh7x3R4LO8wwl0lB0mXJlacMYq0=,tag:nO/S6d16wE+C6RzeZqhF0Q==,type:str]
    digarr: ENC[AES256_GCM,data:GW9fFlBq+YBO1k2RwP1G2KdDMvkI8AK/0YhQ9JodLQaqmXjEYK+aL7BVVgdPi9s0GG6ItrGqC823jkHSBy3oOOIHiNyOP2i7d5N37kaz7YoSSHHORRjVulaASbCxzqGBUiVsfNWO11DBgDR2oP5IikR/M8Fu/Q==,iv:sG+be1LDYKxHI99qQx4SJeDmCQ8u7dnSD8L7DsV7GOI=,tag:MnGMVEN9ripVs8HUkQzi9Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WkNQWkR1RGlvZkFyaTR1
            K3JuazAySTRXS1NzS0JKRU13N2lGbU4vV2hzCmw3YmFyWUdCQ25FTFFZS291WEhy
            RmRYQkdIZEhKY1Y4ek8vYmJuMUw5UFkKLS0tIDZjZXlPUkdTS0VodlBkUVY2WEJ3
            ZVJwdjgyaXBTMEZNTnp2RTlYT0g4TTgKitaNqUtStqYOCvsBMwmXUB5RPS6FYDDy
            XAszTdw1kkKmdW4YuOEJq8DsBhFaN1JbxCu+AJY7hb4BAcF3tUPQBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-07T06:11:40Z"
    mac: ENC[AES256_GCM,data:QykwNbvSS3KlXJfoLUMDGmWEekCoVRtx8mshZc6YGHvwTNYw00SZFs6k1B0ifrlRSseEEjxAG6VyoUIfTab3iR5a0bqP0UgzpVbcQszuq7PjD45Ye3H+0T5229x4sDaVGPvgLScXKnB1bl8qTXrm59nSZr3ktNyaTmfKAaMIfdI=,iv:Eqc0nvzXf7F3WcNiu6PhgrA1m9EBlCGlTfLujIlo6l0=,tag:1J0kET4eU4XVJd4aR6Y1Ww==,type:str]
    version: 3.13.1
