apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: llm-model-routing
  namespace: agenticgateway
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: agenticgateway-internal
  traffic:
    phase: PreRouting
    transformation:
      conditional:
        - condition: request.path.startsWith("/v1/chat/completions")
          policy:
            request:
              set:
                - name: X-Gateway-Base-Model-Name
                  value: string(json(request.body).model)
