apiVersion: v1
kind: Secret
metadata:
    name: actual-mcp
stringData:
    ACTUAL_PASSWORD: ENC[AES256_GCM,data:5pFAhO+0zbGRWj4f/dRlqw==,iv:gQVqFXHcAeTaZnStFZmPmiaG3p6N0/pTmzhy3OCg8C4=,tag:8CLUy6ahuSycrWj1zOl/vA==,type:str]
    ACTUAL_BUDGET_SYNC_ID: ENC[AES256_GCM,data:QCK3ojKtZNePNnKC1i4ey4acxJJ2v7+d1VjUAbgdVRlc5aB7,iv:ZiE2uBGr/jMOcoKSys0E0vgO+AIDLv/xEqAtB7kb/5c=,tag:oaM/5Ktia31deppZm06Tlw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TDhXYmJKSXkzdm85RU80
            eCt1bnloUkRZTklqeHZCK3dKbmJwd3NpMFRFCldsb2xhU1JDYllHeEZDeHB0M3Vk
            eExuR2h5bDIzSDZ2YU5QTnNqbjhyTkkKLS0tIGh5ODNPWXBQWFlrTmREdFNRRGN6
            Q2Z6bzRDZGY4ckp5bE1Fa3k1SVNhVjgKiSN4rkY30pBkdTz74QpNMJ4T3mG5A865
            b2PEm7KEEsXnhPMS2VQQSEw8rcSKTgm6BF8KI6a6RZZHaN2D8OBiiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T17:28:22Z"
    mac: ENC[AES256_GCM,data:08kp/W/4/PS0KbIi/C3vuw5/B8RR6aFq6cYqXuV8GgZe3ZC3nn4TMWkCJQKTuVkMYVIHjTmb2oRIR0CC32DDJFSHBLY6hMdPkdH27b4DsZze0GOr0Dapi4Dqsej5/EG6DzTGk2AOhiRDf0MrYKCDWaMQzMo7CiG8P9KArjZHdmY=,iv:CsixeP+OrkigyxuVjaKWK3pJ7oW6uQjzgzWQ0E8QaWY=,tag:n5PEyhb326pnSvxWjQj3HA==,type:str]
    version: 3.13.1
