apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-flux-operator
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  prune: true
  wait: true
  targetNamespace: flux-system
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  path: ./flux/infrastructure/controllers/flux-operator/app
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-flux-operator-mcp
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  prune: true
  wait: true
  targetNamespace: flux-system
  dependsOn:
    - name: infra-flux-operator
    - name: infra-gateway-api-crds
    - name: infra-agenticgateway
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  path: ./flux/infrastructure/controllers/flux-operator/mcp
