apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dashboard.yml
configMapGenerator:
  - name: intel-igpu-dashboard
    files:
      - intel-igpu.json
generatorOptions:
  disableNameSuffixHash: true
