apiVersion: v1
kind: Secret
metadata:
    name: miniflux-secret
stringData:
    ADMIN_USERNAME: ENC[AES256_GCM,data:EtXgfwA=,iv:Ig4aUY+znb0aJ8XQUPVMo7mSjhROCutnBmco5l43Wg4=,tag:Y0O3OigWfqw342JjEaGe3Q==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:MBwdPADmAx2bJI46E48=,iv:oCIyPIBmjStkW9QlWFI5j2MyPNxQ+e46Baszdh4idUs=,tag:vUU8pW8//edn8e93qgDyGA==,type:str]
sops:
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YzhvV3NFRGx2TDBKMXhV
            YTNvNXZLMHFDMzdRK3hnSGEvZ3RrYloxZ1RzCjhXakhXR202Z21iK1RBcWxzRlZo
            VmRkOUorRFhScjA2TlNqVnEwQUpCZEkKLS0tIHM1TkJjbStOZUoxejF1Zkd4anU4
            V0RtZm5yNWNGancxbC9Oa3p1VXZxQXMKzHSIPH+HIstowdzTxj61aoGAWH69IeNU
            V/1u8xQQAOUzAxj/NZ133zLkcXVdVW0dOdbEvbpe6tFfJNauelVd8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T08:54:51Z"
    mac: ENC[AES256_GCM,data:0psnGn62DsfyfjdLCL6rH3Wfd7IeY9v5aH/S+r3Qi0juFxOHBr69TwMTMhtv2sWVa4O+o72TnJ5gcKitj/k/7vlBF4+oDVrAxmwTWTptzwratqLZEONBO489et9umsovXBM61+LfnmzUrziqZU5U+zKSCChzxEIJNpRgAy7bChU=,iv:S9ttyMHckRnpQ49V0X3g0dp+mCS85szpEseDJvoIsH8=,tag:QI7QkoZ7+MWCDrcuwsSEoA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
