apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-operator
spec:
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.23.2
      sourceRef:
        kind: HelmRepository
        name: cloudnativepg
        namespace: flux-system
  interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    crds:
      create: true
