apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 1h
  chart:
    spec:
      chart: cert-manager
      version: "v1.20.3"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
      interval: 12h
  values:
    image:
      repository: quay.io/jetstack/cert-manager-controller
      tag: v1.20.3@sha256:6c13d61e0348a5bc3477f8ea9a928624300b30d19b1c72a7d2b90372fc713db4
    webhook:
      image:
        repository: quay.io/jetstack/cert-manager-webhook
        tag: v1.20.3@sha256:a61e817632cebed3bb59a189327e786fa3fdd7597167d994a1848d98fd55848f
    cainjector:
      image:
        repository: quay.io/jetstack/cert-manager-cainjector
        tag: v1.20.3@sha256:06ad347fe0dc2eb84cc355c26f6752e05e87dceb6447f5cd29b963dd66dfd8bd
    startupapicheck:
      image:
        repository: quay.io/jetstack/cert-manager-startupapicheck
        tag: v1.20.2@sha256:4e2a69b4a0cc9627905bbeecf720f95d5153ca39cacdab923d2748e73556792b
    installCRDs: true
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
        labels:
          scrape: "true"
