apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yml
  - configmap.yml
  - release.yml

configMapGenerator:
  - name: lemmy-themes
    files:
      - catppuccin-mocha.css
    options:
      disableNameSuffixHash: true
