apiVersion: v1
kind: Secret
metadata:
    name: deepinfra
    namespace: ai
stringData:
    #ENC[AES256_GCM,data:qDfPwPaU9q0gdHqNv4ybbtu4sE3yK/Bq2cON7Nj1M8A5f6pmaDwn6wj9ydQvPKdEKx3H58QkJKkE1vW5jSGfqjz6,iv:84J6qEOR9S9mx+cnbfCj8UUzYUfh8TElYj9CpFUR8cw=,tag:7TYNDFrlz4Aiwl0IF/ZuQw==,type:comment]
    #ENC[AES256_GCM,data:f2+x99JUTT7iEumPdh0IyVOxrPfhRSHlGG2LHObBTFiWhWzKydhKrDeTjQGBrIaeHQfwerD7GfC8C/cWCubivVo5ZDv2rfXxuBivwLc=,iv:iD4UoqYTDkbUV4h1ymlT0QI5R0dhRnGZ1Ls/gee40p0=,tag:cA6IXTVnoQUqMxd9C7O9bA==,type:comment]
    Authorization: ENC[AES256_GCM,data:MsJTBfO/RmaBORlX2rh6/tiMJdJaGF7ZSxd9b55Rejk=,iv:TBI/TPHEpEU/GEtYE/6vqFyWc35apM/y7qAE6n2oIxA=,tag:02hdwZ0n1Nv56zSQOOfAMA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNHpHWGl3ZTh0dkNpVlRS
            Um9kOFlLa2pIeWdCOVQwWXFuUEdSOEVxYlFFCkFsTjBpbThUaGFwSjllaFRqdnZT
            Y0U0RkJpUk5OSmFrUGN3Nk45TGR6Y28KLS0tIG5NME1hT290VFp2R3NUMVBnRGE1
            RXZpUzkya25VSHJFVjBoNzlWUFZBbDAKCECxsND1SuM8Ua2yenFziKPMSRptU+US
            06G9/eodvAKnqVONM5A/NSD3sXEk3guEVAUs46VDXngtaLbEJRoiwg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T17:08:52Z"
    mac: ENC[AES256_GCM,data:GR96DGB/fvB6E7ZcWAEJq29wkswhOfwt7llWGX0efezulcj1VXIyUO0v9+qR5PRSmaWEuvHkoqqYLyT413SqB6ynhdz63ZuQq3QDlhVkT2ywotAd1ty7Suf5tPZzmImBBjTZ0N/AcsmJMddVbMQlnq7Yap9/T980pMs9VKSX9y8=,iv:Fo8vb6+4IATuDbGTnpR/tyrOcULKBaHGgUzOm6Jy/wQ=,tag:oKeTGCGHlS/UwDZuJtZOkw==,type:str]
    version: 3.13.1
