apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: gemma-4-12b-it-auth
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: gemma-4-12b-it-ai
  traffic:
    apiKeyAuthentication:
      mode: Strict
      secretRef:
        name: ai-apikeys
