apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gemma-4-12b-it-cache
  labels:
    app.kubernetes.io/name: gemma-4-12b-it
    app.kubernetes.io/part-of: llama-cpp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-delete
  resources:
    requests:
      storage: 10Gi
