apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  interval: 15m
  chart:
    spec:
      chart: homepage
      version: 2.0.1
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/gethomepage/homepage
      tag: v1.7.0
    env:
      HOMEPAGE_ALLOWED_HOSTS: &host home.nahsi.dev
    serviceAccount:
      create: true
      name: homepage
    enableRbac: true
    ingress:
      public:
        enabled: true
        ingressClassName: nginx-public
        annotations:
          cert-manager.io/cluster-issuer: "nahsi.dev"
        hosts:
          - host: *host
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: homepage-tls

      private:
        enabled: true
        ingressClassName: nginx-private
        annotations:
          cert-manager.io/cluster-issuer: "nahsi.dev"
        hosts:
          - host: *host
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: homepage-tls

    config:
      bookmarks: null

      kubernetes:
        mode: cluster
        ingress: true

      settings:
        title: NahsiLabs Dashboard
        favicon: https://kubernetes.io/images/favicon.png
        theme: dark
        color: slate
        target: _self
        headerStyle: clean

        quicklaunch:
          searchDescription: true
          hideInternetSearch: true
          hideVisitURL: true

        layout:
          Media:
            style: columns
          Apps:
            style: columns
          Infra:
            style: columns
          Observability:
            style: columns

      widgets:
        - search:
            provider: [duckduckgo]
            focus: false
            target: _blank
        - kubernetes:
            cluster:
              show: true
              cpu: true
              memory: true
            nodes:
              show: false

      services:
        - Infra:
            - Proxmox:
                icon: proxmox
                href: https://proxmox.nahsi.dev
                ping: https://proxmox.nahsi.dev
            - Truenas:
                icon: truenas
                href: https://truenas.nahsi.dev
                ping: https://truenas.nahsi.dev
            - Unifi:
                icon: ubiquiti
                href: https://unifi.nahsi.dev
                ping: https://unifi.nahsi.dev
            - Adguard:
                icon: adguard-home
                href: https://adguard.nahsi.dev
                ping: https://adguard.nahsi.dev
            - NPM:
                icon: nginx-proxy-manager
                href: https://npm.nahsi.dev
                ping: https://npm.nahsi.dev
            - IPMI:
                icon: asrock-rack-ipmi
                href: https://ipmi.nahsi.dev
                ping: https://ipmi.nahsi.dev

        - Observability:
            - Ceph:
                icon: ceph
                href: https://ceph.nahsi.dev
                ping: https://ceph.nahsi.dev
            - Cyberpower:
                icon: powerpanel
                href: https://power-panel.nahsi.dev
                ping: https://power-panel.nahsi.dev

        - IoT:
            - Home Assistant:
                icon: home-assistant-alt
                href: https://ha.nahsi.dev
                ping: https://ha.nahsi.dev
            - Valetudo:
                icon: valetudo
                href: https://valetudo.nahsi.dev
                ping: https://valetudo.nahsi.dev

        - Apps:
            - Wireguard:
                icon: wireguard
                href: http://vpn.nahsi.dev
                ping: http://vpn.nahsi.dev
            - qBittorent:
                icon: qbittorrent
                href: https://torrent.nahsi.dev
                ping: https://torrent.nahsi.dev
