apiVersion: v1
kind: Secret
metadata:
    name: langfuse-s3-auth
    annotations:
        kustomize.toolkit.fluxcd.io/prune: disabled
type: Opaque
stringData:
    access_key: ENC[AES256_GCM,data:vLNf1loVgVU=,iv:sBV6G2q1SYvGmbuVUcn7SoZfqZp9/Dv/yORifJh/Fy4=,tag:+jiIUTGfzNaos8dMSSji9Q==,type:str]
    secret_key: ENC[AES256_GCM,data:vfgMEKA3xZKbCwS+BZUq5QZ44KFBas4g8NYbZJCl/67zyEWHfPDxCM0P6kf1/Wb4TJiaai5Y/7s=,iv:qjOgGivyzOxDnaAsoowhvyM6re8CsCuv4wcfM2ukixQ=,tag:x0MQ2NfCMsQGfe2qKNdobQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRWMwSjlydWNZVkIvYWph
            eHdDdVRWQmkvZkNENTI2R1VueXZERnBBbG5FClpOL0hhenVIaTcvb01CdTJxWmdK
            SnJrZFFiYWdOOG1VeGlNWmVNRFk2d1EKLS0tICtCTHdVNDMwUm5qZS9QRWVoUWRW
            TzFKUjh3OGNvMFlGaXdlRmkzMHVqbFUKV9YHSVATzm+WDMARjYyJbuzcETT10/f+
            +241MgTVBUT1N+HsmrlGFXBC/WTI+hJ858CLBFIy9tV6l8zfr2Ua4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T16:59:30Z"
    mac: ENC[AES256_GCM,data:fIO7qsSROQc2MZWLT5BvwYIdRHPjieV1CBp5SePtKtfW7Fq8jWzF23ZOkO8QixCnKJTVBxkhkugoHAwcPBE2fEcOx3uEPexFSwo+i/hmla6cUuN2niJqCMGuq/ZnOM9FReFX3LyWQxy442j3LTAPNtevNMunVJzhExHCGlIzHMo=,iv:XzPK7/EnIuJ0f4jBZyA8cLyJo0+1cBLB5Eo1f/C94c4=,tag:E52czJAAGhkmw32W2M/cjA==,type:str]
    version: 3.13.3
