apiVersion: v1
kind: Secret
metadata:
    name: langfuse-runtime
    annotations:
        kustomize.toolkit.fluxcd.io/prune: disabled
type: Opaque
stringData:
    SALT: ENC[AES256_GCM,data:+3fX8OseUwTZuWhVF1hT4SivrFqMSYUKMHG0J4wy864JsmC46nfNV3M2hA==,iv:L8bVr2eTHgR4SDOEq6hDixyAKaIBUxaBkdD4RTVf1HM=,tag:6sS9FF+JhH5+5OQgdkoWKQ==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:h9IR/eq3AcAhHzKgfIpwzplTEj+heDvVz2/Nxc5vzVR0C9Xteu3Rah9klFqbr4sft/7PCCweFdKE7LdqPiw7iQ==,iv:H5db1+JSVLZJQAV0NKidJ+XlEt5B7Eo/LSzCb0DEqwA=,tag:y38WBwzD4DGNXRxq8uJ8kg==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:Y+ykqdz5MXYflg4VxDJkX4e3kTMbtujDPMnfR6lf3E8118eE8A4sT4cdcg==,iv:9MAi5oLdY66ukcEl5pzJNPASeqPAmKGeKRsJFxRJVBs=,tag:/6GrqN0OA38zE4nR+qFz4A==,type:str]
    AUTH_AUTHENTIK_CLIENT_ID: ENC[AES256_GCM,data:q+RiAxZHIRQQB6Tg8grWaA==,iv:MYEDWS5Fn4Vi3IrCF2ykfgxvTyq+6rv/KOeDXVWPOmA=,tag:6rullyOL9oD0cZWfbFQ9gg==,type:str]
    AUTH_AUTHENTIK_CLIENT_SECRET: ENC[AES256_GCM,data:XiIDHyAZKE+4diPjdrRyvkAsBF3vgQ5Y4FUnFxsICZLWRJJEnLWRMGKKg9d94e7Z9FCyO4lVEss1oRzHQPRC2nRGf1F676KwZj4PAxknplTIVQmXgPOJHjOtfNgIfsMC+7g+k02uQ9SooPRxP9z4XiI5TocuB0PA4qknJG20dhg=,iv:GhB5LVTlCsWQoMUkDTUuihRvg0cQD2WeBmFh7Ote9Ns=,tag:T9ey1m2421Nk4w3fLtP92w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VUxoTmJKbEVyMHU0MXRL
            eXlJTUhhMnlrWU84eENoWHNwcUtud2xMYkVrCnNFNWlWRjdBMllhNks5ZDhDbU5i
            Tk1sU0V4Y3J0WTV1OGFDaFFtN2pPWTQKLS0tIDMwVXF6MFlMYmZydlh2K3FKVmFo
            M3pkYWdhRW9kLyswbWFTak9CR2RJeTgK40g4VuULRzPSG1ZBamRquI58YyrOLy77
            3ZbLrRtb9iAEGm+zvKGEboiZNcCJLpbUal6LYyzJxs3BnWUWQmaTLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T16:54:39Z"
    mac: ENC[AES256_GCM,data:JHfewNY0Okbm6wYcSDtAOz6HONMW2UwYU702mndyKJ9AaErRWzBwTlPMhXKXft8gtZyHRdERoq4k6srThoxjDURvz8g5U/fuNRv3gyHK7kIorfQy6YJXp2KFRbkSORLNw8bVK+wchgvhUD3Rl5ITGoa5CCLOFjk3s1g1mxaAt7M=,iv:c/EwgDz3FZlHetkZywOoVw8jtFW6okbJXRqSkqFs7fw=,tag:RSapeAlrjZI2ru/IgUYMzg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: langfuse-clickhouse-auth
    annotations:
        kustomize.toolkit.fluxcd.io/prune: disabled
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:eidP9/old6PdUew2yzQ33dVox6Bc7abNPHKN2Ek165YYTvRtLpWpeygbLA==,iv:ymiqZiFpaAl4PiXGhNINYL2lO+mnpKCEy1T9AOdTsPI=,tag:qY/9H1M1UXx46rL5ZjPMcA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VUxoTmJKbEVyMHU0MXRL
            eXlJTUhhMnlrWU84eENoWHNwcUtud2xMYkVrCnNFNWlWRjdBMllhNks5ZDhDbU5i
            Tk1sU0V4Y3J0WTV1OGFDaFFtN2pPWTQKLS0tIDMwVXF6MFlMYmZydlh2K3FKVmFo
            M3pkYWdhRW9kLyswbWFTak9CR2RJeTgK40g4VuULRzPSG1ZBamRquI58YyrOLy77
            3ZbLrRtb9iAEGm+zvKGEboiZNcCJLpbUal6LYyzJxs3BnWUWQmaTLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T16:54:39Z"
    mac: ENC[AES256_GCM,data:JHfewNY0Okbm6wYcSDtAOz6HONMW2UwYU702mndyKJ9AaErRWzBwTlPMhXKXft8gtZyHRdERoq4k6srThoxjDURvz8g5U/fuNRv3gyHK7kIorfQy6YJXp2KFRbkSORLNw8bVK+wchgvhUD3Rl5ITGoa5CCLOFjk3s1g1mxaAt7M=,iv:c/EwgDz3FZlHetkZywOoVw8jtFW6okbJXRqSkqFs7fw=,tag:RSapeAlrjZI2ru/IgUYMzg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: langfuse-valkey-auth
    annotations:
        kustomize.toolkit.fluxcd.io/prune: disabled
type: Opaque
stringData:
    default: ENC[AES256_GCM,data:RcvusWVX3Bnv3dlg4t77A1Gp74jv1iMZnlwmzAh+IPKAK0R6UyNNvT4UEA==,iv:yHisJLdQ4SlkemlHCwqYanZVwMv9xXqsU3h1HIBzz8o=,tag:uqRIl9PSnVQZ7cmv3Ehrtg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VUxoTmJKbEVyMHU0MXRL
            eXlJTUhhMnlrWU84eENoWHNwcUtud2xMYkVrCnNFNWlWRjdBMllhNks5ZDhDbU5i
            Tk1sU0V4Y3J0WTV1OGFDaFFtN2pPWTQKLS0tIDMwVXF6MFlMYmZydlh2K3FKVmFo
            M3pkYWdhRW9kLyswbWFTak9CR2RJeTgK40g4VuULRzPSG1ZBamRquI58YyrOLy77
            3ZbLrRtb9iAEGm+zvKGEboiZNcCJLpbUal6LYyzJxs3BnWUWQmaTLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T16:54:39Z"
    mac: ENC[AES256_GCM,data:JHfewNY0Okbm6wYcSDtAOz6HONMW2UwYU702mndyKJ9AaErRWzBwTlPMhXKXft8gtZyHRdERoq4k6srThoxjDURvz8g5U/fuNRv3gyHK7kIorfQy6YJXp2KFRbkSORLNw8bVK+wchgvhUD3Rl5ITGoa5CCLOFjk3s1g1mxaAt7M=,iv:c/EwgDz3FZlHetkZywOoVw8jtFW6okbJXRqSkqFs7fw=,tag:RSapeAlrjZI2ru/IgUYMzg==,type:str]
    version: 3.13.3
