apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: qwen3-1-7b-llm
spec:
  ai:
    provider:
      openai:
        model: Qwen/Qwen3-1.7B
      host: qwen3-1-7b.ai.svc.cluster.local
      port: 8080
