apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: recommendarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: docker.io/tannermiddleton/recommendarr
      tag: v1.3.0@sha256:0462ed4689f721f1c8806c0d3d55bc5b4089015b931fab21f72f28aea8bb05c2

    env:
      PUBLIC_URL: https://recommendarr.nahsi.dev
      DOCKER_ENV: true
      PORT: 3000
      FORCE_SECURE_COOKIES: true

    podSecurityContext:
      runAsUser: 65534
      runAsGroup: 65534
      runAsNonRoot: true
      fsGroup: 65534
      fsGroupChangePolicy: OnRootMismatch

    service:
      main:
        controller: recommendarr
        ports:
          http:
            port: 3000

    ingress:
      main:
        enabled: true
        ingressClassName: nginx-private
        annotations:
          cert-manager.io/cluster-issuer: nahsi.dev
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: "Arr"
          gethomepage.dev/name: Recommendarr
          gethomepage.dev/icon: openai.png
        hosts:
          - host: &host recommendarr.nahsi.dev
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: recommendarr-tls

    persistence:
      data:
        existingClaim: recommendarr-config
        globalMounts:
          - path: /app/server/data

    resources:
      limits:
        memory: 200Mi
      requests:
        cpu: 10m
        memory: 50Mi
