apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: clickhouse-operator
  labels:
    obs.nahsilabs/metrics: "true"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: clickhouse-operator
      app.kubernetes.io/instance: clickhouse-operator
      control-plane: controller-manager
  endpoints:
    - port: http
      path: /metrics
      scheme: http
      interval: 30s
