apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-ai-llm-gpt-oss-120b
  namespace: flux-system
spec:
  dependsOn:
    - name: app-ai-gateway
    - name: app-ai-providers-deepinfra
  path: ./flux/apps/ai/llm/catalog/gpt-oss-120b/app
  targetNamespace: ai
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
