apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-immich
spec:
  instances: 2
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16-0.4.3
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true
  storage:
    size: 10Gi
    storageClass: ceph-rbd-retain
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
