apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: myspeed
  namespace: observability
  labels:
    scrape: "true"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: myspeed
  namespaceSelector:
    matchNames:
      - observability
  endpoints:
    - port: http
      path: /api/prometheus/metrics
      interval: 30s
