apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yml
  - ingress.yml
configMapGenerator:
  - name: alloy-config
    files:
      - ./config.alloy
    options:
      disableNameSuffixHash: true
