apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
spec:
  interval: 1h
  timeout: 5m
  chart:
    spec:
      chart: alloy
      version: 0.12.3
      sourceRef:
        kind: HelmRepository
        name: grafanalabs
        namespace: flux-system
  driftDetection:
    mode: enabled
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: alloy-config
      targetPath: alloy.configMap.name
  values:
    alloy:
      configMap:
        create: false
        key: config.alloy
      clustering:
        enabled: true
        name: alloy
      storagePath: /var/lib/alloy
      enableReporting: false
      mounts:
        extra:
          - name: alloy
            mountPath: /var/lib/alloy
    controller:
      type: "statefulset"
      replicas: 1
      enableStatefulSetAutoDeletePVC: true
      volumeClaimTemplates:
        - metadata:
            name: alloy
          spec:
            accessModes: [ReadWriteOnce]
            storageClassName: ceph-rbd-delete
            resources:
              requests:
                storage: 5Gi
