apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jackett
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  values:
    image:
      repository: ghcr.io/onedr0p/jackett
      tag: 0.20.2297
    env:
      TZ: "Europe/Athens"
    service:
      main:
        ports:
          http:
            port: 9117

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx-private"
        annotations:
        hosts:
          - host: &host jackett.nahsi.dev
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: jackett-tls
            hosts:
              - *host

    probes:
      liveness:
        enabled: true
        custom: true
        spec:
          exec:
            command:
              - /usr/bin/env
              - bash
              - -c
              - curl --fail localhost:9117/health
          failureThreshold: 5
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10

    podAnnotations:
      setGateway: "true"

    podLabels:
      setGateway: "true"

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"

    persistence:
      config:
        enabled: true
        existingClaim: jackett-config

    resources:
      requests:
        cpu: 10m
        memory: 256M
      limits:
        memory: 8192M
