apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hccm
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: hcloud-cloud-controller-manager
      sourceRef:
        kind: HelmRepository
        name: hcloud
        namespace: flux-system
      version: 1.20.0
  values:
    env:
      HCLOUD_TOKEN:
        valueFrom:
          secretKeyRef:
            name: hccm
            key: HCLOUD_TOKEN
      HCLOUD_NETWORK:
        valueFrom:
          secretKeyRef:
            name: hccm
            key: HCLOUD_NETWORK
      HCLOUD_NETWORK_ROUTES_ENABLED:
        value: "false"
      HCLOUD_LOAD_BALANCERS_LOCATION:
        value: "hel1"
      HCLOUD_LOAD_BALANCERS_DISABLE_PRIVATE_INGRESS:
        value: "true"
      HCLOUD_LOAD_BALANCERS_DISABLE_IPV6:
        value: "true"
