apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-grafana
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
    storageClass: ceph-rbd-retain
