apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  interval: 1h
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: grafana
    namespace: flux-system
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    admin:
      existingSecret: grafana-admin-credentials
      userKey: user
      passwordKey: password
    envFromSecrets:
      - name: grafana-oauth
        optional: false
    env:
      - name: GF_DATABASE_URL
        valueFrom: 
          secretKeyRef:
            name: pg-grafana-app
            key: uri
    deploymentStrategy:
      type: RollingUpdate
    testFramework:
      enabled: false
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: nahsi.dev
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: "Observability"
        gethomepage.dev/name: Grafana
        gethomepage.dev/icon: grafana.png
      ingressClassName: nginx-private
      hosts:
        - &host "grafana.nahsi.dev"
      tls:
        - hosts:
            - *host
          secretName: grafana-tls
    persistence:
      enabled: false
    plugins:
      - grafana-clock-panel

    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: VictoriaMetrics
            type: prometheus
            uid: victoriametrics
            access: proxy
            url: http://vmsingle-stack.observability.svc:8429
            isDefault: true
            jsonData:
              prometheusType: Prometheus
              timeInterval: 15s

    ## Grafana's primary configuration
    ## NOTE: values in map will be converted to ini format
    ## ref: http://docs.grafana.org/installation/configuration/
    grafana.ini:
      server:
        root_url: https://grafana.nahsi.dev/
      analytics:
        check_for_updates: false
        check_for_plugin_updates: false
        reporting_enabled: false
      date_formats:
        full_date: "YYYY-MM-DD HH:mm:ss"
        interval_second: "HH:mm:ss"
        interval_minute: "HH:mm"
        interval_hour: "MMM DD HH:mm"
        interval_day: "MMM DD"
        interval_month: "YYYY-MM"
        interval_year: "YYYY"
      news:
        news_feed_enabled: false
      users:
        allow_sign_up: false
        auto_assign_org: true
        auto_assign_org_role: Admin

    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
        folderAnnotation: grafana_folder
        provider:
          disableDelete: true
          foldersFromFilesStructure: true
      datasources:
        enabled: true
        searchNamespace: ALL
      enableUniqueFilenames: true
