apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAuth
metadata:
  name: stack
spec:
  selectAllByDefault: true
  ingress:
    class_name: nginx-private
    tlshosts:
      - hosts:
          - vam.nahsi.dev
        secretName: vam-tls
    annotations:
      cert-manager.io/cluster-issuer: nahsi.dev
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: "Observability"
      gethomepage.dev/name: VictoriaMetrics
      gethomepage.dev/icon: victoriametrics.png
  replicaCount: 1
