apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: stack
spec:
  # -- Data retention period. Possible units character: h(ours), d(ays), w(eeks), y(ears), if no unit character specified - month. The minimum retention period is 24h. See these [docs](https://docs.victoriametrics.com/single-server-victoriametrics/#retention)
  retentionPeriod: "6"
  storage:
    accessModes: [ReadWriteOnce]
    resources:
      requests:
        storage: 10Gi
    storageClassName: ceph-csi
