apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-retain
  volumeName: pvc-15dc76f8-3194-4c93-9a7d-1daf87abd1d1
  resources:
    requests:
      storage: 50Gi
