---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-jellyfin-video
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
    - nconnect=8
    - noatime
    - soft
    - softerr
    - timeo=50
    - retrans=3
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nfs.lan#mnt/storage/media/video#jellyfin
    volumeAttributes:
      server: nfs.lan
      share: /mnt/storage/media/video
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-video
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: nfs-jellyfin-video
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-jellyfin-music
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
    - nconnect=8
    - noatime
    - soft
    - softerr
    - timeo=50
    - retrans=3
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nfs.lan#mnt/storage/media/music/library#jellyfin
    volumeAttributes:
      server: nfs.lan
      share: /mnt/storage/media/music/library
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-music
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: nfs-jellyfin-music
  resources:
    requests:
      storage: 1Gi
