apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: lfm2-5-8b-a1b
spec:
  ai:
    provider:
      openai:
        model: LiquidAI/LFM2.5-8B-A1B
      host: lfm2-5-8b-a1b.ai.svc.cluster.local
      port: 8080
