apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/home-operations/radarr
      tag: 5.23.1.9914

    env:
      TZ: "Europe/Athens"
      RADARR__INSTANCE_NAME: Radarr
      RADARR__PORT: &port 7878
      RADARR__APPLICATION_URL: "https://Radarr.nahsi.dev"
      RADARR__LOG_LEVEL: info

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: nginx-private
        annotations:
          cert-manager.io/cluster-issuer: nahsi.dev
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: "Arr"
          gethomepage.dev/name: Radarr
          gethomepage.dev/icon: radarr.png
        hosts:
          - host: &host radarr.nahsi.dev
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: radarr-tls

    persistence:
      config:
        enabled: true
        existingClaim: radarr-config
      data:
        enabled: true
        existingClaim: radarr-video

    podSecurityContext:
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534

    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
