---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-retain
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-video
spec:
  capacity:
    storage: 1Gi # doesn't matter
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-radarr-video
  mountOptions: 
    - "nconnect=8"
    - "hard" 
    - "noatime"
  nfs:
    server: nfs.lan
    path: /mnt/storage/media/video
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-video
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-radarr-video
  volumeName: radarr-video
  resources:
    requests:
      storage: 1Gi
