apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
spec:
  interval: 1h
  chart:
    spec:
      chart: vaultwarden
      version: "0.46.1"
      sourceRef:
        kind: HelmRepository
        name: vaultwarden
        namespace: flux-system
      interval: 1h
  values:
    resourceType: StatefulSet
    domain: "https://secrets.nahsi.dev"
    logging:
      logLevel: debug
    ingress:
      enabled: false
    httpRoute:
      enabled: true
      additionalAnnotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: "Productivity"
        gethomepage.dev/name: Vaultwarden
        gethomepage.dev/icon: vaultwarden.png
        gethomepage.dev/pod-selector: "app.kubernetes.io/name=vaultwarden"
      parentRefs:
        - name: private-gateway
          namespace: envoy-gateway
          sectionName: https
        - name: public-gateway
          namespace: envoy-gateway
          sectionName: https
      hostnames:
        - secrets.nahsi.dev
      path: /
    adminToken:
      existingSecret: vaultwarden-secret
      existingSecretKey: token
    storage:
      data:
        name: vaultwarden-data
        class: ceph-rbd
        accessMode: ReadWriteOnce
        size: 1Gi
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
    database:
      type: postgresql
      existingSecret: pg-vaultwarden-app
      existingSecretKey: uri
