apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-wallabag
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  primaryUpdateStrategy: unsupervised
  storage:
    size: 2Gi
    storageClass: ceph-rbd
