apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wallabag
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    # renovate: datasource=github-releases depName=wallabag/wallabag
    appversion: 2.6.13
    defaultPodOptions:
      securityContext:
        runAsUser: 0
    controllers:
      main:
        type: statefulset
        containers:
          main:
            image:
              repository: docker.io/wallabag/wallabag
              # renovate: datasource=github-releases depName=wallabag/wallabag
              tag: 2.6.13
            env:
              TZ: Europe/Athens
              POPULATE_DATABASE: false
              SYMFONY__ENV__DOMAIN_NAME: "https://wallabag.nahsi.dev"
              SYMFONY__ENV__SERVER_NAME: "Wallabag"
              SYMFONY__ENV__FOSUSER_REGISTRATION: true
              SYMFONY__ENV__FOSUSER_CONFIRMATION: false
              SYMFONY__ENV__DATABASE_DRIVER: pdo_pgsql
              SYMFONY__ENV__DATABASE_HOST:
                valueFrom:
                  secretKeyRef:
                    name: pg-wallabag-app
                    key: host
              SYMFONY__ENV__DATABASE_PORT:
                valueFrom:
                  secretKeyRef:
                    name: pg-wallabag-app
                    key: port
              SYMFONY__ENV__DATABASE_USER:
                valueFrom:
                  secretKeyRef:
                    name: pg-wallabag-app
                    key: username
              SYMFONY__ENV__DATABASE_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: pg-wallabag-app
                    key: password
              SYMFONY__ENV__DATABASE_NAME:
                valueFrom:
                  secretKeyRef:
                    name: pg-immich-app
                    key: dbname

    service:
      main:
        controller: main
        ports:
          http:
            port: 80

    ingress:
      public:
        annotations:
          cert-manager.io/cluster-issuer: nahsi.dev
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: "Media"
          gethomepage.dev/name: Wallabag
          gethomepage.dev/icon: wallabag.png
        className: "nginx-public"
        hosts:
          - host: &host wallabag.nahsi.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http

        tls:
          - hosts:
              - *host
            secretName: wallabag-tls

      private:
        annotations:
          cert-manager.io/cluster-issuer: nahsi.dev
        className: "nginx-private"
        hosts:
          - host: *host
            paths:
              - path: /
                service:
                  identifier: main
                  port: http

        tls:
          - hosts:
              - *host
            secretName: wallabag-tls

    persistence:
      data:
        enabled: true
        existingClaim: wallabag-data
        advancedMounts:
          main:
            main: 
              - path: /var/www/wallabag/data
      images:
        enabled: true
        existingClaim: wallabag-images
        advancedMounts:
          main:
            main: 
              - path: /var/www/wallabag/web/assets/images
