apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  interval: 1h
  chart:
    spec:
      chart: homepage
      version: 2.1.0
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/gethomepage/homepage
      tag: v2.1.2@sha256:da9dca9ec258c628146bed1445da0853f2b88f0b10bafd97c091de807c363d60
    env:
      HOMEPAGE_ALLOWED_HOSTS: &host home.nahsi.dev
    serviceAccount:
      create: true
      name: homepage
    enableRbac: true
    config:
      bookmarks:
        - NahsiLabs:
            - Infra Repo:
                - href: https://github.com/nahsilabs/infra

      kubernetes:
        mode: cluster
        ingress: true
        gateway: true

      settings:
        title: NahsiLabs Dashboard
        favicon: https://kubernetes.io/images/favicon.png
        theme: dark
        color: slate
        target: _self
        headerStyle: clean

        quicklaunch:
          searchDescription: true
          hideInternetSearch: true
          hideVisitURL: true

        layout:
          - Productivity:
              tab: Daily Use
              style: columns
              columns: 4
          - Knowledge:
              tab: Daily Use
              style: columns
              columns: 3
          - Media:
              tab: Daily Use
              style: columns
              columns: 3
          - Comms:
              tab: Daily Use
              style: columns
              columns: 2
          - Arr:
              tab: Data Hoarding
              style: columns
              columns: 4
          - Downloads:
              tab: Data Hoarding
              style: columns
              columns: 3
          - Platform:
              tab: Systems
              style: columns
              columns: 4
          - Observability:
              tab: Systems
              style: columns
              columns: 4

      widgets:
        - search:
            provider: [duckduckgo]
            focus: false
            target: _blank
        - kubernetes:
            cluster:
              show: true
              cpu: true
              memory: true
            nodes:
              show: false

      services:
        - Platform:
            - Proxmox:
                icon: proxmox
                href: https://proxmox.nahsi.dev
                ping: https://proxmox.nahsi.dev
            - Truenas:
                icon: truenas
                href: https://truenas.nahsi.dev
                ping: https://truenas.nahsi.dev
            - RustFS:
                icon: rustfs
                href: https://rustfs.nahsi.dev
                ping: https://rustfs.nahsi.dev
            - Unifi:
                icon: unifi
                href: https://unifi.nahsi.dev
                ping: https://unifi.nahsi.dev
            - Adguard:
                icon: adguard-home
                href: https://adguard.nahsi.dev
                ping: https://adguard.nahsi.dev
            - NPM:
                icon: nginx-proxy-manager
                href: https://npm.nahsi.dev
                ping: https://npm.nahsi.dev
            - IPMI:
                icon: asrock-rack-ipmi
                href: https://ipmi.nahsi.dev
                ping: https://ipmi.nahsi.dev
            - Wireguard:
                icon: wireguard
                href: http://vpn.nahsi.dev
                ping: http://vpn.nahsi.dev

        - Observability:
            - Scrutiny:
                icon: scrutiny
                href: https://scrutiny.nahsi.dev
                ping: https://scrutiny.nahsi.dev
            - Ceph:
                icon: ceph
                href: https://ceph.nahsi.dev
                ping: https://ceph.nahsi.dev
            - Cyberpower:
                icon: powerpanel
                href: https://power-panel.nahsi.dev
                ping: https://power-panel.nahsi.dev

        - Productivity:
            - Home Assistant:
                icon: home-assistant
                href: https://ha.nahsi.dev
                ping: https://ha.nahsi.dev
