apiVersion: v1
kind: Secret
metadata:
    name: browsertrix-values
    namespace: browsertrix
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:tuTcunaZY3xuZYaTOFgNNSi3fA9/Vb2nQQp6hwDCqPSS9PP5CmWfeca/dYc+jgpXcPJZsm/r4cH1Q186y8mTAOKZBHe0qJEij8gOQtiCekE3LWDKu9J6ZLEoML2Nu3c3FVYvKop6VvKHi/rzrvdtcwz9RErKmfvJTwzgzCYvsYcYU0SYq/2Km3cLtcmaueSKrKhtElyYDWNZCpxQAZP3rE4QgsfM4VpxnD0CIbJ6L4tmrC5GvqWz1gcpExu5huu1MD8NyiiOynSSANixm6fPXda03uJ7P8+4vyppuxQUSjOMV42ujvXxBS42nIb1hgBbZi/JxT/uDF4FhHhrKZNqcHWusDbPPQxPlXSmTTM/J69JTXFCnuk7HFX7sZwGixoLq2DfsNi59+5T/3VK8RzKuSVz9Tqz0XT4a14spO1pi7XWKsC9vcQh2vpGsF+FK3lUbSozpx2QAQ6X3qMKeyC3R+Qtl5jOEHdKOsVh09BGhskdiKkh3Gx2JyWJPesszBn+cSqOI+SU10lonDGFqrK2pfnJ19m8PIxMS9UrQ3MHDTAiemMSwUFI08NMHONoJzFn6W4Tjz5D8guVATHPQDlQeqq4Ra3LgSixdWVDXGxn5Hje/VULyVMXR9K+68luN9rtCau04Mm/LCM0bU1eB4Qctfjr+yLqNiIm+zgvmgiqsQKJWmjGy0/1udqNhGmCiBZi0WK3kt4VY4dNDpns7+iJjBiQSQDdlqSEs/fmN1y/Q5krBusV7xwO7DGpIWohY3VHqrB4udAFIm3EtzNJ4pbZzQxVJK7y5otKdnP1369AdaNHQLVNNfJ6vwQnzz1CNx/gKuHeORaXGdH8uevZseo1oIFSUoGbAtoGrVfVyrSN9oxCsqiWWKe1FnCXcqz3hwYSqnz5AARvciYe2KLq8IOaDNdTjo1+bcqM5d61efjK4cEEOVhWX+A4B0oe96NO4+w6OFViQesV5zly4ZLZas5Yd++lundfareQUwuliaxkY3nXEybhFiDqBpaGowZyT221BjVLtjC/zDRUAt2JZRJjrwk=,iv:pbJYFgUyGlwgCf2gCJoPdtXiW9tsP4KHY0rZAnnvLcA=,tag:sigHjwgyy8ISu4GF3TggZQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOG80dHcwN3UvbmM1YkJw
            cWJWejdQVzV1eDhhZ21GVlM5eWRiM1U2WHdRCldQUFdEMkF5cG41YnBPSlVBZXdJ
            RENpbUxVVWZYbHl6TVlCdlZnbjZqN0EKLS0tIHhkZGkzbmZJVTdvdm0zYmY1QVFr
            MW50TWxTU1dpYXBwWmxWS09pT3ZRZ0kKXwEVrZ0qkxuGoELtsoBRmgBSHuEJ5lKa
            678KjNBmQ1u40MpkijNVG5qoQauIfC1902JXAjOJXVyohZPiPLdTgA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T09:19:15Z"
    mac: ENC[AES256_GCM,data:cCu5tEJfE3IHSn6/YqwxO7VOXMyL3Ww4j9xvJbD+HpQl9hu4COxE7/vp+HtLIM+Uolr6xQ+4AJucvtX9JxaWYwAGQoTRwMNoAKnbHmADmxWoW7ZwSFHQhpDDhzTjzY/hFvZeuk7Vf9gkZK2nsw1foIyt+wWxcR5W2R9h4P9jrI4=,iv:CKXNkefjjnSjYEVcLuUZU2UjUMzPZewDm6n+E2Icvmw=,tag:hB13TmzQnBuHO8t7X2Salg==,type:str]
    version: 3.13.1
