apiVersion: v1
kind: Secret
metadata:
    name: trek-secret
stringData:
    OIDC_ISSUER: ENC[AES256_GCM,data:ohWDsT+vK5DjccMWQKqL37zX+IorPIgYObQii0I/oLVAV2cklAn74Lm+,iv:PBUR5xbdga1rUbr61en4qytZ52Q3CtvDR+lMLBiUv9w=,tag:++LUqRx2LYKxnIhQYhy+fw==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:qtxU+YZQFTE4cMrK7uohyg==,iv:Az+D9EDOUcUrDam2vI4SIL9xirUU55swwVEIcM/OCH8=,tag:JrJ2ovkV4cLPBUIjx97scA==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:pTRRXuRUjEHVrp6RhZdOLCkk9EK9fLYHByVabwwZRkq99jEIUM6YfIigVUIDajRS5pl1Xdb0iWYCEHXaTcG4WrWnJPGmQx9h04ZV3jedPb8JbXpd8VPjAazf9ivWDQaMCU6wyZqZ28tD3naxcCpKWT51y+vx+XF/K32Ctd2fgUo=,iv:q/0CvUpWiM+MLDYXB2y66ZQERi4mrZxzWAxy9+diBNA=,tag:gu9OAf4mH+OfTc10tzLsNg==,type:str]
    OIDC_ONLY: ENC[AES256_GCM,data:1uLQsQ==,iv:adNrDKsrO5TbQsrRxJqprZ2kDoBTM23MG4sNjrGomvY=,tag:yyw6kI012eXfYQwJ24NcNA==,type:str]
    OIDC_DISCOVERY_URL: ENC[AES256_GCM,data:x3I16mk8ZIbAGxPx4rp29iZVET7yTqx1oEiVZEEPSLUwRRx/wgRcLYE+KqPQmPo8IxT+lwKtgc5khwl7BQFEvR4l8/vQUyR6+ck=,iv:3Lm/kf3zboj6DmE0MjeuUxWqGu8F3WhRAT38dvsPLvk=,tag:FqVHDimghD35QP59l4m9Og==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:f3XWegRUzgSTFf3/kHmOMb5aL/cJESAaOOopUsjdwFsU4XkJ1uO46wz/VPl2mHUJhBGyueGbGBM4u6BXnUARWA==,iv:f/91L6Te2nSl8Z81nEa7IGEMVN8pCrmofR0uEHPPD54=,tag:Y9hORyg7MuXZG5YjA0Y6vQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHcmtIY1dJZ3Y4UWpnenlp
            REM1Zm9WRTdXNVpYWFpCWjdXNDRRbDk3NUZzCnNNWk84bGp0V0tGcVVJN1hONzJo
            TkxNVDFjRDhVSlB4NndicXUzUk1SQTgKLS0tIGNsVkVjU3lNMHBPZHVVUkp2MmRo
            Z2lXeGh3L1h3anRhN3BzQnFIc3ZPYncK/w95oDK76ir2pnwl6k4vfvrGtEcxY7XI
            wmgtLXkscMQAecZmjtyWFwPEO/xoq2zoQ/j0FLxOu26QaUk/scSkSQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-08T16:38:25Z"
    mac: ENC[AES256_GCM,data:vZH5VTmtiJuSE5s0hxT7dx6Ol7nce2e/wcyojO9h030+4zPD8pkuOmvjaeHfKDTFk4EWJDr55/ftW0r5tEKhmcl2LG02MCZqQC7/2Y5yWL/e4tLOubjlRZZ3k5F2btgYV5YN3KY8n9qYtddWd7yOw/5zMMadUoECn9nb6DQpR+g=,iv:nQdSXO1ia3vjsbwkbeSOTmrEZpPs1dF5u8Vq12tmpBk=,tag:CNe9Z/FJry9NeZupHjpoNw==,type:str]
    version: 3.13.1
