apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mautrix-telegram
spec:
  secretStoreRef:
    kind: SecretStore
    name: kubernetes
  target:
    name: mautrix-telegram-config-secret
    template:
      engineVersion: v2
      data:
        config.yaml: |
          network:
            api_id: {{ .api_id }}
            api_hash: {{ .api_hash }}
            device_info:
              device_model: mautrix-telegram
              system_version:
              app_version: auto
              lang_code: en
              system_lang_code: en
            animated_sticker:
              target: webp
              convert_from_webm: true
              args:
                width: 320
                height: 320
                fps: 25
            member_list:
              max_initial_sync: 100
              sync_broadcast_channels: false
              skip_deleted: true
            ping:
              interval_seconds: 30
              timeout_seconds: 10
            proxy:
              type: disabled
            sync:
              update_limit: 100
              create_limit: 50
              login_sync_limit: 15
              direct_chats: true
            takeout:
              dialog_sync: false
              forward_backfill: false
              backward_backfill: false
            max_member_count: -1
            contact_avatars: false
            contact_names: false
            always_custom_emoji_reaction: false
            saved_message_avatar: mxc://maunium.net/XhhfHoPejeneOngMyBbtyWDk
            always_tombstone_on_supergroup_migration: false
            image_as_file_pixels: 16777216
            disable_view_once: false
            displayname_template: "{{ `{{ if .Deleted }}Deleted account {{ .UserID }}{{ else }}{{ .FullName }}{{ end }}` }}"

          bridge:
            command_prefix: '!tg'
            personal_filtering_spaces: true
            private_chat_portal_meta: true
            async_events: false
            split_portals: false
            resend_bridge_info: false
            no_bridge_info_state_key: false
            bridge_status_notices: errors
            unknown_error_auto_reconnect: true
            unknown_error_max_auto_reconnects: 10
            bridge_matrix_leave: false
            bridge_notices: false
            tag_only_on_create: true
            only_bridge_tags: [m.favourite, m.lowpriority]
            mute_only_on_create: true
            deduplicate_matrix_messages: false
            cross_room_replies: true
            revert_failed_state_changes: false
            kick_matrix_users: true
            enable_send_state_requests: false
            phone_numbers_in_profile: false
            cleanup_on_logout:
              enabled: true
              manual:
                private: kick
                relayed: nothing
                shared_no_users: kick
                shared_has_users: nothing
              bad_credentials:
                private: nothing
                relayed: nothing
                shared_no_users: nothing
                shared_has_users: nothing
            relay:
              enabled: false
              admin_only: true
              prefer_default: true
              allow_bridge: true
              default_relays: []
              message_formats:
                m.text: "{{ `<b>{{ .Sender.DisambiguatedName }}</b>: {{ .Message }}` }}"
                m.notice: "{{ `<b>{{ .Sender.DisambiguatedName }}</b>: {{ .Message }}` }}"
                m.emote: "{{ `* <b>{{ .Sender.DisambiguatedName }}</b> {{ .Message }}` }}"
                m.file: "{{ `<b>{{ .Sender.DisambiguatedName }}</b> sent a file{{ if .Caption }}: {{ .Caption }}{{ end }}` }}"
                m.image: "{{ `<b>{{ .Sender.DisambiguatedName }}</b> sent an image{{ if .Caption }}: {{ .Caption }}{{ end }}` }}"
                m.audio: "{{ `<b>{{ .Sender.DisambiguatedName }}</b> sent an audio file{{ if .Caption }}: {{ .Caption }}{{ end }}` }}"
                m.video: "{{ `<b>{{ .Sender.DisambiguatedName }}</b> sent a video{{ if .Caption }}: {{ .Caption }}{{ end }}` }}"
                m.location: "{{ `<b>{{ .Sender.DisambiguatedName }}</b> sent a location{{ if .Caption }}: {{ .Caption }}{{ end }}` }}"
              displayname_format: "{{ `{{ .DisambiguatedName }}` }}"
            portal_create_filter:
              mode: deny
              list: []
              always_deny_from_login: []
            permissions:
              "*": relay
              "nahsi.dev": user
              "@me:nahsi.dev": admin

          database:
            type: postgres
            uri: "{{ .db_uri }}"
            max_open_conns: 5
            max_idle_conns: 1

          homeserver:
            address: http://synapse.matrix.svc:8008
            domain: nahsi.dev
            software: standard
            async_media: false
            websocket: false
            ping_interval_seconds: 0

          appservice:
            address: http://mautrix-telegram.matrix.svc.cluster.local:29317
            hostname: 0.0.0.0
            port: 29317
            id: telegram
            bot:
              username: telegrambot
              displayname: Telegram bridge bot
              avatar: mxc://maunium.net/tJCRmUyJDsgRNgqhOgoiHWbX
            ephemeral_events: true
            async_transactions: false
            as_token: "{{ .as_token }}"
            hs_token: "{{ .hs_token }}"
            username_template: "telegram_{{ `{{.}}` }}"

          matrix:
            message_status_events: false
            delivery_receipts: true
            message_error_notices: true
            sync_direct_chat_list: true
            federate_rooms: true
            upload_file_threshold: 5242880
            ghost_extra_profile_info: false

          analytics:
            token: null

          provisioning:
            shared_secret: disable
            allow_matrix_auth: true

          public_media:
            enabled: false

          direct_media:
            enabled: false

          backfill:
            enabled: true
            max_initial_messages: 100
            max_catchup_messages: 500
            unread_hours_threshold: 720
            threads:
              max_initial_messages: 50
            queue:
              enabled: false

          double_puppet:
            servers: {}
            allow_discovery: true
            secrets:
              nahsi.dev: "{{ .DOUBLE_PUPPET_SECRET }}"

          encryption:
            allow: true
            default: true
            require: false
            appservice: true
            msc4190: true
            msc4392: false
            self_sign: true
            allow_key_sharing: true
            pickle_key: "{{ .pickle_key }}"
            delete_keys:
              delete_outbound_on_ack: false
              dont_store_outbound: false
              ratchet_on_decrypt: true
              delete_fully_used_on_decrypt: true
              delete_prev_on_new_session: true
              delete_on_device_delete: false
              periodically_delete_expired: true
              delete_outdated_inbound: true
            verification_levels:
              receive: unverified
              send: unverified
              share: cross-signed-tofu
            rotation:
              enable_custom: false
              milliseconds: 604800000
              messages: 100
              disable_device_change_key_rotation: false

          logging:
            min_level: info
            writers:
              - type: stdout
                format: pretty-colored
  data:
    - secretKey: db_uri
      remoteRef:
        key: pg-mautrix-telegram-app
        property: uri
  dataFrom:
    - extract:
        key: mautrix-telegram-secret
      sourceRef:
        storeRef:
          kind: SecretStore
          name: kubernetes
