apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mautrix-telegram
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: dock.mau.dev/mautrix/telegram
              tag: v0.2607.0@sha256:5a8c0e02f6333c7610ca429a2d643f15ea02fcf52e95647af6e76d5d5cbc78f3

            command: [/usr/bin/mautrix-telegram]
            args:
              - -c
              - /data/config.yaml
              - -n

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
              seccompProfile: {type: RuntimeDefault}

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1337
        runAsGroup: 1337
        fsGroup: 1337
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: {type: RuntimeDefault}

    service:
      main:
        controller: main
        publishNotReadyAddresses: true
        ports:
          http:
            port: 29317

    persistence:
      config:
        type: secret
        name: mautrix-telegram-config-secret
        globalMounts:
          - path: /data/config.yaml
            subPath: config.yaml
            readOnly: true
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
