apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mautrix-telegram
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 5.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: dock.mau.dev/mautrix/telegram
              tag: v0.2609.0@sha256:03e79bcf076da566a9984b0bc06151acbf71e3df9cd2e291142713ad9ebff980

            command: [/usr/bin/mautrix-telegram]
            args:
              - -c
              - /data/config.yaml
              - -n

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
              seccompProfile: {type: RuntimeDefault}

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1337
        runAsGroup: 1337
        fsGroup: 1337
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: {type: RuntimeDefault}

    service:
      main:
        controller: main
        publishNotReadyAddresses: true
        ports:
          http:
            port: 29317

    persistence:
      config:
        type: secret
        name: mautrix-telegram-config-secret
        globalMounts:
          - path: /data/config.yaml
            subPath: config.yaml
            readOnly: true
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
