apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stalwart
  namespace: default
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: stalwart
    namespace: flux-system
  values:
    livenessProbe: null
    readinessProbe: null
    config:
      server:
        proxy:
          trusted-network: [ "10.50.1.0/24" ]
    certificate:
      certmanager:
        enabled: true
        issuerRef:
          name: "letsencrypt"
        dnsNames:
          - &host stalwart.nahsi.dev
    service:
      type: LoadBalancer
      annotations:
        external-dns.alpha.kubernetes.io/hostname: *host
        load-balancer.hetzner.cloud/uses-proxyprotocol: "true"
      ports:
        http: 80
        https: 443
        imaptls: 993
        smtp: 25
        submissions: 465
        imap: null
        pop3: null
        pop3s: null
        sieve: null
        submission: null
    persistence:
      existingClaim: stalwart
