apiVersion: v1
kind: Secret
metadata:
    name: supersync-secret
type: Opaque
stringData:
    allowed_emails: supersync_me@nahsi.dev,Gallyamovdanis19@gmail.com
    jwt: wQv/9Z8bIXs11pSuEKif3jebM4+JfEw21jjt+8xRBdc=
