apiVersion: v1
kind: Secret
metadata:
    name: supersync-smtp
type: Opaque
stringData:
    SMTP_HOST: ENC[AES256_GCM,data:d+199gbI44oocSV7cTs=,iv:2N/QVVfYTKMdnK8/bCtJA6WqSpcDacvY59GKsKgfz+4=,tag:y/WWLmbK0CiT+VzE3IAgIg==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:lLyl,iv:7FjTNKbXqJX7Ibb1+SPqRzWj4liPAVBT+XSbbmD6SK4=,tag:pgdFjaPtbEktqGRq1mq3yQ==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:EYsi28w0EnxhYt+1fmeXWoA=,iv:IU9+3DzuaQLozccnmbXR12e+YxwhzIlCraYC+sSz3kQ=,tag:pYva6vEOjMej4BGTkV/P8w==,type:str]
    SMTP_PASS: ENC[AES256_GCM,data:KPbmzU4LHlKCPpidSlcrFA628JeywuAL,iv:pgsXfHrEQL2WQrflDyfgwlgCvbwPvvax1JHj1zbi+4w=,tag:fGNbTeLPKH4liQTJ99vvMg==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:5WgB4wR1WX7ockifu7OXMLj8iwAa4gCnx2g5Jbevtw==,iv:6Z9bOnx1WvKtyj3iJW1AFLKFax/lKJ1WpR2HzIKudXc=,tag:s62efvv9qbxeB+RPjKHoEw==,type:str]
sops:
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0QXF2c1lRdjhoWW5lM0Yz
            c2RHZUlucW5RanJGVXkzVVduWVdFT2E0eGtRCjF1ME1SVnNEZjZPcVZkYkszOWp6
            MXVEMVk3K3BQNE9Pd2V0emJLM2Jtdm8KLS0tIFJ0YnpYeHRZSURxUXM4R1JxUVAv
            Y1RXNVRzOUI1TkZKVFh3eFg1eExsNUUKsNCK7gnFRaSeA4ktLIvp8yl6+ucVtLYa
            htA2gMe63n8kXC3NxdKi7VhVTmYtWOf8+soPZYgNFD+1cvaQNQKmaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T09:16:07Z"
    mac: ENC[AES256_GCM,data:bUf5wz3eVVsTBezIyaQ5gqzBm0zq06Guo5hGBAxSyg1nYOwxqX5K0xHwqQy+576aXBAeNfy1GBSFuZ0Lms1GbbQByfehOWGTpV4C7+t/UFLopr1Fi8fnu8gyGshqJxUa3ChcpYs58misKqq+HvuY9Lw9ZnSB8cwzkcuTqJZgGQs=,iv:WPiimwZhzQHVCKEN1d4DmBWRdCnzEgxp7r95ESyScKI=,tag:0z9AQ1XWFJXAHrNfp0nb/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
