apiVersion: v1
kind: Secret
metadata:
    name: deepseek
    namespace: ai
stringData:
    Authorization: ENC[AES256_GCM,data:7BBL+tTS+YntZxBbz/xvEONKv4zAyvPmbwKw44byc6IfFMg=,iv:Jk6hhHKutPiwVTKomudfizFQtfORlpEneokkl9DnXTs=,tag:RCyvA1iW6b4rmVxmMN8FGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UHRhV3ozN0pLVTFCL2Q5
            TlBTZnlrbElDaXdGek4zZmR3YitqSkxQQnk0CkR3aFhOQy9Ydk5kN1RtVWlRSUdr
            cS9zbThYZVJ3WXNDZm9KaWZPeFBESG8KLS0tIG1FTTNmWTJGRE9IeE5Bcnh2MWpz
            ays5c1VwSjc5VXp3Q3hRbGo4NDlSazAKyN5BwIQAzgfGIZOBmIcb6+lzqj3EoyGI
            p4CUNbwIA4WrQ/ZYwhdgGKpTK7jacLvOct6LZ3DrfLuToCYpyE8Kbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T15:49:18Z"
    mac: ENC[AES256_GCM,data:ZeEIJugJPMlH0DzWyh3FZFyx3cSppVhNKYfB2XyMv9e84l5wHGVilarqAAAWq9RR+KZhz9YLZFcVCHbtUOhdQyKfPEQPMk/63FpyS4nzDo+3uLINb2ZbWXaO5w5XY8O63lERDazZrPjukebARmvALp0MPSGHkZO3w+to5ZVjvQY=,iv:3qIJXENwmkqeKJGxKuuiaCkW0iKydo4VsZDP13LvQ0A=,tag:FwyC7K1nR12rzdB0PW9/aw==,type:str]
    version: 3.13.1
