apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng
spec:
  secretStoreRef:
    kind: SecretStore
    name: kubernetes
  target:
    name: searxng-config
    template:
      engineVersion: v2
      data:
        settings.yml: |
          use_default_settings:
            engines:
              keep_only:
                - duckduckgo
                - brave
                - wikipedia
                - marginalia
                - github
                - stackoverflow
                - duckduckgo images
                - duckduckgo videos

          engines:
            - name: marginalia
              inactive: false
              disabled: false
              weight: 1
              api_key: "{{ .MARGINALIA_API_KEY }}"
            - name: duckduckgo
              disabled: false
            - name: brave
              disabled: true
            - name: wikipedia
              disabled: false
            - name: github
              disabled: true
            - name: stackoverflow
              disabled: true
            - name: duckduckgo images
              disabled: false
            - name: duckduckgo videos
              disabled: false

          categories_as_tabs:
            general:
            images:
            videos:

          general:
            instance_name: "SearXNG"
            enable_metrics: true

          server:
            limiter: true
            image_proxy: true
            method: GET
            public_instance: false

          search:
            safe_search: 0
            default_lang: en-US
            autocomplete: ""
            favicon_resolver: ""
            formats:
              - html
              - json
            ban_time_on_fail: 5
            max_ban_time_on_fail: 120

          outgoing:
            request_timeout: 5.0
            max_request_timeout: 15.0
            pool_connections: 100
            enable_http2: true

          ui:
            default_theme: simple
            theme_args:
              simple_style: dark
            query_in_title: false
            results_on_new_tab: false
            url_formatting: pretty

          plugins:
            searx.plugins.calculator.SXNGPlugin:
              active: true
            searx.plugins.tracker_url_remover.SXNGPlugin:
              active: true
            searx.plugins.unit_converter.SXNGPlugin:
              active: true
  dataFrom:
    - extract:
        key: searxng-vars
      sourceRef:
        storeRef:
          kind: SecretStore
          name: kubernetes
