apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-crds
  namespace: flux-system
spec:
  interval: 30m
  path: ./flux/apps/networking/gateway-api-crds/app
  prune: true
  targetNamespace: networking
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
