apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-mariadb-operator
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 15m
  prune: true
  wait: true
  targetNamespace: mariadb-system
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  path: ./flux/infrastructure/controllers/mariadb-operator/app
