apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: grimmory-mariadb
spec:
  rootPasswordSecretKeyRef:
    name: grimmory-mariadb-root
    key: password
    generate: true
  database: grimmory
  username: grimmory
  passwordSecretKeyRef:
    name: grimmory-mariadb-user
    key: password
    generate: true
  storage:
    size: 1Gi
    storageClassName: ceph-rbd-retain
  image: docker-registry1.mariadb.com/library/mariadb:12.3.3@sha256:2bdff1534a7e569fecaf4b10b66ad0d410806e382d9db29ba305448addda97c4
  replicas: 1
