apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: grimmory-mariadb
spec:
  rootPasswordSecretKeyRef:
    name: grimmory-mariadb-root
    key: password
    generate: true
  database: grimmory
  username: grimmory
  passwordSecretKeyRef:
    name: grimmory-mariadb-user
    key: password
    generate: true
  storage:
    size: 1Gi
    storageClassName: ceph-rbd-retain
  image: docker-registry1.mariadb.com/library/mariadb:12.2.2@sha256:350261292d0129fd4b24f537dcf05ecd3ebe34d39d5b592af551f38310e7a167
  replicas: 1
