apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: grimmory-mariadb
spec:
  rootPasswordSecretKeyRef:
    name: grimmory-mariadb-root
    key: password
    generate: true
  database: grimmory
  username: grimmory
  passwordSecretKeyRef:
    name: grimmory-mariadb-user
    key: password
    generate: true
  storage:
    size: 1Gi
    storageClassName: ceph-rbd-retain
  image: docker-registry1.mariadb.com/library/mariadb:12.3.2@sha256:a02fe89cb597d4375812b2eac90cf9d0775d4686daa7f7cc750ebbcad7525bbc
  replicas: 1
