---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slskd-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-retain
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slskd-incomplete
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-retain
  resources:
    requests:
      storage: 20Gi
