apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceph-csi-rbd
spec:
  chart:
    spec:
      chart: ceph-csi-rbd
      version: "3.13.1"
      sourceRef:
        kind: HelmRepository
        name: ceph-csi
        namespace: flux-system
  interval: 1h
  values:
    nodeplugin:
      registrar:
        image:
          tag: v2.11.1@sha256:e01facb9fb9cffaf52d0053bdb979fbd8c505c8e411939a6e026dd061a6b4fbe
      plugin:
        image:
          tag: v3.13.1@sha256:97b7308c14289b93da7257a54cd7c30c8161c488b8507722c3ad0cac4511f765
    provisioner:
      provisioner:
        image:
          tag: v5.0.1@sha256:405a14e1aa702f7ea133cea459e8395fe40a6125c088c55569e696d48e1bd385
      attacher:
        image:
          tag: v4.6.1@sha256:b4d611100ece2f9bc980d1cb19c2285b8868da261e3b1ee8f45448ab5512ab94
      resizer:
        image:
          tag: v1.11.1@sha256:a541e6cc2d8b011bb21b1d4ffec6b090e85270cce6276ee302d86153eec0af43
      snapshotter:
        image:
          tag: v8.2.0@sha256:dd788d79cf4c1b8edee6d9b80b8a1ebfc51a38a365c5be656986b129be9ac784
    csiConfig:
      - clusterID: "0f97afb5-e33d-48cb-b27a-4a7ea168b1b7"
        monitors:
          - "10.2.13.10:6789"
          - "10.2.13.20:6789"
          - "10.2.13.30:6789"
    rbac:
      create: true
    storageClass:
      create: false
    secret:
      name: ceph-csi-rbd-secret
      create: false
