apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 1h
  chart:
    spec:
      chart: immich
      version: 0.12.0
      sourceRef:
        kind: HelmRepository
        name: immich-charts
        namespace: flux-system
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Deployment
              name: immich-server
            patch: |
              - op: add
                path: /spec/strategy
                value:
                  type: Recreate
          - target:
              version: v1
              kind: Deployment
              name: immich-machine-learning
            patch: |
              - op: add
                path: /spec/strategy
                value:
                  type: Recreate
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: "v3.0.2@sha256:14390f3dc9512dc3273b12ccee6363d9be16c388699abc3f3fe0498bb9829937"
            env:
              TZ: Europe/Athens
              REDIS_HOSTNAME: "immich-valkey"
              IMMICH_MACHINE_LEARNING_URL: "http://immich-machine-learning:3003"
              DB_HOSTNAME:
                valueFrom:
                  secretKeyRef:
                    name: pg-immich-superuser
                    key: host
              DB_PORT:
                valueFrom:
                  secretKeyRef:
                    name: pg-immich-superuser
                    key: port
              DB_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: pg-immich-superuser
                    key: username
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: pg-immich-superuser
                    key: password
              DB_DATABASE_NAME:
                valueFrom:
                  secretKeyRef:
                    name: pg-immich-app
                    key: dbname
    
    valkey:
      enabled: true
      persistence:
        data:
          type: persistentVolumeClaim
          existingClaim: immich-valkey
    
    immich:
      metrics:
        enabled: true
      persistence:
        library:
          existingClaim: immich-photos
    
    server:
      serviceMonitor:
        main:
          labels:
            obs.nahsilabs/metrics: "true"
      controllers:
        main:
          containers:
            main:
              resources:
                requests:
                  cpu: 500m
                  memory: 1Gi
                limits:
                  cpu: "2"
                  memory: 3Gi
                  gpu.intel.com/i915: "1"
    
    machine-learning:
      controllers:
        main:
          containers:
            main:
              image:
                repository: ghcr.io/immich-app/immich-machine-learning
                tag: "v3.0.2-openvino@sha256:6b3c1f779df2e0f93be57bb2ad15681a43b7731cb325e8e66be7d984eca1949d"
              env:
                MACHINE_LEARNING_PRELOAD__CLIP__VISUAL: ViT-L-16-SigLIP2-512__webli
                MACHINE_LEARNING_PRELOAD__CLIP__TEXTUAL: ViT-L-16-SigLIP2-512__webli
                MACHINE_LEARNING_PRELOAD__FACIAL_RECOGNITION__RECOGNITION: buffalo_l
                MACHINE_LEARNING_PRELOAD__FACIAL_RECOGNITION__DETECTION: buffalo_l
              resources:
                requests:
                  cpu: 200m
                  memory: 5Gi
                limits:
                  cpu: "2"
                  memory: 10Gi
                  gpu.intel.com/i915: "1"
              probes:
                startup:
                  enabled: true
                  custom: true
                  spec:
                    httpGet:
                      path: /ping
                      port: 3003
                    periodSeconds: 10
                    failureThreshold: 180
      persistence:
        cache:
          type: persistentVolumeClaim
          existingClaim: immich-ml-cache
