---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-ml-cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-delete
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-valkey
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-delete
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-immich-photos
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
    - nconnect=8
    - noatime
    - soft
    - softerr
    - timeo=50
    - retrans=3
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nfs.lan#mnt/storage/media/photos#immich
    volumeAttributes:
      server: nfs.lan
      share: /mnt/storage/media/photos
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-photos
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: nfs-immich-photos
  resources:
    requests:
      storage: 1Gi
