---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen3-6-27b
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-delete
  resources:
    requests:
      storage: 30Gi
