apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-miniflux
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4@sha256:6138f19539304b585c6cafd1af82ca407f184139459a8e06f0880df4556d3588
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
    storageClass: ceph-rbd-retain

