apiVersion: v1
kind: Secret
metadata:
    name: miniflux-oidc
stringData:
    OAUTH2_PROVIDER: ENC[AES256_GCM,data:TWU5zQ==,iv:uuhVAsMP9e0AtNfp25kDR7RByGiagb9kL9SzHqc/DTw=,tag:wSZtkWFKSXvsSCRaZm4l6g==,type:str]
    OAUTH2_CLIENT_ID: ENC[AES256_GCM,data:I2OLBn07kepksvF7ocbMgw==,iv:0APcu1ftnSoEHXrngqF0bXLQDz/ZqAo6UognJRoUjVs=,tag:8Q3ilHt/9psQFE4kHxknjg==,type:str]
    OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:B/GAH++4O/sTwfn/TvWzWnVMiTqpp4NSU0PsRN9Ft65oXl6KObvpbHRuR97gyooSY35WuvlBGQ21GhInS8vAs40ETvKpDOT3QXELpzYbhizOhyYWoXFnFcQoG430N7vR03b+K6f7LSBKOcCtD9PDTv7Mro2biwG3qfO5Kmumgvs=,iv:wxHpOJGYyjb34kh3nUEAZlDWpfX91fTueg62xA03nlY=,tag:XxPNkWXaKGLuOrO1R8mtiA==,type:str]
    OAUTH2_REDIRECT_URL: ENC[AES256_GCM,data:xKYDA3MaOQq0dIEjKlV3joB/46vZhGjJmtbrcm+WoNOpbAYuDGg8kkG+,iv:5dc94E89+bClm+fsg6cnqaFUcEwbcrhqNGJZMS9qqlE=,tag:JnMgLxhd0OXhe3yRFKMQuQ==,type:str]
    OAUTH2_OIDC_DISCOVERY_ENDPOINT: ENC[AES256_GCM,data:Hj+0vZWHIh8egZhl/JFK3VL8h05IlZ6/6SEUV2w6M16HClO3vqiavNA3wPP7jA==,iv:mESqRjC7VxJELqqmh+/0h+A1aHc8QDDcc8Tf+HDKJ60=,tag:oKammGu/9EniL0aNh16PPA==,type:str]
    OAUTH2_USER_CREATION: ENC[AES256_GCM,data:RA==,iv:bNZfEhjrb8srzzFYfJAu/Rjh4NhnnGdvyzxnD/h4rfs=,tag:izXl+G3Vg8L5D/2+qN+j0A==,type:str]
sops:
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTllZUWZSdTM2K2ZZZHB3
            WktaWm0vOS9mV1BpK0Zqb2lpV29tbmNCVmtZCjhmazJLWEliajBjVEltUnJVa3Vu
            b0FGWUo4c2MwMStxSXZBWnl1RnJmSk0KLS0tIDJnS2UrS1RmcjNYY0VnaXVZMzJ0
            VFR6UjRhMC9PTktMYVg0cysyZXlMd3MKSJZGYNxUY6OKNv3jjWbqZqzvwySLwSKl
            DaAfu6eNm8+KuP7HYScB1mcEiVFOSHBErEazP59NtXSjM8KPbTqWsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-28T20:01:44Z"
    mac: ENC[AES256_GCM,data:RX0x93P/jKnvy/hadVSoWGmXxFNPyu4QvSuJjTMPHkQ77b+U9s876I1Y2h6LqDDNsP45FOwQ0dw/JKx2H06HqXzrlpaCbrlH5mX+Uj5wbRd9QGxEy/2v9IOqeOAefp2K16nISwmNXhIKQ6zDt2V+cqOLy3EICzNfpAwF0gxGu8A=,iv:j6wu0qBUMRE4qfyFLHrlVEpwQkQlYXkbFMUkUHS875g=,tag:+ZU1EqTaMBXRNkVlVykhKw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
