---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-retain
  volumeName: pvc-ae8a0fe7-a03f-42cf-85f2-a1a6bb99eecf
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-video
spec:
  capacity:
    storage: 1Gi # doesn't matter
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-sonarr-video
  mountOptions: 
    - "nconnect=8"
    - "hard" 
    - "noatime"
  nfs:
    server: nfs.lan
    path: /mnt/storage/media/video
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-video
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-sonarr-video
  volumeName: sonarr-video
  resources:
    requests:
      storage: 1Gi
