machine:
  certSANs:
    - talos.nahsi.dev
---
apiVersion: v1alpha1
kind: TimeSyncConfig
ntp:
  servers:
    - time.cloudflare.com
  useNTS: true
---
apiVersion: v1alpha1
kind: KubeNodeConfig
labels:
  cilium-bgp: true
---
apiVersion: v1alpha1
kind: KubeletConfig
extraArgs:
  rotate-server-certificates: "true"
---
apiVersion: v1alpha1
kind: SecurityProfileConfig
workloadIsolation: true
---
apiVersion: v1alpha1
kind: FilesystemTrimConfig
interval: 168h
---
apiVersion: v1alpha1
kind: FilesystemScrubConfig
interval: 168h
---
apiVersion: v1alpha1
kind: UnattendedInstallConfig
provisioning:
  wipe: false
---
apiVersion: v1alpha1
kind: ResolverConfig
nameservers:
  - address: 10.2.15.2
