apiVersion: v1alpha1
kind: HostnameConfig
hostname: odroid-1
auto: off
---
apiVersion: v1alpha1
kind: LinkConfig
name: enp6s18
addresses:
  - address: 10.2.15.10/24
routes:
  - gateway: 10.2.15.1
---
apiVersion: v1alpha1
kind: UnattendedInstallConfig
provisioning:
  diskSelector:
    match: disk.dev_path == "/dev/vda" && disk.transport == "virtio" && disk.size == 200u * GiB
