machine:
  network:
    interfaces:
      - interface: enp6s18
        dhcp: false
        addresses:
          - 10.2.15.20/24
        routes:
          - network: 0.0.0.0/0
            gateway: 10.2.15.1
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: odroid-2
auto: off
