apiVersion: v1alpha1
kind: HostnameConfig
hostname: pergamon
auto: off
---
apiVersion: v1alpha1
kind: LinkConfig
name: enp6s18
addresses:
  - address: 10.2.15.70/24
routes:
  - gateway: 10.2.15.1
---
apiVersion: v1alpha1
kind: KernelModuleConfig
name: nvidia
---
apiVersion: v1alpha1
kind: KernelModuleConfig
name: nvidia_uvm
---
apiVersion: v1alpha1
kind: KernelModuleConfig
name: nvidia_drm
---
apiVersion: v1alpha1
kind: KernelModuleConfig
name: nvidia_modeset
---
apiVersion: v1alpha1
kind: UnattendedInstallConfig
provisioning:
  diskSelector:
    match: disk.dev_path == "/dev/sda" && disk.model == "QEMU HARDDISK" && disk.size == 200u * GiB
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: comfyui-models
volumeType: partition
provisioning:
  diskSelector:
    match: disk.wwid == "eui.002538da21a151c6" && disk.serial == "S649NL0TA48827H" && disk.transport == "nvme" && !system_disk
  minSize: 900GiB
  grow: true
filesystem:
  type: xfs
mount:
  disableAccessTime: true
