apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synapse-mas
spec:
  secretStoreRef:
    kind: SecretStore
    name: kubernetes
  target:
    name: synapse-mas
  data:
    - secretKey: shared_secret
      remoteRef:
        key: mas-vars
        property: SYNAPSE_SHARED_SECRET
