apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-synapse
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4@sha256:2b124b4c9e9710a449b868fc72ae59bcb2907386d48ddb3e7a7f82491ac0d1e1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 5Gi
    storageClass: ceph-rbd-retain
