apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-synapse
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4@sha256:c4d03ff9119154edbdae8879313cdf0aa5143a26e7ae400ca3ebe22dfc680a73
  primaryUpdateStrategy: unsupervised
  storage:
    size: 5Gi
    storageClass: ceph-rbd-retain
