apiVersion: v1
kind: Secret
metadata:
    name: synapse-smtp
stringData:
    secrets.yaml: ENC[AES256_GCM,data:85O6N3s20OJVxPBqTzEzlL63GnVEIwhIYttMAjI8G5vbrfWtq9rrIp+XgPLfgIDOtRRXBk68+tdQqW+9bGToV+e0tPhQcGHyUNfaBtoYvqhQj1u4k0VN88rvqIITpVzdS1pJb9PF18i9Kd6RrDRb8dveKnrcCyqXrDDDyB1IrXTmCGcQIFr5q7+WVFypM0B/0W/AHLvkAvb2mwhtk1Z+ezWNRNtaSH7JXNmmBbWTtn9pLYpl8iyRwLIcH6+EfZrm9HImr16aO/iuNhxdeAK41A==,iv:PDRxYRRhyVIj0ZT+r/cqV3IE0ZkH7sZNFg5zcaLeIC4=,tag:aTE/0oBdPOVTjNUOu93H+Q==,type:str]
sops:
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSi9jb0NKbTZtMXc4S1ZG
            YlZBU0k2WGgzZGVXV2lFRHFIMVZqL3BCUzBZCnBZS1NyNHppY0lkZllxT2NwakNi
            Qlo1OGRaRitsZDJEVjFFYUxvV1B5MUUKLS0tIDFPY1BaSGFleFE0bFZnZHRIUUJK
            eTdqeWpWVkxUU1hVbmo1Z2x1YUFXQkEKV8Eg8Id7LKWlxw4q65xEydTSFQtNVi8k
            pfKpNXNLKqoIVS5Cnx3meC6RdUOhxigjM8FKG6ANw+Xmuo0IkQjvlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T12:17:42Z"
    mac: ENC[AES256_GCM,data:NMqyxsS1O7K1Z7tB5WMysZ8woXAGOtnqVY/ADgZKUKxfC/rCoy1ANuzJnpCcocomu1qC4rzetel0gW/Yc3d3WtGSK2IZe25k5ljtTf7StvcMNpIrK1FZrTWTv9GclAqJp8MjCs57JTI/rRpVlQHyT1ok0Q/gET+0ATVBDhKcKtM=,iv:uYRq0BjdaAHUDoZt7N8pRC71oiFckM4xg1Hg/48Uj1w=,tag:8PM/A4qCSxfmNfF7e5XsrQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
