apiVersion: v1
kind: Secret
metadata:
    name: synapse-s3
stringData:
    S3_ACCESS_KEY: ENC[AES256_GCM,data:v8cqIR5sFg==,iv:V6KGdzOTMmxiZMO4Nx49I5bLb/K1Flad0PBojSXvCYA=,tag:6qojqCbvyVwRLkj4Q4EoxA==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:JxBtjvnfNpXghxrEoVjtcGHzYJAhOii4almSPn6oRafIxRi0LKavahl90e4sHhkpjKfMjidtCPU=,iv:tyTsZugs4dHPMx/n4hroIpFI1burHriWWMSXpiFcBnc=,tag:0/Q71qHGGbgYAEgzPbe5XA==,type:str]
sops:
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZERYU0J1VnpqcUdoRVVz
            clhib0swNnpHanJyZnVmcmRYM0FUZWwwbmc0CmgxM21RbjJSZzZzek41TTV6YUVl
            SWRjZkladHQva2NNWEdnWnBQMTUvMXMKLS0tIGJ4VzdTc1BzeVVHZ2NRYWpFYTVH
            THRlZlVyMEtoTGZyYWFjZHVRMzJnZUkKa7qAzxA+jYb5Xq7J3aJtiGElohWfigHY
            4YoPPngBNcklTpvfNeDhJfrBRVBIqVCtgY6DhHuxLitLbjENh78UbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T12:17:42Z"
    mac: ENC[AES256_GCM,data:OsCIyAT1jNg2CHHJeYlVfegsM9NIwkk0ohAQAqlpTHa3s09aUIHkd8iHn/Lo6GSUoDaFF9SNtkbsaGz9ox5s3NDi0UVVcPTM6bg3aNycG28voJeOrKi8TN/VKfZQe36EwOXP5WyGkpnPZ+fSN6C1FU2EAqb8oNZzD+ryA18xrjg=,iv:UMRgWTt8vZpOzlbaFWuh+rdDFOhv4RoTr2DE7c4/OoQ=,tag:/OPVPyTtMyB1p2kxLcUTXg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
