apiVersion: v1
kind: Secret
metadata:
    name: synapse-secret
stringData:
    signing.key: ENC[AES256_GCM,data:IJlDOjP8u8jGDhqsUXAAccncSs3Z5H6RZnRAKC6dtgs8gLFdU0e3t4HLb/LBWOApyOK3Fy0kaqPVnQ==,iv:5vl8QFxR9seXZMgiq8VtlMbGIV/qe/YIY5sNNpNAl1g=,tag:03KAX3mQnf09eaR2kN7brg==,type:str]
    macaroon: ENC[AES256_GCM,data:Z1DUOH8CGVeIK4za7UpyWwT0BLvMWsNbQqMyYI+fG5jUa8iBIX5fvJZzbADKa3oxfh4bYfQ/NeC+iqxlrYQ47w==,iv:jyLUEKDkr0RfK/d0eKBvQmJOFJ1P7VaQFBHZ9fFR4SM=,tag:UWiLl9lhXjIPkD5WSIvYSg==,type:str]
    registration_shared_secret: ENC[AES256_GCM,data:lvc6fbIi7yUNlqBK6Th280fnqa0YH6VrH6urmpH230V+TKtjrJHc8Jn4PDcaACVBVzZ/8BrwxuUdImcjNSjIMA==,iv:lBmSJtq/f4CELa7PAGyKFVMRB3H6WaZvZEwKHz8e5oI=,tag:jWhn902oPksH1zd5k0us6g==,type:str]
sops:
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsck5vOEhQL3NybkFTLzR1
            K0t5OUtTK3BHcUZQVnpTaHYrd0EwLzZRdmhNCjRJb2F2a09JbmJseWIzbzNxa0ZG
            cnhLenJ5Umw3L0lsT3lhM09Oa1Y1MUUKLS0tIC9ibUEvdVliMjZwV0g0WFpUbjk2
            MnZzaHFxNzdnZUdPaklqSHZ5YjJ1TTQK1q46GSGMOQskrYYoMUFTOmkCYqSnDFol
            jeZtBxKdCREpJGjTDyk+PPK+EkqVOEas0cG6JqBKkeqqc5okpyFxYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T12:17:42Z"
    mac: ENC[AES256_GCM,data:m1Y1SEwq0d5LjKE1gI0Qq++bsbbsS8YfrreLJgQ7QFXzOBLwve5l3nJS7RyE/E6lqfB2sZLf5UUvgF8TIHLZKY0VzYXm7vc4YXJV5Qq991c6RYqvcW2cCo/3ZIRzxY7+UwirhVi4Blt58PQqn7+dvf+vAq4olM97fchOddGWi2Y=,iv:Z6U5L3MIHDun5LqgGMHAosP4DnlsbCfwkrK0eTTt85g=,tag:eADM2lm29DKqZtql442BPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
