apiVersion: v1
kind: Secret
metadata:
    name: hf-token
stringData:
    HF_TOKEN: ENC[AES256_GCM,data:tH9ib/7z3QJgRJ/XA+CzNrKrrdfbesahIaFC8yS+6mZE5flJ7g==,iv:dh9vTt/llJEQD71At52PrSmMmvImG1Inc+r4+rbs90E=,tag:9h98ar6UYpDQ7BeW8xezBQ==,type:str]
sops:
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMkgwaDc2NlovdmpiQ2lH
            Wno2cHNGeTVwVUxUenBHc0YxRTU1UTNUTm5ZCkdmR055cGRuSnY4U3JYNmxkNnBZ
            NGtyTHNSbFNkV2FZcTdLSkRaL25tZ0UKLS0tIDBRdW1zcWtaR1N2d3lHM1ZyZEdE
            NXZiVnlpMVFPNUJRQWJnRHR4QXZRVU0Ks/Tx6z2JtqZm21lKtPvknsQcXsEsSrDU
            mj67Jjf986L6tq+cO5zyRT9StT1++D1LjNZQqLIFRcGuBcPFjc4H0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T11:26:26Z"
    mac: ENC[AES256_GCM,data:aeltexPDLNgPWmLcLekqaWXRe7vJG4Yk4AiEt4A8YBp6nWM09n6IqHdS373hPKk4l577AAWBPrkc33c6f9CYp6BOA5GqkBvNDdWmonuYte9p3N0UV6lXuQ5zjSBfwKaeR3v8wCl3/wvFKofUnbkkuWFNFbj4aPs7jrPwzePF3zw=,iv:5qYoNrdScQW9Lk4lhxQ/rug2kvwTxsM/Weh+Ni+GXww=,tag:wK/Y2ccKDsmNhggQgMJ+Ng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
