apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vllm
  labels:
    obs.nahsilabs/metrics: "true"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: llminferenceservice
      app.kubernetes.io/component: llminferenceservice-workload
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
