apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-lemmy
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4@sha256:b38bee8f92acd6d7276d5be32e9af36a0ea72c9d339945f1ae205a2acc3cbb89
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true
  managed:
    roles:
      - name: app
        superuser: true
        login: true
  storage:
    size: 5Gi
    storageClass: ceph-rbd-retain
