apiVersion: v1
kind: Secret
metadata:
    name: lemmy-smtp
type: Opaque
stringData:
    LEMMY__EMAIL__CONNECTION: ENC[AES256_GCM,data:Gc91b5Qh2H2tFH04QmuNiHcmRzvwi+Q1XZo4BSMHnyIxcvjkI885m4I4pG0i2VHh68d5pCABBuhGfIRA5QKZN6GRNdh6onBpWy27M8Q=,iv:mWU8jHRphIR1bE4PnoTau467x+Ez6GOnD/5cf8Npmls=,tag:3RiJ0JT+vRCTIbq6MSs7bA==,type:str]
    LEMMY__EMAIL__SMTP_FROM_ADDRESS: ENC[AES256_GCM,data:i6PA0yX4mhsrsm42yTr1V2s=,iv:wc2T2WEEiVivrpr8lTEHSrqv4La/bB3dBKX0otd6f/k=,tag:CLFtd4BkgEWuj/iiaagzqg==,type:str]
sops:
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2N0gwUGhHMDQvUjgvMUly
            QU5DSUEwSExCZU9xQ1VMdlhOcy9CTFI5eDBJCjdTNGZQQ09ua29waFJrOVVzNzhq
            WWNIa3hFcUJCOFZQbUZiOEU2UXRUS1UKLS0tIDVteE9Mb0hZdTJyVzlpbDM0RkIy
            WDF5ZFBlZytndlQ5TlpYRnZHNk1UNXMKP/4GC8kb+8SdoSZZqHWa0mzCEw35R5qx
            JQwiXe49e7bN3naWPwhwqHEUvaIPEfOr/3dZaqwxHaP2boIDTEBDjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T19:56:12Z"
    mac: ENC[AES256_GCM,data:yEP06LBTY43YtYEwrB7GMPa0jF+8KdULv5EV8BfDsvWZ9SPMau4CMd3qI7MEb/FD/iHhQHfIG7ZmpTHC2ZdiAmrXuiJBGCN1A1nv0KSIY7l8+2JOPmsOPozRfPTRR2GoP1tCctEO8xZlPMiIa1QKAl0HQ5fBdUriQNEZI0TaVhM=,iv:IBJdZMEZ8aSg+u9AHHuiyHzm61ClKeALKHf4XMqbYx4=,tag:dCZpzx54Y15Hl6JLgy61Xg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
