apiVersion: v1
kind: Secret
metadata:
    name: lemmy-secret
type: Opaque
stringData:
    pictrs_api_key: ENC[AES256_GCM,data:wbhBXESPRw3xVQU3NoQduPBeVVsjeygxDPS2Kvwl8By94JbEn/iwlrYobZxH9pfU+qu7IukMMwKmtnRcv2lR/w==,iv:Ms6LS7kKSYXF3qwY2wgLez7Qiypq+7gx4AG0NGh5I2k=,tag:9H6N1nny4W5fsHeFhTLTcg==,type:str]
sops:
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYktMSm1wZWcveFZUR3U4
            TXJ0K3lMdWgrOE5STTU5WVBCM0R1WjB1b1M4CmVYZEpPUU9oNUtuTlZlSm5IbldZ
            eEZBSytDMXlHNDlQYTYreXJJRy84OU0KLS0tIHBVUzN2ajdMRHdCcVFrVEVJSlZZ
            ZVZhWkZUNXl6SHBzSXNScFovZGdpZzAKTQxz1k4Tvs2edxwQoWf4g4WUqTwBfUDW
            T3++nzwbUa/24eWv8/lgzA2wS0z3kKalymw+QTmHv3jCA4gJDs1ynA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T19:51:21Z"
    mac: ENC[AES256_GCM,data:5eNriqVDjrL8577ApDgtAjxv9I09ctz+txJT3MeW9Qj9X0qsatNcUsgBWFrnHHl+Ee4p1Pf60QyXLzDEKWfLI8Lgy9Fy99vAFQdgp6pJ5oyskU/7NXmlIpDGfDuzeo8+HylLkW+qQIWFXwSl/Rl63dUn1lLu6q2lKtQZAF8/W0c=,iv:c3Y//Y+fhvb6Kw4nM5OkBUvsSjelLdj6ph3QI7BWPRU=,tag:YZsI2hY2D5Kj4wZ8ov4Q8w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
