apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-myspeed
  namespace: flux-system
spec:
  path: ./flux/apps/myspeed/app
  targetNamespace: myspeed
  prune: true
  dependsOn:
    - name: infra-prometheus-operator-crds
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: obs-myspeed-dashboard
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-grafana-operator
    - name: obs-grafana
  path: ./flux/apps/myspeed/obs
  targetNamespace: observability
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
