apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-prowlarr
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4@sha256:21497884139dc18c9015e11f02a28a28962d9f670a42d9bf4481b7fd37b5213c
  storage:
    storageClass: ceph-rbd-retain
    size: 4Gi
