apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-prowlarr
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4@sha256:7af186660aead1b948d827ef1c52c20a8d2cb7b2a4089424b8f612e0a61dc2f9
  storage:
    storageClass: ceph-rbd-retain
    size: 4Gi
