apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-prowlarr
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4@sha256:1a8ef3dc0dc214c1764660291b29a98288b13753c09e9981b86eaf0c75de8bdc
  storage:
    storageClass: ceph-rbd-retain
    size: 4Gi
