apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-mas
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4@sha256:21497884139dc18c9015e11f02a28a28962d9f670a42d9bf4481b7fd37b5213c
  primaryUpdateStrategy: unsupervised
  storage:
    size: 2Gi
    storageClass: ceph-rbd-retain
