apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-mas
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4@sha256:1a8ef3dc0dc214c1764660291b29a98288b13753c09e9981b86eaf0c75de8bdc
  primaryUpdateStrategy: unsupervised
  storage:
    size: 2Gi
    storageClass: ceph-rbd-retain
