apiVersion: v1
kind: Secret
metadata:
    name: mas-smtp
stringData:
    SMTP_HOSTNAME: ENC[AES256_GCM,data:GoiShDYinTSJb2ipElw=,iv:hPrEbWxlMRNnBTOseZqO1+HHYvTn4tAKVTwxNOhy0V4=,tag:cTuChy6FE+8DyeLBVLo+Iw==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:Y6ul,iv:hiEacgyIcP/uYhepUFOur/sZSoPXpPLuT3Kmxo4vRic=,tag:Qrq6C8koKSbamGlGbF7f8w==,type:str]
    SMTP_MODE: ENC[AES256_GCM,data:zKAs,iv:xS4s766dWQoMEMAEqDUxFCx9GXUsFPbArQ3AuNmxOGU=,tag:1h+FIphetFMmAyYRfb3mdQ==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:KvTW+dIpequ4kxaPYbVdjGk=,iv:iyOaXjIGvQnEJYYrmNdjfgRcdx7ZpMs8Y5AG4ACVko0=,tag:iBku4F0YqcSQNh8TJ5VZvA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:lH9YbZRAsalYr7UBun2JA36bpUC7QQKu,iv:8GZZojDVg0qBUpVogT9BvBmdckCcQctP8dJJYO1Ic44=,tag:W2g3wGe+9X40HjzBZDLOyQ==,type:str]
    EMAIL_FROM: ENC[AES256_GCM,data:3YY+runy2VyP+mZnLKECwZ/BKCI0rhf2ej4=,iv:rz7FFLnVtpf5FSl/YF2z73KIouXJwoA7qMQyMDwgw18=,tag:nbEWXZYZ/9Znqy0sO6X6MA==,type:str]
    EMAIL_REPLY_TO: ENC[AES256_GCM,data:Hwhw6rE9uQHNWmyF49qjXcSxkG+TI+es7eE=,iv:0Yuguer3DhuBjJ4mk2hsk6XlRPU9WES6U9oOMAitDYs=,tag:SWAEA373rty37Mm9R2/Clw==,type:str]
sops:
    age:
        - recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZHRPMUIwZGFydmVJSUpN
            K1BnWWhFK2twbTlSdDBscG8zMkdlSndzR1RjCjRadGxVdUttQVhLNzd3Ukt2dkd2
            eDE1Z1RCM1IvT1gvQ0VJeDh2VGQwKzQKLS0tIDZJYU5LeDM5QUZhcU9pZ3ZyL1Rr
            NzJqTXlNaWl5Yk9YUXc0Q3FtUTI3c2cK3rMeGvpH+6MBT2MxSaLzdmLo/CvdmG7o
            88I4nVBi3kOnNmQloOKxuT6HDfefo+KbzM+oyDDirmVdck55ipDfAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T13:14:38Z"
    mac: ENC[AES256_GCM,data:FI6EVscrCeKyTmzJyjxl/QbBeXFthbydRAtm9Qwu+U8TMfCd3dYNW35+Y8WZBziQ10IFoi78XwvGCcPTdpEt1Eahysw0GLYFe8Fwb1bkWH3yALxy/3ElD5S/uxYdlnO8A+T2PMMgxn8zOaH465mOqscmiCQ/7X6aWatwbTTLiyU=,iv:Vv62xf22zTekuXkbWvZMNKo5DsE2EhLPNuUV0YaRNGU=,tag:PKdG8/Gyptd75CJ4sD8pbg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
