apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-llm-d-infra
  namespace: flux-system
spec:
  interval: 1h
  timeout: 5m
  retryInterval: 2m
  prune: true
  targetNamespace: ai
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  path: ./flux/apps/ai/llm-d-infra/llm-d-infra
  dependsOn:
    - name: infra-gateway-api-crds
    - name: infra-agenticgateway-crds
    - name: infra-agenticgateway
