apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-companion
  namespace: flux-system
spec:
  dependsOn:
    - name: app-invidious
    - name: infra-prometheus-operator-crds
  path: ./flux/apps/youtube/companion/app
  targetNamespace: youtube
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: obs-companion-dashboard
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-grafana-operator
    - name: obs-grafana
  path: ./flux/apps/youtube/companion/obs
  targetNamespace: youtube
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
