apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mas
spec:
  secretStoreRef:
    kind: SecretStore
    name: kubernetes
  target:
    name: mas-secret
    template:
      engineVersion: v2
      data:
        config.yaml: |
          http:
            listeners:
              - name: web
                resources:
                  - name: discovery
                  - name: human
                  - name: oauth
                  - name: compat
                  - name: graphql
                  - name: adminapi
                  - name: assets
                binds:
                  - address: '[::]:8080'
                proxy_protocol: false
              - name: internal
                resources:
                  - name: health
                binds:
                  - address: '[::]:8081'
                proxy_protocol: false
            trusted_proxies:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
              - 127.0.0.1/8
              - ::1/128
            public_base: https://mas.nahsi.dev/
            issuer: https://mas.nahsi.dev/

          database:
            uri: "postgresql://app:{{ .pg_password }}@pg-mas-rw.matrix.svc/app"
            max_connections: 10
            min_connections: 0
            connect_timeout: 30

          secrets:
            encryption: "{{ .ENCRYPTION_SECRET }}"
            keys:
              - key: |
                  {{ .RSA_KEY | nindent 14 }}
              - key: |
                  {{ .EC_KEY | nindent 14 }}

          matrix:
            kind: synapse
            homeserver: nahsi.dev
            secret: "{{ .SYNAPSE_SHARED_SECRET }}"
            endpoint: http://synapse.matrix.svc:8008/

          passwords:
            enabled: false

          branding:
            service_name: nahsilabs

          email:
            from: "noreply@nahsi.dev"
            reply_to: "noreply@nahsi.dev"
            transport: blackhole

          upstream_oauth2:
            providers:
              - id: 01KSWKABKK3Y4YV91MY6P8FCA9
                human_name: Authentik
                issuer: "https://auth.nahsi.dev/application/o/matrix/"
                client_id: "{{ .AUTHENTIK_CLIENT_ID }}"
                client_secret: "{{ .AUTHENTIK_CLIENT_SECRET }}"
                token_endpoint_auth_method: client_secret_basic
                scope: "openid profile email"
                allow_existing_users: true
                claims_imports:
                  localpart:
                    action: require
                    template: "{{ `{{ user.preferred_username }}` }}"
                  displayname:
                    action: suggest
                    template: "{{ `{{ user.name }}` }}"
                  email:
                    action: suggest
                    template: "{{ `{{ user.email }}` }}"
                    set_email_verification: always
  data:
    - secretKey: pg_password
      remoteRef:
        key: pg-mas-app
        property: password
  dataFrom:
    - extract:
        key: mas-vars
      sourceRef:
        storeRef:
          kind: SecretStore
          name: kubernetes
