---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-private-advertisements
  labels:
    cilium-bgp: "true"
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchLabels:
          cilium-bgp-private: "true"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "private-ip-pool"
  labels:
    cilium-bgp-private: "true"
spec:
  allowFirstLastIPs: "No"
  blocks:
    - cidr: "10.2.14.1/24"
  serviceSelector:
    matchLabels:
      cilium-bgp-private: "true"
