apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "private-ip-pool"
  labels:
    cilium-bgp-private: "true"
spec:
  blocks:
    - cidr: "10.2.14.0/24"
  serviceSelector:
    matchLabels:
      cilium-bgp-private: "true"
