---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-public-advertisements
  labels:
    cilium-bgp: "true"
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchLabels:
          cilium-bgp-private: "public"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "public-ip-pool"
  labels:
    cilium-bgp-public: "true"
spec:
  blocks:
    - start: "37.98.199.181"
  serviceSelector:
    matchLabels:
      cilium-bgp-public: "true"
