apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: gateway
spec:
  clientIPDetection:
    xForwardedFor:
      numTrustedHops: 0
  path:
    escapedSlashesAction: KeepUnchanged
  headers:
    lateResponseHeaders:
      set:
        - name: Strict-Transport-Security
          value: "max-age=63072000; includeSubDomains; preload"
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway
