apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/home-operations/sonarr
      tag: 4.0.14.2938

    env:
      TZ: "Europe/Athens"
      SONARR__INSTANCE_NAME: Sonarr
      SONARR__PORT: 8989
      SONARR__APPLICATION_URL: "https://shows.nahsi.dev"
      SONARR__LOG_LEVEL: info

    service:
      main:
        ports:
          http:
            port: 8989

    ingress:
      main:
        enabled: true
        ingressClassName: nginx-private
        annotations:
          cert-manager.io/cluster-issuer: nahsi.dev
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: "Arr"
          gethomepage.dev/name: Sonarr
          gethomepage.dev/icon: sonarr.png
        hosts:
          - host: &host shows.nahsi.dev
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: sonarr-tls

    persistence:
      config:
        enabled: true
        existingClaim: sonarr
      media:
        enabled: true
        existingClaim: nfs-sonarr-video

    podSecurityContext:
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534

    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
