---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: digarr-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-retain
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: digarr-backups
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-retain
  resources:
    requests:
      storage: 2Gi
