apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: obs-node-exporter
  namespace: flux-system
spec:
  path: ./flux/observability/collect/node-exporter/app
  targetNamespace: obs-collect
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: obs-node-exporter-dashboards
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-grafana-operator
    - name: obs-grafana
  path: ./flux/observability/collect/node-exporter/obs
  targetNamespace: obs-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
