apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: companion
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: quay.io/invidious/invidious-companion
              tag: latest@sha256:cd5c3dae67bdb025eb5c849963418bbcb3c77d94fd13b8c6a017111a329f6865
            env:
              SERVER_ENABLE_METRICS: "true"
              SERVER_SECRET_KEY:
                valueFrom:
                  secretKeyRef:
                    name: companion-secret
                    key: COMPANION_KEY
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        fsGroupChangePolicy: Always
        seccompProfile: {type: RuntimeDefault}

    service:
      main:
        controller: main
        ports:
          http:
            port: 8282

    serviceMonitor:
      main:
        enabled: true
        labels:
          obs.nahsilabs/metrics: "true"
        endpoints:
          - port: http
            path: /metrics
            interval: 30s
            relabelings:
              - action: replace
                regex: .*
                replacement: companion
                targetLabel: instance

    persistence:
      cache:
        type: emptyDir
        globalMounts:
          - path: /var/tmp/youtubei.js
