apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: hindsight-api-auth
spec:
  length: 48
  digits: 12
  symbols: 0
  noUpper: false
  allowRepeat: true
  secretKeys:
    - token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hindsight-api-auth
spec:
  refreshPolicy: CreatedOnce
  target:
    name: hindsight-api-auth
    creationPolicy: Orphan
    deletionPolicy: Retain
    immutable: true
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: hindsight-api-auth
