apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-hindsight
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4@sha256:2b124b4c9e9710a449b868fc72ae59bcb2907386d48ddb3e7a7f82491ac0d1e1
  primaryUpdateStrategy: unsupervised
  postgresql:
    extensions:
      - name: pgvector
        image:
          reference: ghcr.io/cloudnative-pg/pgvector:0.8.4-18-trixie@sha256:8285ceb870b819f5854c1343e775cbafe23579bdb676c981ec6795d6466f8300
  storage:
    size: 10Gi
    storageClass: ceph-rbd-retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: app
spec:
  cluster:
    name: pg-hindsight
  name: app
  owner: app
  extensions:
    - name: vector
      ensure: present
