apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-hindsight
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4@sha256:dabf20b4a1d0d2d26ad3f39b25dc57a270ffdaf0ca7105a6c897dc9f17c0ac83
  primaryUpdateStrategy: unsupervised
  postgresql:
    extensions:
      - name: pgvector
        image:
          reference: ghcr.io/cloudnative-pg/pgvector:0.8.4-18-trixie@sha256:8285ceb870b819f5854c1343e775cbafe23579bdb676c981ec6795d6466f8300
  storage:
    size: 10Gi
    storageClass: ceph-rbd-retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: app
spec:
  cluster:
    name: pg-hindsight
  name: app
  owner: app
  extensions:
    - name: vector
      ensure: present
