apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-hindsight
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4@sha256:7af186660aead1b948d827ef1c52c20a8d2cb7b2a4089424b8f612e0a61dc2f9
  primaryUpdateStrategy: unsupervised
  postgresql:
    extensions:
      - name: pgvector
        image:
          reference: ghcr.io/cloudnative-pg/pgvector:0.8.4-18-trixie@sha256:8285ceb870b819f5854c1343e775cbafe23579bdb676c981ec6795d6466f8300
  storage:
    size: 10Gi
    storageClass: ceph-rbd-retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: app
spec:
  cluster:
    name: pg-hindsight
  name: app
  owner: app
  extensions:
    - name: vector
      ensure: present
