apiVersion: v1
kind: Secret
metadata:
    name: hindsight-s3-auth
    annotations:
        kustomize.toolkit.fluxcd.io/prune: disabled
type: Opaque
stringData:
    access_key: ENC[AES256_GCM,data:3/XSRbBk+cIE,iv:PqqY0mCcHS7KUV2KKhwM5EK21EsVJTbHuxI06WqpuSc=,tag:7g/a26CM9/OjBHPi3dU7bg==,type:str]
    secret_key: ENC[AES256_GCM,data:Vi+yF9Gu7KUqqlCgVMS1WqfAsRu5shF4M1qfjeDtUvkD0LCti+iBUuyZt1Gux7a6trEOo9UTsxk=,iv:GJLWfEp38gaj3TpkkwG5UKsk9fLV1q9RdEAongLP/qw=,tag:qWpM6v7jKKeBKtniGHA/cg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBraVBLNHJqZzRqam85TDVF
            T2lDaHVRa0NMdVdyZW90YVJhU0Z1T2JTRHdRCkNpQUNjb2FlNjIxRDF6azNZc1NX
            NWEzYmFOZk5yNlhjdEZ1NXQ5Q2oyaFEKLS0tIEN2ajdwTS9OUklRdmVPTkpOOE82
            UTdYOUFTeDNQMzhPYjYzL055OFNqZFkKKqiyqNm9degpVd+F/cZ3QBkBZ3d6xlr3
            +dnVntpLoexCFVtFnt48+Xv13AomNKexB5CfsBJeWW4EaSddwYn5sQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T20:38:31Z"
    mac: ENC[AES256_GCM,data:aeN8g5o/TxW9mNt/HporcmtcWbrx4LmD2ejBuXHnONoT1y2T8Zk0qP07xVk4pB8rYinsW9jOw05cfCSO6a3kd3N5OIx5sTbgVriYub7ddVZoFubFB7mj7BVnFzKRP/mqHEDfHBlQkTvx2QGx9hvOJ5IEg3R5DMu5fR4Z0lz/oEE=,iv:ouTD0UQJnAXqiVGSuBXNBy925p2KVDz7CpTOlk5i6xU=,tag:RhOuvhykbCaf+2e0xpRwTA==,type:str]
    version: 3.13.3
