apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: qwen3-5-2b-llm
spec:
  ai:
    provider:
      openai:
        model: Qwen/Qwen3.5-2B
      host: qwen3-5-2b.ai.svc.cluster.local
      port: 8080
