---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen3-0-6b
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-delete
  resources:
    requests:
      storage: 10Gi
