apiVersion: v1
kind: Secret
metadata:
    name: babel-auth
    namespace: arr
type: Opaque
stringData:
    BABEL_AUTH_USERNAME: ENC[AES256_GCM,data:7Azmp0w=,iv:i3rCzk4/iXXTbxzKFS9+zyNh1DCgXoeycUwImAKrDGs=,tag:mzh5ljDkxm4U1zllBmV1OQ==,type:str]
    BABEL_AUTH_PASSWORD: ENC[AES256_GCM,data:7OBY3JjshjkpACL6D/Hf/2MoQBRASXTKRXpeBmu9fAY=,iv:vG2eDr/y9EOAjAz8qrAiSWVyObo0W86xiWtBySTTFEc=,tag:kuStNi2nsEzCI7K5G5imaA==,type:str]
    BABEL_WEBHOOK_SECRET: ENC[AES256_GCM,data:/XPTr9GGDVU1u5jywoKeJmubCrQgS9cn5QJjpLCqNsA=,iv:trqgwXX8kR0ie6lmnAJzFauJ3lnqoF4fQYfzIE6jffo=,tag:iHnL6+A5DpFIelN1M2TbDQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNLzkvRmZmdUVvTGlQWVE3
            WFkwWDVOdUpraDJyNXo0OFFKckZPbXBBejNBCm05UjQrVkt3MjBZMjc2YTlvaXpT
            N1Y0KzRsUENDeDFYb3JJNlMvcW0valkKLS0tIHh0dFFhZjJjZm5HYmZHVENEblVI
            dGFzdzlWcmZ5Q0NkOHhXK3I1eHBKYVUKPc5E2Y+fH7Yz+Dcv14ZGOv74gdBq6wPK
            VxxFlMCWLt3OkIfjCGyBMUS8CZicDt6bcRqqksTpla9LHcb2yKD9eA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T03:39:46Z"
    mac: ENC[AES256_GCM,data:dSyQ8IPRRaJzRcPDTAjbgSrMaarEhnOBQPlzB57uxU5DZR4vUI9EtPW1C/l/VzfqNDkBY/dU5VGhVH3sp9jgYtYtinfBdNgVgPOCX1kRb9Hkit3CA+deD74MpFbRA5ELzNzeVF8OsvMWNVFx+9tPcFT3KcHPcRv7y9kUzJk7MMM=,iv:ihOsZ/FtYvDVuWeratfzrd3Pa8Uk+TCkW2+6jJSqGSA=,tag:m8dQ7yNn+nxeaBcMHGlSRQ==,type:str]
    version: 3.13.3
