apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-state-metrics
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: kube-state-metrics
    namespace: flux-system
  values:
    image:
      registry: registry.k8s.io
      repository: kube-state-metrics/kube-state-metrics
      tag: v2.19.1@sha256:85108987d044b18a098126732f98602df408888c0f7d456241f5abefb9744bc1
    fullnameOverride: kube-state-metrics

    prometheus:
      monitor:
        enabled: true
        honorLabels: true
        additionalLabels:
          obs.nahsilabs/metrics: "true"
