apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.12.0"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 12h
  values:
    controller:
      kind: Deployment
      replicaCount: 2
      # for fixing the issue with vaultwarden websocket not working
      allowSnippetAnnotations: true
      config:
        annotations-risk-level: Critical
      publishService:
        enabled: true
      service:
        type: LoadBalancer
        externalTrafficPolicy: Local
        labels:
          cilium-bgp-public: "true"
