apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nahsi-dev
  namespace: networking
spec:
  secretName: nahsi-dev-tls
  issuerRef:
    kind: ClusterIssuer
    name: nahsi.dev
  dnsNames:
    - "*.nahsi.dev"
