apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-readeck
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.6@sha256:d7a81cb5da3182d95d0da5fabfb9e484e375db899dcd54b684105f1e8966e9ca
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
    storageClass: ceph-rbd-retain
