apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-readeck
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4@sha256:dabf20b4a1d0d2d26ad3f39b25dc57a270ffdaf0ca7105a6c897dc9f17c0ac83
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
    storageClass: ceph-rbd-retain
