apiVersion: v1
kind: Secret
metadata:
    name: opencloud-s3
stringData:
    STORAGE_USERS_DRIVER: ENC[AES256_GCM,data:/yauMP8o7siKTkWF,iv:mRcaOsRbPAUBMhkDhpYtPv3DeFh6rSJLOYjD6sQHdiY=,tag:PJiRuSo0SS9zuwj791D95w==,type:str]
    STORAGE_SYSTEM_DRIVER: ENC[AES256_GCM,data:HHWdJpTup/zOcA==,iv:iL7aKJanjibcbMdLfxRgvUGXKg+GQwd9/d+WYSJO0J8=,tag:24Kkm7ALCc32IApdtnewaQ==,type:str]
    STORAGE_USERS_DECOMPOSEDS3_ENDPOINT: ENC[AES256_GCM,data:1NPcaCeVVI/oYIr8Mf5FbTcL8QQswt4TZQ==,iv:6EagDXW7aGjKSWuYFWfTIfLwd415iNZAz9tYCnMGRbA=,tag:tJZiU2l5ea0G9E531vqXEA==,type:str]
    STORAGE_USERS_DECOMPOSEDS3_REGION: ENC[AES256_GCM,data:H1rrNN6s5mBg,iv:Ag9k4Dc5DCRsIcYTJBlbN/b4P0ndjKVS+mS2y3uOAV4=,tag:EQJrIKkrGuzvjxtnPaPOGw==,type:str]
    STORAGE_USERS_DECOMPOSEDS3_BUCKET: ENC[AES256_GCM,data:S2AU2672JH4/,iv:BD+kxMdTXgc1SCIY8XVrK2goB4M5Goxt83I6BWpz7Go=,tag:PGSVF4D84uL7L57MRsyTFA==,type:str]
    STORAGE_USERS_DECOMPOSEDS3_ACCESS_KEY: ENC[AES256_GCM,data:JXefLr2RQLbG,iv:W9kuLGz0PrFLj7aALeCIxvezDjoZ2A/RvFtJqlJN6bg=,tag:4ZCTaRRTbiROfd2kjRB9eQ==,type:str]
    STORAGE_USERS_DECOMPOSEDS3_SECRET_KEY: ENC[AES256_GCM,data:Jvx+rVMnn4WA3ilx0a6BIUvJpqCyEvFw5AngaZgc7cVtQO1M4IEhlk/IaucOs74pqgC7F4Eu9GU=,iv:9iZWKwbVR0Z6GHaSyHflx+LMLoc3gB+JAnUoK0yGnsk=,tag:KZDsdYyx66wJzUq7NHweSw==,type:str]
    STORAGE_USERS_EVENTS_NUM_CONSUMERS: ENC[AES256_GCM,data:IQ==,iv:/5JKr8Fze2zpTmHpmYn/2zMzXvTl/ZUe7HK0ULPMOdI=,tag:oj4AOylXfYBjJhxAWhvufw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUkQ2WU9NZWxKSFF2cEpk
            T3hKTW4rblZGVDcxZGEyOXVhRTROYm9pR2drCjdnMVNRYnhvTCs1c2N0RDdoblVI
            YmNxQzdqT0d3aEhXNkI0eWFWOE92dXcKLS0tIEJOc3N3cDI5Rkxza2NIeExGMnNX
            YW51aFJ6eERiUXp4c2NlcWJPdXBHNkkK7mFldwPW0W/WrGvg4Dme2kOxSAuI2rbt
            3zf5ugqw7p97R22HA0xZzO6bCMwunhvS3ctjOj07OjSXfC7eQ1e1wg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T10:11:21Z"
    mac: ENC[AES256_GCM,data:5CP1TfSqOGOlvVczUkopPj/oJIkjS5LDpA+tjENqPxPdcmHG03OlNQzKs5G6SZbdtJ+btP7LeLEcKW64VhcwPHEYKFdfrwLmRYcoLvn/uGU2kmQYdkrcr/xWOgFYAA0bPmOTWnJ43/aR4+XUWpxUVsNegBHXybLqLjaN4WYW7VE=,iv:MAmzAlz7UAs9oo2CxZLxQ1ed9hew3B3HtqJopDoes6g=,tag:cjY0EitG0jOrxhaDjuwirQ==,type:str]
    version: 3.13.1
