apiVersion: v1
kind: Secret
metadata:
    name: opencloud-oidc
stringData:
    OC_OIDC_ISSUER: ENC[AES256_GCM,data:1c/pEf8pJglemBseT+oX8EeNM8LP3n38KmEy+kTA5GxkLJ8o8Ubo2UWJFDr4FyM=,iv:oXdayC7XrNhMx648bS2lcTDfpZcSFsDOLiKmQEdx5O4=,tag:v+rn3BPcS4QSQwFrg9N6Sg==,type:str]
    OC_OIDC_CLIENT_ID: ENC[AES256_GCM,data:WkSNgjPNFWj1s1DX0kOqNg==,iv:GznD97kdwzqe2ybNwOXXkR6VfC5gozceahYePs8bRoo=,tag:fi7m8XIV2sG+akQot2t7SQ==,type:str]
    OC_OIDC_CLIENT_SCOPES: ENC[AES256_GCM,data:tI9mdUhMeafLiOVSc7j9GFlwDM7yTWDQzND5dhztfVBquMz482DU+XP/K8xxIa2V,iv:bkvvJryslPR/7ju4Tz14QOVXwER2BCj4O2Zyc7nVBvc=,tag:MrzMHmAiryLU+6sRBx/bOA==,type:str]
    OC_EXCLUDE_RUN_SERVICES: ENC[AES256_GCM,data:Bvv6,iv:e2iNZzYRjNhOvzlg8oEBCjl+e+3nWu7AFtCQQNHVhoo=,tag:xG+CrDmI4hiWKlBEYo//bA==,type:str]
    IDP_DOMAIN: ENC[AES256_GCM,data:jQ3EkiyDeQoMBTJkpyw=,iv:ZwcjDZx7GmGSYU6ki6amVk7ccWylkbHnYQ08ketdAYE=,tag:M1DK4W4erfyk/0mpc9714Q==,type:str]
    WEB_OPTION_ACCOUNT_EDIT_LINK_HREF: ENC[AES256_GCM,data:GnCyq/oZuqpfnXgTCfTs6wH+V8IagE6cwEa6xk9JNdVmRaMmRSIVHho=,iv:2R5YUMhOfu9Jivh2/FgkTY/vumplbPSAnoD2wiojGmk=,tag:umhP7Q+fnaLqZWZLIqg9+Q==,type:str]
    PROXY_OIDC_ACCESS_TOKEN_VERIFY_METHOD: ENC[AES256_GCM,data:xsFQ,iv:MEyxPyjwA7e7iIcjFQ2FHGZUJg+HfGIkja4nXFlpau8=,tag:vb42darTDgIjsGfu9Bi94Q==,type:str]
    PROXY_OIDC_REWRITE_WELLKNOWN: ENC[AES256_GCM,data:PvWEaA==,iv:foitbF3ghtuby9vtjmiwU0U+4V86WJ4GRv1FxllaHJA=,tag:46H3WElCFkxE+EP7cy54IQ==,type:str]
    PROXY_AUTOPROVISION_ACCOUNTS: ENC[AES256_GCM,data:S7dT6w==,iv:He9ujdIMGGa2+JuP4I428Eiwe1p9h1zFYfFjj1ed1Vo=,tag:0XYZsam/p+lpk9qiwtSlJQ==,type:str]
    PROXY_USER_OIDC_CLAIM: ENC[AES256_GCM,data:QN5k,iv:73nSB9lqmd93tDD5jVVFtdGD+UuKTM/pRQCRuKg6+80=,tag:tZVjWQfbEDIRmwheS1aoUw==,type:str]
    PROXY_AUTOPROVISION_CLAIM_USERNAME: ENC[AES256_GCM,data:riHH,iv:CdpJ3VSKwO0WfizCzzRflEgqzX1ncCpUiSH4I1mYc+E=,tag:geB9iyP0XSLDVLMH64Ic5A==,type:str]
    PROXY_USER_CS3_CLAIM: ENC[AES256_GCM,data:ZRw0SaOImdE=,iv:OsScwgU+gzlF2sXnwV7EYxw33XgUwL2vgsIalJPDMlc=,tag:jAoeuyTu5sjHW6lVoX39gA==,type:str]
    PROXY_ROLE_ASSIGNMENT_DRIVER: ENC[AES256_GCM,data:/icQlw==,iv:oLw51h7voWT2/nWaQshy6Ld7jPpbNSanC218WgvoVp4=,tag:692G7VvVjOsjOj4+A6OJFg==,type:str]
    PROXY_ROLE_ASSIGNMENT_OIDC_CLAIM: ENC[AES256_GCM,data:aLQ9wiIst+RpDlSz,iv:xHe/5bpubDniZv2kWgOBjL6mmE2Uk1GoHgm3y93Brc8=,tag:op5tGPq++Ls+Va5ACNPQ6A==,type:str]
    GRAPH_ASSIGN_DEFAULT_USER_ROLE: ENC[AES256_GCM,data:ldcjQiI=,iv:tSuTiuR8NR9Sp0lCxd25a7Mzuizgk+1UqmgIAesxVdg=,tag:eVgYzK3X+RpaqWcW0qeHtQ==,type:str]
    GRAPH_USERNAME_MATCH: ENC[AES256_GCM,data:+VbGPw==,iv:oQ1fAk5goau/MEveS85biPTOgCAk/AX3t8NS1OxhWRw=,tag:XByHZmcbzYaTGOPPFPQRcQ==,type:str]
    SETTINGS_SETUP_DEFAULT_ASSIGNMENTS: ENC[AES256_GCM,data:NK44jII=,iv:sqIVDlih+18zwHxOkfQVGjE8qU3GMP0gMEr8y50UUjI=,tag:Ru6ZO339owe0OTjbGdMbvA==,type:str]
    OC_ADMIN_USER_ID: ""
    FRONTEND_READONLY_USER_ATTRIBUTES: ENC[AES256_GCM,data:WuLsG1sXysOyzc0qUAwgpu+Otg/Psb5uPB5DWzntG0lL224SsT4YZAqB5T728AwGPFAB6/KrOogwwPFur9u325EXBkYLyUXUC8TOtvZZhIMiQpdexSJvITR56ETP6LwK54j6LYdq8OXLrS/yMpVFl+cY3ZikH5cHUg==,iv:UWagVDFGXBluft/vpZDdWqQUdmdBoFsIbSTaXX0naGU=,tag:jEcMNQHDnA2PwymFKZ36Ng==,type:str]
    WEBFINGER_WEB_OIDC_CLIENT_ID: ENC[AES256_GCM,data:NuLf1EZSqOOqB2eX4r8I8A==,iv:aHf3AjFprN/4CS1XkWpnLvMR8JEhmtfh2r3Nee3M0dU=,tag:59chnZTPlhI1cBAqEAM4Dw==,type:str]
    WEBFINGER_WEB_OIDC_CLIENT_SCOPES: ENC[AES256_GCM,data:EQ36thcWi15NWe4fN9akbXX53C0T1RQkS6Qrz2BD1TBV,iv:/ZLnAqEYH9H7EKhOCsY3O7k4DyPKoSmbKRirty6+VYM=,tag:h21SOB2UZ+rMrM6nVK17zw==,type:str]
    WEBFINGER_ANDROID_OIDC_CLIENT_ID: ENC[AES256_GCM,data:tih0ebJ1jbhFQZ9HDNUgOg==,iv:fSLBFn2+ImwCC1D88RbS8D0xUymnUA4YPAEcacyw45A=,tag:HykgIixK17UQvFYpUcK+og==,type:str]
    WEBFINGER_ANDROID_OIDC_CLIENT_SCOPES: ENC[AES256_GCM,data:TPle0cEwYOkNxtG8aEIjUeftwLpYgKrBQJ/c7G86V8rjlwGx8dPs2vASr7nEwFZ1,iv:NpOTGhZyJEeJAtMNE/GJQnzGtOOP2cHn3uGzOtstIJ8=,tag:Frtm+Bo/gYw8wM5B/TQGqA==,type:str]
    WEBFINGER_IOS_OIDC_CLIENT_ID: ENC[AES256_GCM,data:xdiMH8yRHfF4zsRz9vNxEA==,iv:MRxHc7zBaGJJPJD3ue/l25RRGQTp2eVC0Mu/ihQURvA=,tag:OHfz89EYp5sfjIow+jYoQQ==,type:str]
    WEBFINGER_IOS_OIDC_CLIENT_SCOPES: ENC[AES256_GCM,data:fEp75pElfbbdeQRxc6G3XhRtG12+LjJtSB6mK/+dvwM/TgsbM8GYtYsfGzxPlQGY,iv:SbGAinLABEWOrrsysOqEs4e0ILtmM5aVGEUZVa+6FqM=,tag:GYOW7gzpLWQ9gQMWZKIwJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdkt0VndGcGg5d2JMRDdY
            Y0lydGtvYy9lbXAxTm1XRkMyaXk0dExrUDB3ClRydGlUYkwwS3p2b25wdVR3K29t
            Z3ovbTllVHRHZGplZWROUHpFcU41cFEKLS0tIFllL3NEVDJmV3R2bmhKdGNtWDJV
            YkdOSUJqajJYbUl3TGIzdUpKbU1TcXcKqjTcgESvB5sHPy/L0jKjlg9bdubfExiY
            0gTHcx1hhR77wbwFBr5+5r8UzPmAHLehvmTkum69IaHspLpOc3L2Zw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T10:32:03Z"
    mac: ENC[AES256_GCM,data:MoY+kdNxT5jJbrJ1RLpmb0RZaKELIB2mkAlG0X2lq9gGmQYRwMVlR7mc1X/Je9KJ5QXoM3Zlx3zwmBQP+b4SGIaYGr1KIDpl1L/GMltKvQ2zkOxExUktUNG4RS7+Zp1/gORhLk192V0sW/f2KAdSWrdSFkUEzxiTwnJAkc2goGI=,iv:sVAh5rXHzur7sTS4hy2F7pBDiQUl5dgO3txrJOOY8MI=,tag:LcKTnh15Lf52EbHcJSlLZQ==,type:str]
    version: 3.13.1
