apiVersion: v1
kind: Secret
metadata:
    name: opencloud
stringData:
    IDM_ADMIN_PASSWORD: ENC[AES256_GCM,data:qHFwxNoxBBcrz8Ph4faEXvcKs48CcR0OhwYQk5IWZy+SHRjpJHb+C8nnALzcf6JktmSbtOBTl6ryLWeqNEld2w==,iv:ooxKBht6HWpsnoJa9XkN/rbkxE/UFIfz/e94OQSEDrI=,tag:yVjhLF7x6s9B1GIDeP0lVw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByN1B3VHZHejd6YTdZYnhX
            TTYvcFhLVnBXVS9NbTlaRVpYY2RwUVNpOTFvCmpwUzd6elYrbURLN255RS93Zkp2
            U2ROa1FhV0Vnakc2c3J4Yzdjc3poMFUKLS0tIGdtNVpLYmxzKzlqay9xMnlFd0E3
            dU9WeHRXZ3lOWFV4cHI1TDluUTFYWlUKcLAUCnFaEtUwwU8NzhMfXZI+ki6TvCJa
            1jrobk43L+4XsCwe48PT7dGz92hNHqVg9kr7P+7jgn28L4tbwPtL0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17kf3tfnhtv36pjscj7mzuv5dc0xjcj388764258uwgad78mzzs2qtu05pw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T10:11:21Z"
    mac: ENC[AES256_GCM,data:qjgQZGl29eOpLR8657V4FnVYXyfavhgIvN3/9hGsFxfIhXycBe/cgWXZH3HkgZcdrGTO1Cfck0wIM03MUJISYr9x8gKAS7J8Ups2OexjTcKjI3J8z7AEJiYj+o4iXfst0YVE9y0mATIebxQSBCTdIiUeRbG3skBjxkmUlwEBdS4=,iv:QfeDU8LSaiuuVInDaLGriXdMPWsEHthMLumxSbQBl90=,tag:kY+aj5QDzvKYqLD+IoBSdg==,type:str]
    version: 3.13.1
