apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-ai-llm-deepseek-v4-flash
  namespace: flux-system
spec:
  dependsOn:
    - name: app-ai-gateway
    - name: app-ai-providers-deepinfra
  path: ./flux/apps/ai/llm/catalog/deepseek-v4-flash/app
  targetNamespace: ai
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
